cql_tests.py
pyassertions.py
ttl_test.py

Add tests for TTL feature.
Unfortunately, the ttl tests take around 4.5 minutes to run. I tried to use smaller interval in my tests, but this produced unexpected failure due to a too fast or too slow execution.

Add tests for TTL feature

---

paging_test.py

By flattening the lists to not include dicts, they become
hashable, meaning the comparisons are 5x faster, critical
with data sizes of 5k-50k rows. Race condition was due to
variable definition coming after callback.

Fix runtime and race condition.

---

dtest.py

set log level to 'critical' to suppress (most) noise
there's perhaps a small risk of masking useful
information so I added an env var allowing
this behavior to be overridden by setting
SILENCE_DRIVER_ON_SHUTDOWN=false

quiet driver log noise on test cleanup

---

upgrade_through_versions_test.py

give better info about tags/heads being used
allow finding 'tentative' tags
change trunk to 3.0
update version from strings to tuples for easier handling
query tags direct from apache git, or local if configured

Improve upgrade tag discovery

---

assertions.py
commitlog_test.py

Work In Progress. Do not merge, this is only partial work, more will be added.
Current tests:
* Test default commitlog segment size
* Test default compressed commitlog segment size
* Test small commitlog segment size 
* Test small compressed commitlog segment size
* Test IGNORE commit_failure_policy 
* Test DIE commit_failure_policy 
* Test STOP commit_failure_policy 
* Test STOP_COMMIT commit_failure_policy 
We only test some of failure policies in Cassandra-2.0 due to the lack of memtable options, which produce inpredictable flushing of the commitlogs.

Add some tests for to commitlogs

---

auth_roles_test.py
cfid_test.py
consistent_bootstrap_test.py
cql_prepared_test.py
incremental_repair_test.py
paging_test.py
paxos_tests.py
schema_test.py
tools.py
ttl_test.py
udtencoding_test.py
upgrade_supercolumns_test.py
user_functions_test.py
user_types_test.py

Addresses #152 -- this solves the same problem as #175, but the pull request is sent to the correct branch :fireworks:
The proposed solution in #175 worked by replacing every test function on the class with a wrapped version. This implementation works by replacing the class's `setUp` method, which is called before every test.
It'd be nice to just wrap the class itself, rather than one of its methods, but we can't find the C* version for a class until after `setUp` executes and the cluster gets initialized (so far as I can tell). I tried instantiating the class and getting the version inside `since`, but that messed up class creation somehow and removed the `runTest` method. It might be useful to add functionality to `Tester` that allows us to find the version without instantiating the …

@since decorator work with test classes

---

global_indexes_test.py
tools.py

- Simplifies the `@require` decorator and makes it work on classes.
- Moves `@since` and `@require` decorations from methods to class level on `TestGlobalIndexes`.

Require class decorator

---

replication_test.py
tools.py
topology_test.py

- Makes the `no_vnodes` decorator work on classes and simplifies its implementation.
- Moves `no_vnodes` off of methods and onto classes where possible.

No vnodes class decorator

---

bootstrap_test.py

Part of addressing #182. Adds a function that uses `nodetool` to calculate the load on a node, and uses that function in `bootstrap_test:TestBootstrap.simple_bootstrap_test`. Caveats:
- As discussed in #182, `get_size` isn't robust enough to be used elsewhere - it's a one-off.
- The test fails -- the relationship between `node1`'s initial size and it's final size is off.
- `patient_cql_connection` throws an error, though it doesn't in other tests, as far as I've seen. See #182.
- Because of the failures mentioned above, I've gotten a little debug-statement happy. These should probably be removed, though maybe not until the problems are fixed.

Bootstrap size

---

tools.py

This decorator wasn't used anywhere. I think an unimplemented test is the usual use case for `unittest.skip`, so I don't see any point to keeping this decorator around. 
Objections?

removes unused not_implemented decorator

---

cql_tests.py

This solves the same problem as #192, but by welcoming the tests back into the fold rather than destroying them.

uncomments and updates 3 commented-out tests

---

incremental_repair_test.py

Slowdown multiple subsequent repairs test to not use 200 threads
@mshuler feel free to merge if this is enough to fix your yesterday's issue.

Slowdown multiple subsequent repairs test to not use 200 threads

---

bootstrap_test.py

Blocked on https://github.com/pcmanus/ccm/pull/245, which puts the behavior of `get_size` in `Node.data_size`.
I can add back the debug statements if anyone was particularly attached.
*****
This reverts commit 65dfa9607299006533f9dd6b9bb7aebd0b7348d5, reversing
changes made to 2cbf96f5d6ee2a95e7f7986e315567f6e3a2c4c8.
The changes introduced in the merged branch have been integrated into
ccmlib itself, making it unnecessary to do this calculation in the tests
themselves.

Revert "Merge pull request #184 from mambocab/bootstrap-size"

---

pushed_notifications_test.py

This PR fixes a problem with `pushed_notifications_test`. I know @aboudreault know's what's going on with these tests, so he may be the best reviewer.
I'm not sure this is the best solution. It might be better to have a `NotificationWaiter` initialized with `num_notifications=x` to wait for `x+1` notifications. The existing API is a little dangerous -- I think it encourages bugs like the one this PR fixes.
See the commit message, reproduced below:
****
This is a subtle bug in the test logic. In the initial implementation of the first test, we're waiting for 1 notification, so we used the default `num_notifications` value of 1. Because of the way NotificationWaiter works, though, that means it will stop waiting once it observes a single notification. That means that as long as the first …

increments minimum # of notifications to wait for

---

bootstrap_test.py

This test is not supposed to fail when using vnodes, but I haven't restricted it since it could catch a future bug that might happen with/without vnodes. The tests is running 3 times since sometime, it doesn't happen.

Add manual boostrap test for Cassandra-9022

---

repair_test.py

[CASSANDRA-8979](https://issues.apache.org/jira/browse/CASSANDRA-8979) improved repair not to stream unnecessary gc-able data.
This PR adds test for that.

Test for CASSANDRA-8979

---

consistency_test.py
tools.py

When writing and reading at ConsistencyLevel.ONE, there's no guarantee
that reads will see all writes.

Correct consistency checks for CL.ONE writes and reads

---

snapshot_test.py

This doesn't fix the failing `snapshot_test.TestSnapshot.test_basic_snapshot_and_restore` test, but exposes the problem more clearly.

Check sstableloader exit status, error if non-zero

---

incremental_repair_test.py

This should fix ``incremental_repair_test.py:TestIncRepair.multiple_repair_test``

Don't try to flush node2 while it's down

---

incremental_repair_test.py

These help prevent the test from being timed out.

Add print statements to the incremental repair test

---

tools.py

This allows uses like
@require(42)
def func():
pass
rather than unnecessarily requiring
@require('42')
def func():
pass
Strings will still work; this change just supports the [common use case](https://github.com/riptano/cassandra-dtest/search?utf8=%E2%9C%93&q=%22%40require%22) where the only information passed in represents the integer ID of a Jira ticket.

convert @require's argument to a string

---

deletion_test.py
jmxutils.py

Defect reported in [#9194](https://issues.apache.org/jira/browse/CASSANDRA-9194).
[Fails](https://gist.github.com/mambocab/87681ed3770e19345a21) on all 2.0 and 2.1 releases going back to 2.0.2. `nodetool cfstats` earlier than that doesn't support the way I get the memtable data size, so I don't know if it worked then.

test that memtable size calculation includes tombstones

---

dtest.py

Addresses #246. `ccmlib.Node.grep_log_for_errors` returns a list of lists of strings. This fix joins each of the lists into a single string to be compared in `__filter_errors`.
To demonstrate the problem and its fix, run
```UPGRADE_PATH=1_2:2_1 nosetests -x upgrade_through_versions_test.py:TestRandomPartitionerUpgrade```
That particular upgrade path will always throw an error, and since the tests in this `TestRandomPartitionerUpgrade` use the log filter, the errors will be used in the regex comparison that was throwing the `TypeError`. It should error out with a `TypeError` on HEAD fail correctly after applying this change.

Tester.teardown: accounts for lists of error lines

---

metadata_tests.py

This adds a test which does a concurrent compaction, repair and read.  In the middle of this we call nodetool resetlocalschema.  Causes issues. Written for 9249

add metadata reset test

---

deletion_test.py

Don't merge just yet -- I think this is the correct change, but I'm waiting for confirmation from Benedict [here](https://issues.apache.org/jira/browse/CASSANDRA-9194?focusedCommentId=14505980&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14505980) that this is the right metric to use.

changes mbean used for querying memtable heap size

---

snapshot_test.py

The previous version built the path with string formatting. This patch makes it use ccm's cross-platform tools for getting paths for executables.

uses platform-agnostic executable-specifying code

---

.gitignore
lib/cassandra-attack.jar.txt
thrift_hsha_test.py

Some devs were a little stumped as to where this jar lived. In testing, we have been wget'ing the file from the test master server, prior to dtest runs. Let's just add the jar to dtest, so there is no mystery.

Add cassandra-attack.jar from CASSANDRA-6285

---

dtest.py
tools.py

This addresses #238. My request for review has 3 parts:
1. Verify that the name-matching behavior described in `@require`'s docstring is the desired behavior.
1. This makes a hopefully non-invasive change to `dtest` and `dtest.Tester`. Previously, the directory used was calculated at object-definition/method-call time by grabbing `CASSANDRA_DIR` from the environment. Now, it's calculated at load time. This allows `@require` to grab the directory of the currently-running C* install without actually starting a cluster. Please check that this change makes sense before +1'ing this patch.
1. Since this behavior depends on some external state, I'm concerned that it :tada: _works on my machine_ :tada:. I'd like a reviewer to run the [shell script with the tests linked at this …

Require filter branch

---

auth_roles_test.py
auth_test.py
batch_test.py
counter_tests.py
cql_prepared_test.py
cql_tests.py
dtest.py
paxos_tests.py
schema_test.py
secondary_indexes_test.py
upgrade_through_versions_test.py

Was accepted to cql_connection and its family of
functions, but never used. Leftover from the old thrift
connection functions.
@mambocab or @aboudreault to review

Remove all instances of the ignored arg 'version'

---

topology_test.py

A node should not be able to rejoin a cluster after being decommissioned.
Should I lower the timeout on the log-watching? It'd be nice for failure not to take a full 10 minutes, but I don't want the test to flap, either.
Addresses https://issues.apache.org/jira/browse/CASSANDRA-8801

add test for CASSANDRA-8801

---

secondary_indexes_test.py
upgrade_supercolumns_test.py

These tests are only designed to be run on 2.1 at the highest, and for
2.2 and later they fail due to Java 8 compilation errors.

Set max_version for some upgrade tests

---

cqlsh_tests/cqlsh_copy_tests.py
cqlsh_tests/cqlsh_tests.py
cqlsh_tests/cqlsh_tools.py

Reverts riptano/cassandra-dtest#284
The reverted commit broke CI. CI has been fixed, so this un-reverts.

Revert "Revert "Cassandra 9306: cqlsh COPY tests""

---

repair_test.py

Some basic tests for CASSANDRA-5839 (27596a8) along with a few improvements to `repair_test.py`:
- some style improvements (5fec1d4, 4258a8f),
- removal of [mutable default argument](http://docs.python-guide.org/en/latest/writing/gotchas/#mutable-default-arguments) footguns (de5ef7e).
I do want the reviewer to sanity-check [this line](https://github.com/riptano/cassandra-dtest/blob/4258a8f832b7c0b2cc502db5196d2800fbd8e22f/repair_test.py#L310) -- I'm pretty sure we can ignore that error. It's generated [here](https://github.com/apache/cassandra/blob/d96a02a12e20bc2e0b096904ebe7a1d68532d2f3/src/java/org/apache/cassandra/db/lifecycle/LifecycleTransaction.java#L258) and appears to be a guard against invalid updates, not a fatal error.

Cassandra-5839

---

cqlsh_tests/cqlsh_copy_tests.py
cqlsh_tests/cqlsh_tests.py
cqlsh_tests/cqlsh_tools.py

Fixes a failing cqlsh test on trunk by using the same driver monkeypatching the cqlsh does in all cqlsh tests, not just the new copy tests.

monkeypatches driver for all cqlsh tests

---

cqlsh_tests/cqlsh_copy_tests.py

The copy tests are broken pre-2.1, for example [here](http://cassci.datastax.com/job/cassandra-2.0_novnode_dtest/24/testReport/junit/cqlsh_copy_tests/CqlshCopyTest/test_undefined_as_null_indicator/). Until I figure out formatting for 2.0, we should skip these tests.

skip copy tests pre-2.1

---

cqlsh_tests/cqlsh_copy_tests.py

This adds a format string, like in cqlsh itself, for `datetime`s in the cqlsh copy tests. This should fix [this test](http://cassci.datastax.com/job/cassandra-2.1_dtest/106/testReport/cqlsh_copy_tests/CqlshCopyTest/test_all_datatypes_write/), which is broken on 2.1.

add formatting for 2.1 compatibility

---

cqlsh_tests/cqlsh_copy_tests.py
cqlsh_tests/cqlsh_tests.py
cqlsh_tests/cqlsh_tools.py

Don't attach the cached functions to a class -- that makes it so it's treated as a method, so deserialize can't be called as a function afterwards. This puts them in a dictionary instead.
Causing failures on cassci like [this one](http://cassci.datastax.com/view/All_Jobs/job/trunk_novnode_dtest/65/testReport/cql_tests/TestCQL/select_with_alias_test/). I repro'd the test bug locally with this command:
```
$ CASSANDRA_VERSION=git:trunk nosetests cqlsh_tests/cqlsh_copy_tests.py:CqlshCopyTest.test_all_datatypes_round_trip cql_tests.py:TestCQL.empty_blob_test --verbosity=3
```
Fails on master, succeeds with this PR.

fix deserialize problems

---

pushed_notifications_test.py

Ensure nodes return an error message in case of TombstoneOverwhelmingExceptions rather than dropping the request. A drop makes the coordinator waits for the specified  read_request_timeout_in_ms.

Add test for cassandra-7886

---

pushed_notifications_test.py

Along with https://github.com/pcmanus/ccm/pull/291, this should
make sure that we don't collect NEW_NODE events from the cluster
starting up.  Sadly, I don't see any simple alternatives to adding the sleep()
line.

Ensure NEW_NODE notifications aren't errantly collected

---

cql_tests.py

This goes with CASSANDRA-9492, since the counter column is first alphabetically, we'll use that as the default validator

CASSANDRA-9492: Using stable ordering for all JDKs

---

repair_test.py

Apparently both of these flap! so skip 'em both. Failure for the newly-required test is [here](http://cassci.datastax.com/view/trunk/job/trunk_dtest/200/testReport/repair_test/TestRepairDataSystemTable/repair_table_test/)
Changes the existing @require to account for the new ticket, filed [here](https://issues.apache.org/jira/browse/CASSANDRA-9534)

changes require for repair history table tests

---

json_test.py

Python converts to operating-system specific line-endings on any stream
write or print call which causes failures when coupled with doctest's
<BLANKLINE> replacement logic.

Convert CRLF to LF in cqlsh_print on Windows.

---

cql_tests.py

This tests the bug described in [CASSANDRA-9565](https://issues.apache.org/jira/browse/CASSANDRA-9565).
It might be more appropriate to test this as a unit test, in which case we shouldn't merge this. Thoughts?

adds cql test for NPE in 'WITH WITH' queries

---

configuration_test.py

There's some cleanup in this PR. I can remove it if you don't want to review commit-by-commit. 1177cc0 is just whitespace fixes, and 10f640e cleans up imports, both in the file where I've added a test.
5a44306 is where it's at. On trunk, and on HEAD for 2.2, 2.1, and 2.0, this fails when the new setting for DURABLE_WRITES isn't respected.
I don't know if I'm happy with how readable this test is, so I'm looking for feedback there.

DURABLE_WRITES setting test

---

deprecated_repair_test.py

Test for [CASSANDRA-9570](https://issues.apache.org/jira/browse/CASSANDRA-9570).
In the future, when ```@Deprecated``` repair methods are removed, this test will be obsolete.

Add deprecated repair JMX API tests

---

rebuild_test.py

```nodetool rebuild``` test seems missing.
Added simple rebuild test that traces the steps of adding data center and rebuild from the other.
Also added verification for my fix for [CASSANDRA-9119](https://issues.apache.org/jira/browse/CASSANDRA-9119).

Add rebuild test

---

dtest.py

Updated environment variables DEBUG and TRACE such that they also accept class names along with true/false/yes/no, By inputting class name(s) (separated with a colon), you can set only those classes to have that level of logging.

Cassandra-5322 Making dtests more granular

---

dtest.py

This adds a `compact_storage` kwarg to `Tester.create_cf`. If truthy, it creates the table `WITH COMPACT STORAGE`. This is helping me with comparing the old row format to the new format that will be introduced in 3.0.
Since it's a kwarg at the end of the parameter list, it doesn't affect existing calls.

adds compact storage option to create_cf

---

rebuild_test.py

[9119](https://issues.apache.org/jira/browse/CASSANDRA-9119) hasn't been merged yet, so this test is failing on cassci; the first commit fixes that.
The next two commits are import and whitespace cleanup.
The final commit removes `allow_log_errors` from the class in `rebuild_test`; it still passes on the 9119 branch without it (at least locally), so we should catch errors if we can.

require and clean up rebuild test

---

CONTRIBUTING.md
configuration_test.py
rebuild_test.py

Updates CONTRIBUTING to reflect this style choice.
Follow up to feedback on #324. We use CASSANDRA-N instead of just N because some dtests will be related to tickets in other projects, such as the Python driver.
You can verify that there aren't any more instances of `@jira_ticket N` with
```
grep -r 'jira_ticket[ \d]*$'
```

s/@jira_ticket N/@jira_ticket CASSANRA-N/g

---

CONTRIBUTING.md

This is a starting point for the Python 3 `CONTRIBUTING` changes we discussed while reviewing #328. I couldn't think of any changes other than string formatting off the top of my head, but that list should probably get longer at some point.
I've taken the liberty of also mentioning PEP8 and import sorting. [`isort`](https://github.com/timothycrosley/isort) is the tool I used [here](https://github.com/riptano/cassandra-dtest/commit/2f29d9254a692e5954d5140e1dca7fcdb3696edd) and I think it's nice.
Feel free to propose things to add/remove. I tried to describe how we already do things and not to impose anything new.

adds style section to CONTRIBUTING

---

consistency_test.py

It seems consistency_test.py:TestAvailability.test_network_topology_strategy fails on Jenkins on all branches. However I cannot reproduce it on my box, it passes every time. At LOCAL_QUORUM a write should fail if only one node is up and two are down, given that rf is three. So I am guessing we need to wait for other nodes to notice, but it is only my best guess as I don't know how to download the node log files from Jenkins.

Trying to fix Jenkins failure, CASSANDRA-9102

---

cql_tests.py

There's some incorrect error checking that causes failures on trunk ([cassci](http://cassci.datastax.com/view/trunk/job/trunk_dtest/lastCompletedBuild/testReport/cql_tests/TestCQL/validate_counter_regular_test/)). 3cf8ce9 fixes that.
3e8e3e8 and aad92ce deal with some code that was commented out.
The rest of the commits are whitespace, markup, and various PEP8 cleanup.

Cql test failure

---

paging_test.py

@EnigmaCurry spotted this problem yesterday, we're probably needlessly consuming cpu
while waiting for something that might take a second or two.

Add a small pause when waiting for inbound pages

---

compaction_test.py

d0f67ce: As discussed in #327, this is a better solution to `TestCompaction_with_LeveledCompactionStrategy.sstable_deletion_test` flapping on 2.0. We still skip that particular test pre-2.2 (eb8c7ab), but the other tests are not skipped as they were in the previous PR. Instead, we use a flush, a major compaction, and log-waiting to block on a compaction.
587f821 should be reviewed on its own. It's justified in its commit message. It may expose a C* bug: compaction throughput runs at about 120-125% of the specified maximum.
The other commits are cleanup.
Requesting review from @shawnkumar since he wrote the tests and from @ptnapoleon since he reviewed the previous PR.

Major compaction cleanup

---

conf/cassandra-2.2_test-select.cfg
conf/trunk_test-select.cfg

At least running locally, they succeed now, as discussed over in #251.

re-includes tests from replace_address_test

---

deprecated_cql_tests.py

CASSANDRA-9695 got committed (and with great unit tests!). I made sure this passed on previously-affected versions (HEAD on cassandra-2.{0,1,2} and trunk).
I've also done the obligatory removal of unused imports and PEP8 whitespace fixes.

Unrequire in cql tests

---

datahelp.py
paging_test.py

This is mostly cosmetic change, but allows data given to datahelp.py
to have a line that breaks between the headers and the data descriptions.
I also took this opportunity to fix up the imports in paging_test.py
I vetted the change by running some of the paging tests and all looks well.

Prettify data

---

.travis.yml
cqlsh_tests/cqlsh_copy_tests.py
cqlsh_tests/cqlsh_tools.py
hintedhandoff_test.py
thrift_tests.py

(Thank you, @knifewine)
This adds a travis configuration file to the repo. It'll run `pep8` on changed lines, so idiomatic-ness will only improve.
It also runs `pyflakes` via `flake8` on all files. It only reports on importing errors, since @ptnapoleon fixed all those and all of this type of error found should be new.
This PR also removes unused imports and `from module import *`, as found by `pyflakes`, so we don't start off with failing linters. It also cleans up the imports with `isort` because why not?
For the errors we've ignored and for PEP8 checking on the entire codebase, we can take it in chunks, or just improve things as we change tests, with the help of this linting.

Add travis config with linter

---

dtest.py

We're already importing this from ccmlib.common here. In
zero tests do we ever use the dtest implementation, only ever the
ccmlib one. They're identical code.

Remove redefinition of is_win function

---

cqlsh_tests/cqlsh_tests.py

`test_describe` started failing (I assume) because of changes to the Python driver introduced in [CASSANDRA-9064](https://issues.apache.org/jira/browse/CASSANDRA-9064) -- the test assumed that the `min_threshold` and `max_threshold` would always be printed, but they aren't if they use the default values.
I also added a test for the other case, where the thresholds are set to non-default values, to make sure they are printed.
I also removed a few line continuations because I think they're gross.
The tests still all pass on `cassandra-2.{0,1,2}` and trunk, except for `cqlsh_tests/cqlsh_tests.py:TestCqlsh.test_describe_round_trip`, which still fails on 2.0 because the fix for 9064 wasn't applied there.

Fix failing tests 9064

---

stress_tool_test.py

This adds a couple smoke tests for the new feature added in [CASSANDRA-9522](https://issues.apache.org/jira/browse/CASSANDRA-9522).
I don't know if this is where we want tests of stress itself to live -- I'm happy to move them or to wait until other external tools' tests get merged.

add test for stress sparseness distribution

---

compaction_test.py
cqlsh_tests/cqlsh_tests.py
hintedhandoff_test.py

I also changed the warning message of 9643, which was modified during commit. 
hinted_handoff.py will fail due to an NPE in the logs but this is not related to 9035 at all. This NPE is happening for other dtests too.

Removed @require tags for some committed tickets

---

scrub_test.py

I had to change a previously written test to run it on trunk, since we now have a new sstable file, the statistics file, which seems to be required when scrubbing.

Fix to run the test for CASSANDRA-9591 on trunk as well

---

compaction_test.py
json_tools_test.py
offline_tools_test.py

This deals with problems related to `sstable2json`. #361 is followup for some of it. The justification for each commit is in its message.

Remove sstable2json tests

---

dtest.py
tools.py

This adds some new functionality surrounding the `@require` decorator. If you set the environment variable `IGNORE_REQUIRE` to `'yes'` or `'true'`, then `@require`d tests will run as though there were no decorator. It also modifies `@require`d tests with the `attr` decorator, so you can select them with `nosetests -a required`. 
Unfortunately, they'll still be skipped if you don't set `IGNORE_REQUIRE`; to have these play together nicely would require digging into the behavior of plugins, which is out of scope right now.
@aboudreault and/or @shawnkumar to review. Asking for extra-careful review of the docstring changes -- can you think of a better way to document this?

adds tools for running tests with @require

---

INSTALL.md
jmx_test.py
repair_test.py

This deals with a couple flaky tests on 2.2. See the commit messages for more details.
I'm not confident that the new `wait_on_binary_proto` will make the test stop flaking, as I noted in the commit message for that change -- I don't understand the interaction between `wait_for_binary_proto` and `wait_other_notice` well enough to say. However, adding `wait_for_binary_proto` can't hurt, and it might help. We'll figure it out as we keep an eye on flaky dtests in the coming weeks.

2.2 flakes

---

incremental_repair_test.py

One of the repair tests is flaky on 2.2 (see [this jira ticket](https://issues.apache.org/jira/browse/CASSANDRA-9752)). This decorates it as such.
Unfortunately, it also seems to fail hard on trunk. If we merge this PR, it will be run twice on trunk until it's fixed. Are we ok with that? This is marked with `@attr(long)`, so I take it it's a long-running test. I think @mshuler is the person to answer that question.

Flaky repair test

---

thrift_tests.py
tools.py

This changes the `require` decorator so you can skipping the `require`d test only after a particular version. So, imagine:
- A commit is merged to 2.2 and all greater versions, causing a test to fail or flap.
- File Jira ticket number 42 to request the bug be fixed.
- We want to run the test on versions before 2.2, but skip it on later versions 2.2.
The changes in this PR allow us to use `@require(42, broken_in='2.2')` to tag the test's failure as dependent on `CASSANDRA-42` and skips the test on all versions after 2.2.
This also changes the `since` decorator to use a more standard design. This allows a class to be `since`d multiple times, which is more likely to come up now because the new `require` feature uses `since` internally.
My testing of this basically consisted of playing with …

Require with version

---

secondary_indexes_test.py

This has been [failing consistently on cassci](http://cassci.datastax.com/view/trunk/job/trunk_dtest/lastCompletedBuild/testReport/secondary_indexes_test/TestSecondaryIndexesOnCollections/test_map_indexes/history/). This is because one of the asserts was expecting an old error message. This updates the error message for that assert and consolidates some logic with a similar assert nearby.

looks for correct error on map key search

---

paxos_tests.py

This skips a known failing test and cleans up `paxos_tests.py` along the way. Not a big review job. @aboudreault or @shawnkumar could you have a loog?

Skip paxos test

---

compaction_test.py
paging_test.py

This skips a few more tests on trunk that probably won't get fixed in the next day or two.

Skip known trunk failures

---

sstablesplit_test.py

This removes the hardcoded number of sstables expected by `sstablesplit_test`, addressing #384.

Fix sstablesplit test

---

cqlsh_tests/cqlsh_tests.py

Found this while reviewing for [CASSANDRA-9703](https://issues.apache.org/jira/browse/CASSANDRA-9703). Looks like this test should be passing everywhere now, for some reason.

fix cqlsh describe round trip test

---

metadata_tests.py
offline_tools_test.py

Pyflakes caught that these were missing.

Add missing import of require

---

cqlsh_tests/cqlsh_copy_tests.py
cqlsh_tests/cqlsh_tests.py

This PR is related to my work on 9304 here: https://issues.apache.org/jira/browse/CASSANDRA-9304
The changes make the tests not care about the order of the rows in the COPY TO command.

Make cqlsh tests not care about order

---

offline_tools_test.py

`require` doesn't live in `dtest`. This makes `offline_tools_test` import it correctly.

import require correctly

---

deletion_test.py
jmx_test.py
jmxmetrics_test.py

This is a patch for [CASSANDRA-9448] (https://issues.apache.org/jira/browse/CASSANDRA-9448) to support renaming of metrics in 3.0. I also modified the tests for CASSANDRA-7436, P.R. no 335.
It should be merged only when CASSANDRA-9448 is committed, else tests on trunk will fail.

Patch for CASSANDRA-9448

---

commitlog_test.py

os.chmod can't be trusted on Windows. Comments on the PR should be pretty explanatory.

Fix TestCommitLog.ignore_failure_policy_test on Windows

---

paxos_tests.py

This un-`@require`s the contention test in `paxos_tests.py` -- it passes locally, and it looks like the underlying bug is fixed (see the discussion [in CASSANDRA-9764](https://issues.apache.org/jira/browse/CASSANDRA-9764).
Unfortunately, the test has hung periodically on CassCI; I've filed #421 to track progress on fixing that. Until then, it's skipped.
This PR includes the usual isort cleanup as well.

Unskip paxos contention test

---

commitlog_test.py

Not ready to merge; requesting review.
This PR fixes `default_segment_size_test` and `small_segment_size_test` as described in [this Jira comment](https://issues.apache.org/jira/browse/CASSANDRA-9717?focusedCommentId=14622145&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14622145). It also has a tentative (not working yet :frowning:) change to the `_commitlog_test` method -- the goal is to allow the final segment of compressed commitlogs to be smaller than expected. Unfortunately, this does not seem to fix the test for the small, compressed commitlog -- smaller commitlogs are encountered before the final one.
@blambov Could you please review these tests, and help me figure out where I went wrong special-casing the test for the small, compressed commitlog? …

Fix commitlog tests

---

bootstrap_test.py

Some of the tests I added for CASSANDRA-9765 pass locally but fail on Jenkins. I'm guessing the timeout is too short so I reverted to the default timeout.

Fix for bootstrap tests on Jenkins

---

paging_test.py

This test has been passing for a while: http://cassci.datastax.com/job/trunk_dtest-skipped-with-require/22/testReport/paging_test/TestPagingWithDeletions/test_ttl_deletions/history/ so, gonna un-require it.
So, this test works by:
1. inserting data with a 3-second TTL in a loop
- checking that the data is there (new with this PR)
- waiting 5 seconds
- checking that no data is there
I'm concerned that, if there's a long delay between steps 1 and 2, or if the test is running on a slow machine, TTL'd data may have already expired before its presence is checked for. Is this a realistic concern, or is 3 seconds plenty of time?

Unrequire paging ttl test

---

configuration_test.py
dtest.py
jmxutils.py

* Fix is platform independent, should work on Linux but I didn't have the chance to test.
* Also fixed configuration_test.change_durable_writes_test
More information: https://issues.apache.org/jira/browse/CASSANDRA-9902

CASSANDRA-9902 Fix configurations dtest on windows

---

offline_tools_test.py

Refactored offline_tools_test.py:TestOfflineTools to create a cluster with only one node and write less keys: tests were taking too long with 3 machines, RF=3 and millions of rows. Essence of tests was maintained while making them faster.
Also, the test sstablelevelreset  was not properly testing this tool, so I fixed that.

fixed and optimized sstableofflinerevel and sstablelevelreset dtests

---

internode_ssl_test.py

CASSANDRA-9884 still needs fix NPE when internode compresssion is off.
Patch to add this scenario.

Add test for internode_compression: 'none'

---

upgrade_through_versions_test.py

This is still kinda a WIP while I see how it behaves on jenkins, but would love feedback in the meantime.
The basic gist of things here is to write/read and increment/read at quorum during the (rolling) upgrade process to make sure clusters can keep serving quorum during an upgrade.

Upgrade improvements

---

bootstrap_test.py

decommissioned_wiped_node_can_join_test : replace SIGTERM with SIGKILL after decommision to make sure process does not linger

Trying to fix decommissioned_wiped_node_can_join_test on Jenkins

---

bootstrap_test.py
concurrent_schema_changes_test.py
replace_address_test.py

I noticed that the test I've added for CASSANDRA-9871 is not running on Jenkins whilst it did run on my box. The reason is that the version of ccm I had installed was not up-to-date. After updating it I got the same failure and fixed it along with a few more tests in replace_address and one test in concurrent_schema_changes that were failing with the same reason. I also sped up a couple of tests in replace_address, no need to wait for 5 minutes for a binary notification that will never be there.
Finally, I attempted one more time to fix decommissioned_wiped_node_can_join_test() although this is just a guess as this test was fine on my box even after updating ccm.

Fix for replace_address and concurrent_schema_changes failing tests.

---

replace_address_test.py

A follow up to yesterday's pull request, #449, we need to allow a few seconds for the node to stop running.

Another fix for replace_address

---

incremental_repair_test.py

Skips this test entirely, since ci w/other attr (excluding long test for instance) doesn't appear to be working atm.

Add skipIf is_win for multiple_subsequent_repair_test

---

compression_test.py
schema_metadata_test.py

2 questions with this pull request:
- should it verify that the actual sstables on disk are compressed?
- I had a small usability nit -- the enabled key only comes back from the compression metadata call if it's disabled -- so a client that was checking status has an odd check -- should this be brought up on the jira ticket?

added compression disable/enable test - CASSANDRA-8384

---

json_tools_test.py

this test assumes the commit log will be recovered on next startup, which was not happening on windows because the node was being shutdown before the next sync period, so I basically changed it to use the batch-sync commit log, which fixed the test
(this test is also dependent on https://github.com/pcmanus/ccm/pull/351 to work on windows)

fix for CASSANDRA-10051

---

commitlog_test.py

During #CASSANDRA-10051 I needed to investigate a difference in behavior of commit log replay between Windows and Linux, and didn't find any dtest for commit log replay, which is a critical feature of cassandra.
This dtest basically inserts a single row, shuts down the node without flushing, and verify if the inserted row is present in next cluster startup due to commit log replay.

Added test_commitlog_replay_on_startup

---

incremental_repair_test.py
repair_test.py

These tests hung on a recent CassCI run (I believe [this one](http://cassci.datastax.com/view/trunk/job/trunk_dtest/lastCompletedBuild/testReport/)). Here are the relevant tests in the test nodes' stdout; note no more tests are run after these tests:
https://gist.github.com/mambocab/2ae8539003bee6b4eb7d#file-test_stdout-005-txt-L204
https://gist.github.com/mambocab/2ae8539003bee6b4eb7d#file-test_stdout-008-txt-L2
So, this PR skips them hard.
There's also a bit of import reorganization in this PR :+1:

Skip hanging tests

---

.travis.yml

Dunno why I didn't make a PR for this this a week or two ago when I did it, but:
We've been having some weird problems with Travis, where the diffing fails to find the right master branch. It's hard to tell when it's a problem, but this should fix it.
It also has the nice side effect of letting people run Travis on their forks and check this stuff via CI before making a PR. For example, here is a build of a branch on my fork that I deliberately inserted whitespace errors into:
https://travis-ci.org/mambocab/cassandra-dtest/builds/75453490

fetch riptano/master and diff against that

---

replace_address_test.py

This has been failing on CassCI because it used sleep without importing it. But when I ran it locally, it passed? Spooky. Anyway, this should fix it, and contains the obligatory isort changes.

Import sleep in replace_address_test

---

dtest.py

This helps with tests that fail due to Read/Write timeouts.  We could add an exponential backoff but this will probably help 90%

Add retry method for flaky/slow nodes

---

json_test.py

Fixes a test failure on Windows from a LF vs. CRLF difference

Ignore whitespace differences on pkey_requirement_test

---

cqlsh_tests/cqlsh_tests.py

This fix depends on the resolution of the following tickets:
https://issues.apache.org/jira/browse/CASSANDRA-10000
https://issues.apache.org/jira/browse/CASSANDRA-10004

changed cqlsh_tests.TestCqlsh.test_eat_glass to specify utf-8 encoding (CASSANDRA-9418)

---

bootstrap_test.py

Limiting cluster stream_throughput_outbound_megabits_per_sec on bootstrap_test.py:TestBootstrap.bootstrap_with_reset_bootstrap_state_test
fails (more details here: https://issues.apache.org/jira/browse/CASSANDRA-10097)

fix for CASSANDRA-10097

---

commitlog_test.py

Increased TestCommitLog.small_segment_size_test error tolerance from 20% to 25%

---

compaction_test.py

This test has been flapping on CI. From what I've seen, it's always below the threshhold and greater than 4, so this should reduce failure.
Example failures here:
http://cassci.datastax.com/view/trunk/job/trunk_dtest/323/testReport/junit/compaction_test/TestCompaction_with_DateTieredCompactionStrategy/compaction_throughput_test/
http://cassci.datastax.com/view/trunk/job/trunk_dtest/318/testReport/junit/compaction_test/TestCompaction_with_DateTieredCompactionStrategy/compaction_throughput_test/
http://cassci.datastax.com/view/trunk/job/trunk_dtest/314/testReport/junit/compaction_test/TestCompaction_with_DateTieredCompactionStrategy/compaction_throughput_test/
http://cassci.datastax.com/view/trunk/job/trunk_dtest/lastCompletedBuild/testReport/junit/compaction_test/TestCompaction_with_DateTie …

fixes up assertions for compaction tests

---

sstablesplit_test.py

I cannot reproduce locally the error described on [CASSANDRA-10108](https://issues.apache.org/jira/browse/CASSANDRA-10108). The error is only happening on [windows cassci](http://cassci.datastax.com/view/win32/job/cassandra-3.0_dtest_win32/21/testReport/sstablesplit_test/TestSSTableSplit/split_test/).
In order to have more elements to find out what's happening, this PR modifies `sstablesplit_test.py` to debug_print stdout, stderr, and rc of the sstablesplit tool. This shouldn't affect passing tests, will only print when the test fails.
This PR depends on this [ccm PR](https://github.com/pcmanus/ccm/pull/363).

printing debug output on sstablesplit failure (sstablesplit_test.py)

---

upgrade_internal_auth_test.py

'Unable to delete' from SSTableDeletingTask is expected on Windows on older versions during upgrades.

Exclude 'Unable to delete' on 22 upgrades on Windows

---

commitlog_test.py

The `commitlog_test.py:TestCommitLog.stop_failure_policy_test` was failing on Windows due to java.lang.OutOfMemoryError: Java heap space (https://issues.apache.org/jira/browse/CASSANDRA-10100)
I noticed that `prepare()` method (used by all tests) was setting the configuration `memtable_heap_space_in_mb` to 512MB. This property by default is 1/4 of the heap size, and the heap of ccm nodes is only 500MB. Do you remember why is it necessary to set this property for these tests?
Not setting this property made the failure policy tests (including `stop_failure_policy_test`) pass on Windows, probably due to reduced heap/gc pressure. However, the commit log segment size tests (`_commitlog_test` variants) were affected by the removal of this property, so I assume this property is only necessary …

Setting memtable_heap_space_in_mb only on commit log segment size tests

---

sstablesplit_test.py

[ccm PR363](https://github.com/pcmanus/ccm/pull/363) caused a [regression](http://cassci.datastax.com/view/cassandra-3.0/job/cassandra-3.0_dtest/lastCompletedBuild/testReport/sstablesplit_test/TestSSTableSplit/single_file_split_test/history/) on dtest `single_file_split_test`.
The simple fix is to rely on the new output of `run_sstablesplit`, which already exposes the stdout and stderr instead of trying to redirect the output to a temp file.

Updated single_file_split_test to iterate over run_sstablesplit output instead of redirecting output to file

---

cqlsh_tests/cqlsh_tests.py

This changes the order of the values in the `compaction` configuration dictionary. Locally, this fixes this error:
http://cassci.datastax.com/view/trunk/job/trunk_dtest/516/testReport/cqlsh_tests/TestCqlsh/test_describe/

compaction conf dictionary vals for cqlsh describe

---

upgrade_through_versions_test.py

This is the simplest way to test specific protocol versions, but does
require parting upgrade testing into several jobs to get full upgrade
coverage from 1.2 up through 3.1 and beyond.
The alternative to this method would require a lot more complexity to
maintain connections at the proper protocol version (particularly with
the concurrent testing now taking place with reads/writes).

changes upgrade tests to focus in a particular protocol version

---

assertions.py
batch_test.py
materialized_views_test.py

Validation tests for gc_grace_seconds on logged batches and materialized views.
Test depends on validation/approval on https://issues.apache.org/jira/browse/CASSANDRA-9917

Tests for CASSANDRA-9917

---

compaction_test.py
scrub_test.py
sstablesplit_test.py

This does some whitespace cleanup, but more importantly, removes `@require`s from tests that pass now.

Unrequire passing tests

---

commitlog_test.py

small timeout was making test fail on [win32 cassci](http://cassci.datastax.com/view/cassandra-3.0/job/cassandra-3.0_dtest_win32/lastCompletedBuild/testReport/commitlog_test/TestCommitLog/test_commitlog_replay_on_startup/history/)

removed watch_log_for timeout on test_commitlog_replay_on_startup

---

schema_metadata_test.py

It seems [support to multiple secondary indexes per column](https://datastax-oss.atlassian.net/browse/PYTHON-372) on the most recent python driver release [broke schema_metadata_test](http://cassci.datastax.com/view/cassandra-3.0/job/cassandra-3.0_dtest/lastCompletedBuild/testReport/schema_metadata_test/history/). This PR fixes the existing dtests to assume there might be more than one index per column.

Fix schema_metadata_test regression for secondary indexes

---

.travis.yml
linter_check.sh

The linter should only check lines that have changed on the branch being linted. The previous script checked against HEAD of master, which meant that Travis would catch linter errors in PRs when unrelated changes had been merged into master since they were branched off.
Asking for review from @ptnapoleon, since he stepped through git stuff with me, and from @aboudreault, since he is the keeper of the linter script.

lint against most recent common ancestor

---

upgrade_internal_auth_test.py

Instead of using the error whitelist approach, the idea is to mark the log for errors just before upgrading to 2.2 on Windows, effectivelly ignoring all errors happening on 2.1 (since we're not interested in those errors for the purpose of this test).
This test depends on this [ccm PR](https://github.com/pcmanus/ccm/pull/370) and approval on [this ticket](https://issues.apache.org/jira/browse/CASSANDRA-10037) before being merged.

Ignoring errors before upgrade to 1.2 on Windows (CASSANDRA-10037)

---

materialized_views_test.py

It seems there was a regression in the [latest CI run](http://cassci.datastax.com/view/cassandra-3.0/job/cassandra-3.0_dtest/lastCompletedBuild/testReport/materialized_views_test/TestMaterializedViews/really_complex_repair_test/), although the test passes locally.
I think the `gc_grace_seconds` of 1 second is too low, and might cause batchs to expire before reaching the destination node. This PR increases the `gc_grace_seconds` to 5 seconds.

Increased gc_grace_seconds of base table to 5s in materialized_views_test

---

cqlsh_tests/cqlsh_tests.py

Two new commands are added to clqsh by CASSANDRA-10086: CLS and CLEAR and here are the tests for them.

Tests for CASSANDRA-10086

---

tools.py

When `git`, called through `@require` printed whitespace to stderr, the decorator would fail. Because of the way it was called when loading through nose (and because of poor error reporting design on my part), the failure was silent.
I'm not sure I understand what I was going for when I originally wrote this branch-handling code, but my thoughts on it now are in my commit messages; don't let this pass review if you don't agree with them.

Improve git in require

---

CONTRIBUTING.md
upgrade_tests/cql_tests.py
upgrade_tests/paging_test.py
upgrade_tests/upgrade_base.py

This adds in the long-suffering upgrade tests from #471. They do still need to be refactored, but they will be useful to the devs running on trunk.
This also makes the subfolders in the dtests into modules. This will fix the recent problem where some modules of tests didn't run at all because of hidden errors during test module loading. [Here is the list of tests that weren't running](https://gist.github.com/mambocab/5c75a4c7d36b7666bea3); they ran successfully in this CassCI job:
http://cassci.datastax.com/job/scratch_mambocab-dtest_trunk/lastCompletedBuild/testReport/

Backwards compat modules

---

upgrade_tests/cql_tests.py
upgrade_tests/paging_test.py

Pursuant to some discussion on IRC, these tests need to be run over a few upgrade paths (see [CASSANDRA-10269](https://issues.apache.org/jira/browse/CASSANDRA-10269). Until then, they are hard-coded to upgrade from 2.1, so let's only run them on 2.2 and greater for now.

only run upgrade tests on 2.2 and later

---

assertions.py
cql_tests.py

I've added a test for materialized views and I've updated the existing tests for CASSANDRA-7392 since they were no longer passing (increased timeout, added failure exceptions, removed retry policy and changed log file format slightly).

CASSANDRA-7392: added MV test and adapted existing tests

---

cqlsh_tests/cqlsh_tests.py

As discussed on PR #529, this fixes the cqlsh tests for CLEAR and CLS on Linux by setting the TERM environment variable.

adds TERM env variable to cqlsh clear tests

---

upgrade_tests/cql_tests.py
upgrade_tests/paging_test.py
upgrade_tests/upgrade_base.py

This makes the upgrade tests run different paths depending on the version you're running the tests on. In particular,
| C* Version | upgrade path |
| :--- | :--- |
| 2.1 | 2.1->3.0 | 
| 2.2 | 2.2->3.0 | 
| 3.0 | 3.0->trunk | 
| trunk | 2.2->trunk |
as discussed [in CASSANDRA-10269](https://issues.apache.org/jira/browse/CASSANDRA-10269).
This also adds an environment variable that lets users configure what version to upgrade to.

Specify upgrade paths

---

nodetool_test.py
upgrade_tests/cql_tests.py

These two tests have started succeeding:
http://cassci.datastax.com/job/trunk_dtest-skipped-with-require/61/testReport/upgrade_tests.cql_tests/TestCQL/only_pk_test/
http://cassci.datastax.com/job/trunk_dtest-skipped-with-require/61/testReport/nodetool_test/TestNodetool/test_decommission_after_drain_is_invalid/
So I've un-required them. CASSANDRA-8741 has been closed, so that test definitely is ready to be unskipped, and CASSANDRA-6717 is in progress, so it makes sense to me that the other test would start succeeding now.

Remove requires

---

incremental_repair_test.py

This is for [CASSANDRA-10345](https://issues.apache.org/jira/browse/CASSANDRA-10345).
In cassandra-3.0, hinted handoff can generate SSTable during incremental repair that is not be marked as repaired.
We need to disable hinted handoff for reliable test.

Disable hinted handoff to prevent unintended SSTable

---

replication_test.py

I've expanded the test for CASSANDRA-10238 as follows:
- cover 3 all snitches capable of updating their configuration file
- multi-dc setup
- test adding new racks
See CASSANDRA-10238 for further details.

Additional test coverage for CASSANDRA-10238

---

upgrade_tests/cql_tests.py
upgrade_tests/upgrade_base.py

This rewrites the logic for determining the upgrade path in the storage engine upgrade tests. Rather than working off the branch name, it works off the version of the It works locally for me, both for running as-is, and for specifying paths with `UPGRADE_TO`. Demonstration of the latter is here:
http://cassci.datastax.com/job/scratch_mambocab-storage_engine_upgrades-2.1/17
This should deal with problems like [the problem tjake had](https://issues.apache.org/jira/browse/CASSANDRA-10261?focusedCommentId=14740734&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14740734) where the test ran the upgrade from cassandra-3.0 to the pre-3.0 dev branch, which isn't a supported path.

improve and consolidate upgrade path decision logic

---

upgrade_tests/paging_test.py

This fixes one of the failing tests in CASSANDRA-10267. The log pattern we grep for has changed in 3.0, and the read_request_timeout was reduced to prevent sporadic OperationTimedOut exceptions, instead of ReadTimeout

fixing test_failure_threshold_deletions

---

replication_test.py

These dtests pass on CassCI, and CASSANDRA-10238 has been resolved. @stef1927 Are these tests ready to be un-skipped?

removes require from skipped 10238 tests

---

concurrent_schema_changes_test.py

While `concurrent_schema_changes_test` seems a little flaky in general, this particular test is failing consistently since the schema table was modified in CASSANDRA-9921.

Fix details of mv schema table

---

upgrade_tests/cql_tests.py
upgrade_tests/paging_test.py

I've removed `test_multiple_row_deletions`, which we shouldn't be testing an upgrade for, and added a sleep to `rename_test`, giving time for the schema to propagate.

misc fixes for CASSANDRA-10267

---

schema_metadata_test.py

the package of the collections recently changed and broke this check -- it really only needs to verify the class name is the same

changed collection datatype check to only use the class name and not the

---

paging_test.py
upgrade_tests/paging_test.py

CASSANDRA-9775 has been resolved. Since `test_with_equal_results_to_page_size` was hanging the build, I've removed the hard skip, but not the `@require`, so it will run on [the branch for `@require`d tests](http://cassci.datastax.com/job/trunk_dtest-skipped-with-require/). If it's stable there for a few days, I'll make another PR to remove the `@require` there too.

remove @require from CASSANDRA-9775 tests

---

replication_test.py

This will fix the line separator so that it works on Windows as well.

Fix SnitchConfigurationUpdateTest on Windows

---

incremental_repair_test.py

@emolsson can you review? This is a rebasing of #544 to remove a few changes made with `autopep8`. Sorry, we weren't very clear about how to configure `autopep8` for this. It should be the same as your work, but with the `autopep8` commit replaced by https://github.com/riptano/cassandra-dtest/commit/e1bd34d7ddbda31de146dc0dd3cf0f8eb68ceb6a.

Emolsson un autopep8

---

paging_test.py

Follow-up to #566 -- this has been run on cassci for a while and it doesn't look like it fails or hangs:
http://cassci.datastax.com/job/trunk_dtest-skipped-with-require/82/testReport/paging_test/TestPagingSize/test_with_equal_results_to_page_size/history/
This test should be ready to run with normal jobs now.

unrequire passing, non-hanging paging test

---

cqlsh_tests/cqlsh_copy_tests.py

self.data only exists after calling all_datatypes_prepare, so when looking it up on self, check for it before doing so.
This should deal with the recent failures in the copy tests on CassCI:
http://cassci.datastax.com/view/trunk/job/cassandra-3.0_dtest/lastCompletedBuild/testReport/cqlsh_tests.cqlsh_copy_tests/CqlshCopyTest/test_null_as_null_indicator/
http://cassci.datastax.com/view/trunk/job/cassandra-3.0_dtest/lastCompletedBuild/testReport/cqlsh_tests.cqlsh_copy_tests/CqlshCopyTest/test_undefined_as_null_indicator/
I wasn't able to reproduce the original failures locally, but this change should be safe. @nutbunnies You touched this last, right? Could you review?

short circuit self.data access

---

materialized_views_test.py

This fixes [CASSANDRA-10460](https://issues.apache.org/jira/browse/CASSANDRA-10460).
The failures were due to the fixed bug in the dtest.

Use correct delete statement to delete whole partition in MV dtest

---

bootstrap_test.py

This should fix `decommissioned_wiped_node_can_join_test` on Jenkins but it should only be merged after CASSANDRA-10205 is committed since otherwise the test will hang on `node2.stop`

Fix for CASSANDRA-10205

---

jmxmetrics_test.py

ccm lib will already add the port, so we don't need to specify it here.

Fix jmxmetrics_test usage of jmx port

---

upgrade_tests/cql_tests.py

This also `isort`s `cql_tests.py`.
Basically, in order to run these tests reasonably on normal branches, we need to skip all these upgrade tests on certain versions because of, e.g. Java compatibility. Then, in order to run them manually on paths that involve those versions (so, the user specifies the correct Java version and wants to override the automatic skip), we set `SKIP=false` to disable those skips. However, we _actually_ want to skip this test, because it uses protocol version 2. So, in the test itself, we check the version of the node we're querying and manually raise `nose`'s exception that skips a test.

manually skip upgrade test with protocol v2

---

tools.py
upgrade_tests/upgrade_base.py

This fixes the logic that determines the default upgrade path for the tests in `./upgrade_tests/`. Previously, choosing the sensible default required that the `UPGRADE_TO` env variable be set, which is the opposite of what we want.
It also adds a parameter to the function that detects the Cassandra git branch so that you can pass in an argument. This parameter has a default value, and the function behaves identically with no argument specified, so it shouldn't affect other callers.

Fix default upgrade logic

---

upgrade_tests/cql_tests.py

This doesn't compare the node version, so it always executes the code meant for 2.2 nodes. I believe this causes a failure here:
http://cassci.datastax.com/view/Upgrades/job/storage_engine_upgrade_dtest-21_HEAD-22_tarball/20/testReport/upgrade_tests.cql_tests/TestCQL/limit_multiget_test/
On the 2.1 -> 2.2 upgrade path. @nutbunnies, can you please review?

do node version check in limit_multiget_test

---

offline_tools_test.py
sstableutil_test.py

In the second installment of CASSANDRA-7066, `sstablelister` was renamed to `sstableutil` and the location of the txn log files was changed. However the dtests were never 'unrequired' and so we forgot to merge the fix for them. This patch addresses these changes, and this includes the fix for sstableverify_test (CASSANDRA-10461). It also 'unrequires' the tests.

Changes for second part of CASSANDRA-7066

---

upgrade_tests/upgrade_base.py

This bug spawned this monster of a run:
http://cassci.datastax.com/view/Upgrades/job/storage_engine_upgrade_dtest-30_tarball-trunk_HEAD/53/testReport/
Phew. My bad. This should fix it.

fix git branch logic in upgrade tests

---

largecolumn_test.py

[CASSANDRA-8670](https://issues.apache.org/jira/browse/CASSANDRA-8670) was added on 2.2, but for some reason it has a @since(3.0) annotation,

Fix for CASSANDRA-10459

---

tools.py

Previously this code assumed that `git` would be available in the environment running `nosetests`. This is not always true; this was brought to my attention by a user in a desktop Windows environment who uses a `git` shell for some work but `cmd.exe` for `nosetests`. This PR changes the function that shells out to `git` so it returns `None` if you can't shell out.

Catch windowserror git

---

topology_test.py

This PR includes tests added to topology_test that check for a null status entry on nodes that crash during the decommission of the other node. This test is necessary to reproduce [CASSANDRA-10231](https://issues.apache.org/jira/browse/CASSANDRA-10231), which is not covered by any preexisting tests.
Since topology_test was flagged as @no_vnodes at a class level, I moved this down to the scope of the preexisting methods and added the test as a new method that is not decorated.
The commit shows up as Stefania since she did the hard work of first writing this test; that said, I've rebased with nits and fixes, so I'll be responsible for any feedback.
I've run through autopep8 for low-hanging fruit.
Thanks!

Test to reproduce CASSANDRA-10231 that crashes nodes during decommission

---

bootstrap_test.py

Potential fix to [CASSANDRA-10167](https://issues.apache.org/jira/browse/CASSANDRA-10167).
I couldn't reproduce flapping in my laptop, but potential hang may be caused by streaming waiting to be timed out for 1 hour (default value).
This patch sets `streaming_socket_timeuout_in_ms` so that test won't hang and time out.
Can you try running this in CI env to see this will fix the problem?

add streaming_timeout_in_ms to resumable_bootstrap_test

---

offline_tools_test.py
sstableutil_test.py

As discussed on CASSANDRA-10461, to better debug disk space issues such as [this] (http://cassci.datastax.com/job/cassandra-3.0_dtest/248/testReport/offline_tools_test/TestOfflineTools/sstablelevelreset_test/), I've changed `sstablelevelreset_test` to first look at the exit code and `stderr`, and only afterwards validate `stdout`.
I've also improved splitting of `stdout` into lines for `SSTableUtilTest` since it passes locally but fails on Jenkins due to an extra line; so my best guess is a line ending problem.

Fixes for CASSANDRA-10461

---

consistency_test.py

Figured I'd clean stuff up while I'm poking around in here. I'm not sure that `short_read_test` and `short_read_reversed_test` are primarily related to CASSANDRA-9460, but it is noted in the test itself.

tag related jira tickets in consistency_test.py

---

bootstrap_test.py

I wrote this test forever ago, but didn't merge it because of https://issues.apache.org/jira/browse/CASSANDRA-9484 Well now it isn't failing anymore on 2.2 or 3.0, so we should merge this in.
@mambocab to review.

Test for Cassandra 7069

---

upgrade_tests/upgrade_base.py

As discussed on #cassandra-dev. @ptnapoleon look good?

use 2.2.2 by default for upgrades

---

sstableutil_test.py

This fixes sstableutil_test.py so that it works regardless of extra output lines such as `WARN  14:58:01 Only 37512 MB free across all data volumes. Consider adding more capacity to your cluster or removing obsolete snapshots`, see CASSANDRA-10461 for more details.

Ignore output lines that are not table file names in sstableutil_test

---

upgrade_tests/upgrade_base.py

This does 2 things:
- bumps up 2.2.latest for the upgrade test defaults
- adds some (really quite gross) logic for falling back to downloading from git rather than the archive.

Use 2.2.3 upgrades

---

upgrade_tests/cql_tests.py
upgrade_tests/paging_test.py
upgrade_tests/upgrade_base.py

This makes each upgrade test run twice, each with a different topology. It does this basically by treating the test methods as methods from mixins and adding a bunch of extra classes that are actually run as the tests.
Requesting review from @thobbs and from @ptnapoleon. @ptnapoleon, sorry to ask this of you, but could you double-check that I've made 2 subclasses of each test class in `upgrade_test`? I don't think I missed any, but I want to make sure none of them fell through the cracks. (There may also be a better solution here, open to suggestions.)

run upgrade suite 2x with different cluster topos

---

sstableutil_test.py
tools.py

Compaction logging was moved to debug level and so this test was broken.

10461: fixed sstableutil compaction log watching

---

upgrade_tests/cql_tests.py
upgrade_tests/upgrade_base.py

By @pcmanus' request, this allows users to upgrade to a local directory by specifying a `UPGRADE_TO_DIR` environment variable. Yes, the logic is hacky and lives all over the file, but there's a refactor for these tests in the queue anyway, so I don't feel too bad about it.

use UPGRADE_TO_DIR env var for upgrade tests

---

bootstrap_test.py

This is for [CASSANDRA-10578](https://issues.apache.org/jira/browse/CASSANDRA-10578).
Added sleep before checking cassandra process is not running.
Hope this helps running test reliably.

Wait before checking the node is running

---

dtest.py

@ptnapoleon can you review? We disucssed this privately.
This change prints the log errors split by newlines rather than spaces. Doesn't actually make a huge difference unless you want to do some post-processing. Before (results truncated):
```
AssertionError: Unexpected error in node1 node log: ['ERROR [main] 2015-10-29 10:53:49,321 LogTransaction.java:436 - Failed to remove unfinished transaction leftovers for txn [/tmp/dtest-_iDCHG/test/node1/data/system/local-7ad54392bcdd35a684174e047860b377/ma_txn_compaction_dac891a0-7e4c-11e5-9df1-6d10b7106813.log]  java.lang.NullPointerException: null \tat org.apache.cassandra.db.lifecycle.LogRecord.getExistingFiles(LogRecord.java:243) ~[main/:na] \tat org.apache.cassandra.db.lifecycle.LogRecord.getExistingFiles(LogRecord.java:237) ~[main/:na] \tat …
```

Print error with new lines

---

upgrade_tests/paging_test.py

This adds some plumbing to allow passing non-default timeout values to `request_one` and `request_all` in the paging upgrade tests, then uses that plumbing in `test_multiple_partition_deletions`, `test_single_partition_deletions`, and `test_query_isolation`. This will hopefully fix some tests that flap on CassCI:
https://issues.apache.org/jira/browse/CASSANDRA-10476?focusedCommentId=14980505&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14980505
@blerer is this what you had in mind?

Timeout paging upgrade tests

---

upgrade_internal_auth_test.py

* Remove requires annotation
* Bump connection timeout when checking permissions. During the upgrade
to 2.2 test, this can timeout with the default value.

Minor fixes for CASSANDRA-8653

---

cqlsh_tests/cqlsh_tests.py

Depends on https://issues.apache.org/jira/browse/CASSANDRA-10513

Update cqlsh_test index ordering after 2.2 driver update

---

thrift_hsha_test.py

When running this in a tight loop locally, I can reproduce it very infrequently; if I add the pause here, I haven't seen this ever happen (been running for a few hours).

thrift_hsha: Allow a few seconds to go by while testing for closed sockets

---

materialized_views_test.py

This adds/fixes tests for [CASSANDRA-10621](https://issues.apache.org/jira/browse/CASSANDRA-10621) and [CASSANDRA-10634](https://issues.apache.org/jira/browse/CASSANDRA-10634).
A few changes are made:
* in the tests for bootstrapping nodes and adding datacenters, we modify the test so that the values for the partition key are different between the base table and the view table. This prevents nodes from always being paired to themselves in view replica calculation
* we add a test for Cassandra write survey mode
* we make sure to test adding datacenters under NetworkTopologyStrategy and SimpleStrategy

Improve/add MV tests around bootstrapping/adding datacenters

---

offline_tools_test.py

This PR fixes CASSANDRA-10645.
It addresses a number of issues:
* move to cross-platform line-splitting
* fix filesystem casing issues in output across Python/Java
* more reliably corrupt sstable file so that the sstable isn't sometimes empty
* reduce number of stress writes to reduce test duration
The test now reliably passes on Windows 2.2/3.0 and Linux 2.2/3.0.

CASSANDRA-10645: Rework sstableverify tests to work cross-platform 

---

upgrade_tests/paging_test.py

As per a comment from Sylvain on CASSANDRA-10476:
> We do expect 2.2.3 -> 3.0 upgrade to succeed. We don't expect
> static_columns_paging_test to pass however since that test don't even
> pass for non-upgrade test on 2.2.3, it's a bug of 2.2.3 that has been
> fixed in 2.2.4 (CASSANDRA-10381). If we can make so that the test
> doesn't run on 2.2.3 (but does run once we'll update to 2.2.4), that
> would be perfect.
@pcmanus is this what you had in mind? This will skip the entire test if any node is version 2.2.3 or lower. Another option is to still run the test, but only query nodes running higher versions. I'm not sure what configurations we expect errors in.

Skip static columns paging test 10476

---

native_transport_ssl_test.py

Depends on #580, @ptnapoleon to review.
Since this is a straight-up refactor (so, not urgent, style discussions are appropriate and worth blocking merge), I thought it might be a good place to start the `self.assertThing` vs `nose.tools.assert_thing` discussion. Philip and I had talked about how it would be nice to use the `nose.tools` after Andrew ran into problems writing custom assert functions that weren't methods. Example in action [on this line](https://github.com/riptano/cassandra-dtest/compare/master...mambocab:clean-up-ssl-tests?expand=1#diff-256d3a62cfb3c3d440953958032f15f1R35). 
I propose we start using them for new code and changed tests, and mark it as such in CONTRIBUTING. I like them better because they allow us to more easily write custom asserts. They also take up less …

Clean up ssl tests, possibly begin using `nose.tools` assertions

---

sstableutil_test.py

The `sstableutil` tests fail on Windows because they compared the output from `sstableutil` and `glob.glob`, which were outputting filenames in different (but still correct, because of Windows tooling's case-insensitivity) casings. In my OpenStack Windows test environment, I'd also get different strings for filenames for the same files because filenames would get abbreviated to their short forms with `~1` when returned by (IIRC) `glob.glob`.
Once we port to Py3, we should be able to can switch to using `os.path.samefile`. For the moment, we'll have to work around it. The solution here is to trim the common prefix from each filename when we get them back from a given tool. The remainder will uniquely identify the file and allow us to make sure the same files are reported by `sstableutil` …

workaround for CASSANDRA-10632

---

concurrent_schema_changes_test.py

See https://issues.apache.org/jira/browse/CASSANDRA-10665. @nutbunnies, are any of these supposed to pass reliably, or should we `require` away the whole suite until we have our improved view onto failing tests?

Skip concurrent schema changes

---

jmx_test.py

2 commits here:
- one that does `s/"/'/` for Python nerd purposes, and
- one that cleans up the exception-handling logic in `jmx_test.py`.
The main reason for this PR is because I have a question about the existing logic here:
https://github.com/riptano/cassandra-dtest/compare/master...mambocab:jmx_test-exception-handling?expand=1#diff-a5036552850755a7ef3b1b262c2f2727L77
This catches the exception, checks to see if its message meets some criteron, then happily continues running the test. In the other call to `nodetool netstats`, it fails the test regardless of whether the exception meets our criterion or not:
https://github.com/riptano/cassandra-dtest/compare/master...mambocab:jmx_test-exception-handling?expand=1#diff-a5036552850755a7ef3b1b262c2f2727L88
Is both of these correct? The first …

jmx_test exception handling

---

cqlsh_tests/cqlsh_tools.py

I believe `ValueError`s and `TypeError`s are the only ones thrown when the functions called here are provided incorrect arguments. I ran the cqlsh_copy_tests and nothing blew up, which is promising. (In any event, we need to not use a bare `except:` here, so if this is an incomplete list of exceptions to check for, it'll still be a starting point for doing this correctly.)

don't use bare except trying to strip timeszones

---

sstableutil_test.py

On Linux, abortedcompaction_test is flapping when it fails to find any
temporary files. The comment indicates that we should try increasing the
number of records so that temporary files are still around by the time
we check for them. This commit does that.
This is part of CASSANDRA-10664, and will hopefully make this test stop flapping:
http://cassci.datastax.com/job/cassandra-3.0_dtest/355/testReport/junit/sstableutil_test/SSTableUtilTest/abortedcompaction_test/
I don't know if it's necessary to double the number of records; maybe bumping them 50% would be sufficient. I just picked a number, really. Before this change, this test can take between 2.5 and 3 minutes sometimes, FWIW.

increase # of records for abortedcompaction_test

---

dtest.py

We are getting so many timeouts when connecting, see for example [this job here](http://cassci.datastax.com/job/cassandra-3.1_dtest/lastCompletedBuild/testReport) .
I would like to see if increasing the connect_timeout helps.

Increase connect timeout

---

upgrade_through_versions_test.py

bump trunk version
remove 1.2 as a test starting point
add 2.2 back into the proto v1/v2 paths

upgrade tests version tweaks

---

sstableutil_test.py

Consider this a reopened version of #665.
I've applied @jkni's (excellent) changes and made some changes, mostly for Python 3 compatibility (`map` returns a list in py2, but a generator in py3, so we have to flatten it to a list. I pulled out a method to do just that.).
@jkni can you please review and smoke test on Windows when you get a chance? and @ptnapoleon can you review for readability? I think Joel's changes make this much more readable but I already know the test, so.

Fix  strip common prefix

---

upgrade_through_versions_test.py

When x.y.z has been tagged it should always win over x.y.z-foo

upgrade test special case comparing tag versions

---

dtest.py

As previously written, if one of the file deletions failed, the subsequent deletions wouldn't even be attempted.
I've also added a note about a change to make after the move to Python 3.

fixes ssl store file deletion

---

offline_tools_test.py

In [CASSANDRA-10582](https://issues.apache.org/jira/browse/CASSANDRA-10582), the exception thrown on corrupt sstables was unified with that of 3.0.
The test wasn't updated, so it was failing on 2.2 when it looked for the old exception output.
I've removed the 2.2 branch in an if condition; we no longer need to handle it separately.

Unify corrupt sstable output analysis in sstableverify test

---

cqlsh_tests/cqlsh_copy_tests.py

Tests with failure injection for CASSANDRA-9304 and a fix for a failing test on Jenkins due to wrong set ordering.

Tests with failure injection for CASSANDRA-9304 

---

schema_metadata_test.py

PYTHON-404 seems to have changed this, so tests need to adjust.
Good benefit is no more version checking.

adjust schema metadata checks

---

jmx_test.py

There is no need to load this much data to effectively test what we're testing. It just makes the test take too long. I'd like to drop it even farther if I could, to 50 or 100k. I also used the cleaner shorthand to notate the load on another test in the file.
@mambocab

Reduce stress load in netstats_test

---

cqlsh_tests/cqlsh_copy_tests.py

This should fix [test_copy_to_with_more_failures_than_max_attempts] (http://cassci.datastax.com/job/cassandra-2.2_dtest/403/testReport/cqlsh_tests.cqlsh_copy_tests/CqlshCopyTest/test_copy_to_with_more_failures_than_max_attempts) and [test_copy_to_with_child_process_crashing] (http://cassci.datastax.com/job/cassandra-2.2_dtest/lastCompletedBuild/testReport/cqlsh_tests.cqlsh_copy_tests/CqlshCopyTest/test_copy_to_with_child_process_crashing).

9304: increased failing token range to fix flaky cqlsh copy tests on Jenkins

---

replication_test.py

Reverts riptano/cassandra-dtest#678 Looks like the ticket isn't ready for commit, it might be causing test failures. So I'm pulling the test back out.

Revert "Tests for CASSANDRA-9474"

---

replication_test.py

This fixes the replication tests due to the changes for CASSANDRA-10243 and introduces new tests for it. One new test, `test_cannot_restart_with_different_rack` will still fail until CASSANDRA-9474 is also committed (which is imminent so I did not `@require` the test).

Fixes to replication_test.py for CASSANDRA-10243

---

replication_test.py

Added in stefania's PR #688, fixed the regex, and then made other fixes so that these tests work on OSX, where nodetool calls always print to stderr

Replication cleanup

---

bin/collect_known_failures.py
concurrent_schema_changes_test.py
tools.py
upgrade_tests/cql_tests.py

Supercedes #700.
> Adds simple decorator that tags a known failing test with some metadata about the failure. Also tags a couple tests for demo purposes. I smoke-tested this with
> 
> ```
> CASSANDRA_VERSION=git:cassandra-3.0 nosetests --collect-only -a known_failure -v
> CASSANDRA_VERSION=git:cassandra-3.0 nosetests --collect-only -a known_failure '!known_flaky' -v
> CASSANDRA_VERSION=git:cassandra-3.0 nosetests --collect-only -a known_failure=cassandra -v
> CASSANDRA_VERSION=git:cassandra-3.0 nosetests --collect-only -a known_failure=systemic -v
> Which demonstrates the basic functionality of the decorator.
> ```
> Printing out associated ticket URLs is a little more difficult and will involve writing a small nose plugin, I believe.
> 
> @ptnapoleon to review and give feedback. In …

Known failure decorator

---

tools.py

Small addition to the `known_failure` decorator. Just adds a freeform 'notes' attribute; it's not used in a meaningful way yet, but could be in the future, and might be better than comments for adding metadata like "this fails on 3.0+", which we can't handle at the moment.
@ptnapoleon to review.

add `notes` param to `known_failure`

---

upgrade_tests/cql_tests.py
upgrade_tests/paging_test.py

Part of the dtest failure audit. Adds metadata to the `upgrade_tests` module.

add failure metadata in upgrade tests

---

upgrade_tests/cql_tests.py

Missed this because it isn't run on the main dtest jobs. Fixes this error:
http://cassci.datastax.com/view/Upgrades/job/storage_engine_upgrade_dtest-21_HEAD-22_tarball/82/testReport/upgrade_tests.cql_tests/TestCQLNodes3RF3/test_v2_protocol_IN_with_tuples/

flatten cursor.execute to fix protocol test

---

commitlog_test.py
paging_test.py

On 2.1 we were getting OperationTimedout instead of ReadTimeout.
This was because we now have a default retry policy set.
On retry, we were ignoring the ReadTimeout error that was
correctly being sent by C*. By overring the retry policy,
we have stopped retrying, and now propagate the correct exception.
@knifewine to review.

Use FallthroughRetryPolicy on failure_threshold_deletions

---

bin/collect_known_failures.py
tools.py

adds free-text notes to json output from `bin/collect_known_failures.py`.
You can try this out locally with 
```sh
python ./bin/collect_known_failures.py -a failure_notes
python ./bin/collect_known_failures.py -a known_failure
```
@ptnapoleon to review.

add failure_notes to collect_known_failures output

---

jmxmetrics_test.py
offline_tools_test.py

I enhanced `jmxmetrics_test.TestJMXMetrics.begin_test` to cope with offheap memtables, else it will consistently fail after CASSANDRA-9472 is committed.
I believe the known failure described in CASSANDRA-10846 for `sstableofflinerelevel_test` is probably due to a lack of overlapping tables. I had it consistently failing on the 9472 branch with offheap memtable objects whilst without offheap memtable ojects it would pass consistently. After investigating I discovered it was passing only because of 1 overlapping table. Increasing the number of records from 100K to 200K fixed it in both scenarios.

Fixes for CASSANDRA-9472

---

materialized_views_test.py

I don't think that `options` is manipulated in a way that would cause
problems, but we're asking for trouble leaving it like this.
@ptnapoleon, can you review? It's teeny, I don't see any potential for issue here

changes default arg from dict to None

---

cqlsh_tests/cqlsh_copy_tests.py

We need a `@since` for `test_reading_with_ttl` because CASSANDRA-9494 is only on trunk, at least for the time being.

CASSANDRA-9494 was only committed on trunk

---

sstable_generation_loading_test.py

Added test to check sstableloader works with upper case keyspace name.
This is test for [CASSANDRA-10806](https://issues.apache.org/jira/browse/CASSANDRA-10806).

Add test for CASSANDRA-10806

---

cql_tests.py
upgrade_tests/cql_tests.py

A number of tests were incorrectly named -- they didn't begin with 'test_' or end with '_test', so they weren't picked up by nose and so weren't run by nosetests. I missed this in review. @ptnapoleon to review.

name tests so nose will pick them up

---

index_summary_upgrade_test.py

@knifewine to review, and also run locally, as it fails on OSX because it's using 2.1.3.

Also set the cluster install dir, so ccm can track version

---

bootstrap_test.py

This failure has been resolved in [CASSANDRA-10844](https://issues.apache.org/jira/browse/CASSANDRA-10844).
A clean run without this test failing can be seen on [CassCI](http://cassci.datastax.com/job/cassandra-2.1_dtest/391/testReport/bootstrap_test/TestBootstrap/failed_bootstrap_wiped_node_can_join_test/history/).

Remove known_failure decorator on failed_bootstrap_wiped_node_can_join_test

---

cqlsh_tests/cqlsh_copy_tests.py
cqlsh_tests/cqlsh_tests.py
dtest.py

These are the tests for the new COPY options introduced by CASSANDRA-9303. Because of the new parameters of `format_value()` in pylib `formatting.py`, once CASSANDRA-9303 is committed the existing tests will break. For the same reason we should not merge until 9303 is committed, I also omitted `@require`.
There is a bit of code to review so take your time, we can hold the commit of 9303 until this review is completed.

Tests for CASSANDRA-9303

---

materialized_views_test.py

Done as part of the test coverage for CASSANDRA-10981

Expand MV consistency tests to focus on a single partition

---

bootstrap_test.py

Verifies that a node which has been decommed and wiped can rejoin and,
by implication, that it can successfully establish gossip connections
with existing seeds.

Add test for CASSANDRA-8072

---

CONTRIBUTING.md

Adds a review checklist to `CONTRIBUTING.md`. Impetus: we would have missed some stuff on #738 if not for Carl's sharp eyes: https://github.com/riptano/cassandra-dtest/pull/738#issuecomment-170140677
Should be uncontroversial -- I've tried to just document our existing review process here. @ptnapoleon, and any other interested parties, to review.

Review checklist

---

materialized_views_test.py

After CASSANDRA-6696 and CASSANDRA-10421, flushing the schema keyspace is more likely to cause timeouts on waiting for the completion of the migration test callback.
This is particularly a problem in dtests because it hits a pathological case of 9 data directories on the same physical disk.
This PR adds a JVM argument when starting bootstrapping nodes to increase this wait time.

CASSANDRA-10978 - increase wait time for migration tasks in MV bootstrapping tests

---

user_types_test.py

We were running into EC issues with the Write, Read, Assert pattern. As sometimes we would read from a replica w/o the data yet
@knifewine to review, as he and I broke this in the first place.

Use stricter CL on test_type_secondary_indexing

---

dtest.py
upgrade_through_versions_test.py

This includes some other simplifications and problems I found along the way, notably config wasn't being set properly for some upgrade tests, and some schema metadata code was trying to create database stuff with invalid names (in the case of bare versions like 1.2.3).
Also included is a small refactor to Tester to support a hook on subclasses for setting configuration. This is probably less drastic than we might like but it should keep other tests behaving the same without any surprising changes to config (for better or worse).

Remove upgrade ver magic

---

upgrade_through_versions_test.py

looks like some tests on CI are struggling to meet the original timeout that worked fine locally.

increase timeouts

---

topology_test.py

By not watching the logs, we were trying to move too many nodes at once, which would throw an error. Unfortunately, watching the logs is not enough, as the state jump to normal happens just before the rest of the ring is ready for another move again.
@knifewine to review

Check for nodetool move to finish on topology_test

---

upgrade_tests/upgrade_base.py

Some of the tests do a truncate just after a do_upgrade(). As do_upgrade() restart a node but doesn't wait for the other(s) to have detected the restart of that new node, the truncate might actually fail saying some node are down as pointed in CASSANDRA-11016. The fix is trivial, we just wait for other nodes to notice the restart.

Wait on nodes detecting one another on upgrade (CASSANDRA-11016)

---

upgrade_tests/cql_tests.py

Since 3.0, multiple indexes per-column are supported, so attempting to create a values index on a map which already has a keys index should succeed.

Modify map keys index upgrade test for 3.0

---

commitlog_test.py

@jkni Can you give this a once-over, please? Addresses [CASSANDRA-10865](https://issues.apache.org/jira/browse/CASSANDRA-10865).

skip crc test on <=2.1.X

---

sstableutil_test.py

we can't watch the log for Compacted ... as it won't happen with this little data

sort the oplog list and dont wait for compactions

---

bootstrap_test.py
commitlog_test.py
compaction_test.py
scrub_test.py
secondary_indexes_test.py
snapshot_test.py
sstable_generation_loading_test.py
sstableutil_test.py

Quite ugly to do the 'for x in xrange(0, self.cluster.data_dir_count)' everywhere, this uses https://github.com/pcmanus/ccm/pull/441 to get the actual data directories instead (note that the ccm-PR needs to be merged first)

clean up the way we iterate over data directories

---

bootstrap_test.py

The decommission will have already caused the node DOWN
notifications to come up. So we won't see more on stop, so waiting
will cause us to timeout
@mambocab to review. Please make your preferred fixes and merge yourself, as I'll be on vacation, and don't want to let this set until I return.

Don't wait other notice after decommission

---

batch_test.py
metadata_tests.py

@knifewine can you review? These are passing now in the skipped-with-require CassCI job, and the relevant JIRAs were closed.
I also removed the re-import of `debug` in `batch_test.py`. The `debug` defined in `tools.py` is the one that's imported from `dtest`, so they actually point to the same function. Thus, this change won't change the behavior of `debug` in the module.

Unskip required

---

upgrade_supercolumns_test.py

Addresses CASSANDRA-10868 and removes dependency on an environment variable.
All 4 tests in this file now fail :/ Do we have a procedure for adding `known_failure` to things before merge? I don't know if I should really file the bug until I have some CassCI runs, but I also don't want the dtest triage person to have to deal with it, since I already know about the failure.

Use binary dist for upgrade supercolumns test

---

cqlsh_tests/blogposts.yaml
cqlsh_tests/cqlsh_copy_tests.py

This introduces a new test to simulate connection failures and test that COPY TO handles them correctly. It should also fix the occasional failures for test_bulk_round_trip_blogposts as described in CASSANDRA-10938.

Fixes for CASSANDRA-10938

---

cqlsh_tests/cqlsh_copy_tests.py
cqlsh_tests/cqlsh_tests.py
cqlsh_tests/cqlsh_tools.py
json_test.py

Some fixes to support microseconds in the timestamp and a new test for it (3.2+ only). Please wait for CASSANDRA-10428 to be committed before merging.

Support microseconds in the default timestamp format, CASSANDRA-10428

---

cqlsh_tests/cqlsh_copy_tests.py
cqlsh_tests/cqlsh_tests.py

When tests for CASSANDRA-10428 were written, trunk was still at 3.2 but now it is at 3.4 and therefore the version tags need updating. At the moment 3 cqlsh tests are failing on 3.3.

Fix version for CASSANDRA-10428

---

schema_metadata_test.py

fixes issues of db object names being too long or not compatible.
idea and most of implementation thanks to @mambocab!

consistent hash for naming db objects

---

materialized_views_test.py

We have seen flapping on this test in a couple places. Most recently here:
http://cassci.datastax.com/job/cassandra-3.3_dtest/70/testReport/materialized_views_test/TestMaterializedViews/add_write_survey_node_after_mv_test/
Bumping up the migration time a few more seconds will hopefully fix this flapping

Bump materialized view migration timeout up (again) to 5s

---

metadata_tests.py
tools.py

As discussed privately: `@require`ing this test is incorrect -- we want to skip it everywhere, all the time. Its hanging is hanging our `@require`d-test-auditing job, which we don't want.
Also a couple cleanup commits in there to deal with stuff that `flake8` found.

Unrequire metadata test

---

upgrade_through_versions_test.py

we need to pay closer attention to both head of branch testing, as well as testing of provisional releases as an upgrade's terminating version.
these changes introduce vars to track both the head of various branches, and also others to track 'latest' versions available. in specific release testing we'll be using tags assigned to these latest vars. to reduce unnecessary testing and noise, these are currently gated on whether or not the 'latest' appears to be a provisional unreleased version (currently simply if it has 'tentative' in the name we include it for testing).
this also adds some missing cases for testing 3.3 (along with the new conditional classes that correspond).

New upgrade classes

---

upgrade_tests/cql_tests.py
upgrade_tests/paging_test.py
upgrade_tests/upgrade_base.py

I feel like there's some cleanup to do in this history, and these commits will need to be rebased onto master after #787 is merged, but the code is in place.
The big change is the removal of `upgrade_tests.upgrade_base.get_default_upgrade_path` and the code that calls it. It's replaced by code that extends the upgrade-test-generation code introduced in #787 by attaching the specified upgrade path to the test class, rather than specifying it through a mess of environment variables and weird logic defining the default path.
This is currently running here:
http://cassci.datastax.com/view/Dev/view/mambocab/job/mambocab-consolidated-upgrades/20/
We can use this job to run all our upgrade tests on a single job if we like.

Remove upgrade_tests default upgrade logic

---

upgrade_tests/cql_tests.py
upgrade_tests/paging_test.py
upgrade_tests/upgrade_through_versions_test.py

This sets `__test__` based on the value of the `UPGRADE_TEST_RUN` env var -- so, rather than skip the test, it removes it from test discovery entirely. This works around problems we had on non-upgrade jobs after merging #798, where `nosetests` threw up when passed too many test names.
On my machine, this seems to work:
```sh
$ CASSANDRA_VERSION=git:trunk nosetests --collect-only 2>&1 -vv | grep upgrade_tests  
upgrade_tests/regression_test.py:TestForRegressions.test_10822 ... ok
$ UPGRADE_TEST_RUN=true CASSANDRA_VERSION=git:trunk nosetests --collect-only 2>&1 -vv | grep upgrade_tests | wc -l
2921
```
Can a reviewer please verify?

gate upgrade test discovery on env var

---

cqlsh_tests/cqlsh_copy_tests.py

Fixes mutable arguments to `_test_bulk_round_trip` in the `cqlsh` `COPY` test suite. #803 should be rebased onto this once it's merged.

fix mutable arguments to _test_bulk_round_trip

---

write_failures_test.py

Addresses the issues brought up in #498. @iamaleksey can you review to double-check the protocol version skips?
This also makes some formatting fixes and removes unused variables. @ptnapoleon can you review those?

Protocol skip fixes

---

upgrade_tests/upgrade_through_versions_test.py

Tags failures from [CASSANDRA-11162](https://issues.apache.org/jira/browse/CASSANDRA-11162).
Looks like we might not be able to do the `TestClass.test_method = known_failure(**known_failure_args)(TestClass.test_method)` thing. For one thing, because each instance of `test_method` is actually the same object, you might as well just decorate the test on the base class. Also, I got a kinda cryptic errorThe error I got when I tried to actually do this was kinda cryptic, though, so I could be wrong here. I didn't dig too far. @knifewine and @ptnapoleon, could you review, please, and try to think of a different solution?

tag known failures

---

sstableutil_test.py

PR #765 removed a line to wait for compactions after a node started. This line watched the log for compaction completion, which was problematic because compactions were not always triggered. This change looked good on CassCI.
Locally, dtests are always failing on 3.0 because this line was removed. Investigating, I found it was because a compaction did in fact start so files changed during the test. I've also seen the issue on [CassCI](http://cassci.datastax.com/view/Dev/view/jkni/job/jkni-10736-3.0-dtest/2/testReport/).
I asked Marcus about this and he suggested this change; in this case, if a compaction is triggered, we will wait for its completion, but if none are ongoing, we will proceed. I think this might open a very small race condition where we check before a compaction starts, but …

Add wait for compactions to finish after starting node

---

upgrade_tests/cql_tests.py
upgrade_tests/upgrade_through_versions_test.py

This does some tagging work for failing upgrade tests.

Tag failing upgrade tests

---

dtest.py

adds support for continuous watching of cassandra logs, to enable closer association between dtest actions and resulting log failures (esp among upgrade tests).
when enabled, this will trigger ccm to open a continuous log watching thread, which will call back when errors are encountered, and dtest can then take actions to halt and cleanup test execution.
currently gated by an env var, but that will change soon, in line with command line flags

Logwatch callback

---

cql_tests.py

I think CASSANDRA-11108 is good to be closed -- see [this comment on JIRA](https://issues.apache.org/jira/browse/CASSANDRA-11108?focusedCommentId=15159075&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15159075). If that gets closed, we can merge this; if not, we can close without merge.

untag failing test from CASSANDRA-11108

---

cql_tracing_test.py

Fixes the mistake that causes the failure here:
http://cassci.datastax.com/view/trunk/job/trunk_dtest/1026/testReport/junit/cql_tracing_test/TestCqlTracing/tracing_default_impl_test/history/
@ptnapoleon or @knifewine can you review? The test in question is `cql_tracing_test.py:TestCqlTracing.tracing_default_impl_test`.

add space to tracing error check

---

cql_tests.py
tools.py
utils/metadata_wrapper.py

This is ready for review. I'm going to make another PR pulling out the `SELECT` assertions to use functions from the `assertions` module. @knifewine and/or @ptnapoleon to review.
Much of this uses checks over the driver's cluster metadata instead of the previous assertions -- for example, rather than adding a column to a table, then asserting that a query has the result we expect, we directly check `<metadata object>'.columns`. To make this easier, I've added a collection of objects that, when accessing items or attributes, refresh the appropriate metadata and update themselves. The API there is up for grabs, but the idea is that it basically looks like a `cassandra.metadata.Metadata` object, except you don't have to refresh the metadata before accessing its attributes.
I'm still running …

Cql tests audit followup

---

requirements.txt

`blist` shouldn't be necessary anymore since the changes to the driver last year.
(this also sorts the bare package installs in `requirements.txt`, I didn't add `docopt` in the correct position in the file.)

Remove blist

---

thrift_tests.py

@blerer This test fails on 2.2:
http://cassci.datastax.com/job/cassandra-2.2_novnode_dtest/227/testReport/thrift_tests/TestMutations/test_expiration_with_default_ttl_and_zero_ttl/
http://cassci.datastax.com/job/cassandra-2.2_dtest/539/testReport/thrift_tests/TestMutations/test_expiration_with_default_ttl_and_zero_ttl/
Is it meant to pass there? If so, I'll file a ticket; otherwise, we can just apply `@since` to it.

add since to test failing on 2.2

---

upgrade_tests/upgrade_through_versions_test.py

@knifewine could you have a look-see? This has to do with our recent talk about what to do with, e.g., the tests upgrading from 3.1 to 3.2.

remove upgrade paths that won't change anymore

---

jmxmetrics_test.py

Looks like it's been a while since anyone's looked at https://issues.apache.org/jira/browse/CASSANDRA-10845, so I figured I'd skip this for the time being. Any objections?

skip failing jmx metrics test

---

upgrade_tests/upgrade_through_versions_test.py

this has been the source of a number of problems and should be
removed for simplification.
each of these test modules is built with a different purpose in mind
and having them tangled has become an issue.
this needs to be followed up with proper expansion of schema coverage
within upgrade_through_versions or in another test built for the express
purpose of upgrade testing

remove upgrade_through dep on schema_metadata_test

---

repair_tests/repair_test.py

for the tests that test this option

The `-tr` option does not exist in 2.1. Restricting test version

---

bootstrap_test.py
consistency_test.py
consistent_bootstrap_test.py
global_row_key_cache_test.py
replace_address_test.py
snitch_test.py

https://github.com/pcmanus/ccm/pull/464. wait-other-notice now defaults to True, so we need
to set it to False in some places. Also, start is no longer
idempotent, so we can't double start() in some tests
Running here:
http://cassci.datastax.com/view/Dev/view/ptnapoleon/job/ptnapoleon-cassandra-2.2-dtest/

Make changes to tests based on CCM node start API changes

---

repair_tests/repair_test.py

Don't specify the order of endpoints in repair log grep

---

upgrade_tests/cql_tests.py

write and read back at more appropriate levels
write at cl.all and read back at cl.one
it's possible that this test was failing previously
when a coordinator (and selfsame replica) would defer
to another node at cl.one, allowing a stale data read
and therefore an assertion failure

whole_list_condition_test flakiness fix

---

cqlsh_tests/cqlsh_copy_tests.py

I've added a text column to the primary key of `test_reading_counter`, which was introduced by CASSANDRA-9043. For counter tables we need to test values that require quotes as well: there was an issue with missing quotes that was introduced by CASSANDRA-9302 and fixed by CASSANDRA-11053. Unfortunately this problem found its way to a customer and so I would like to ensure this does not happen again in future.

Extended test for CASSANDRA-9043

---

deletion_test.py

I needed to tag this, and the docstring was old and sparse, so I figured I'd clean things up a bit. I've
- added a tag
- run isort
- fleshed out the docstring
- made stronger assertions using `assertEqual` instead of a bare `assert`
Runs fine for me locally.

gc_test tag and improvments

---

cqlsh_tests/cqlsh_copy_tests.py

CASSANDRA-11184 and CASSANDRA-11185 have been fixed for quite some time, so I closed them and removed the known failure for CASSANDRA-11185.

Removed known failure for CASSANDRA-11185

---

cqlsh_tests/cqlsh_copy_tests.py

A new test for CASSANDRA-11255 and some changes due to a new default precision for double values in COPY TO.

Test and changes for CASSANDRA-11255

---

auth_test.py

@ptnapoleon to review. Main fix is to prevent flakes like this in the future:
http://cassci.datastax.com/job/cassandra-3.0_dtest/607/testReport/junit/auth_test/TestAuthRoles/grant_revoke_roles_test/
I also removed some unused variables that `flake8` caught. @ptnapoleon I pushed this to the `riptano` repo so you could rebase out the `flake8 fixes` commit and actually use those `usercount` variables if you want.

Fix auth race condition

---

replace_address_test.py

Removing the annotation since the ticket was closed. Do we know why we skip this pre-2.2? If it hangs or something we should skip it.

remove known_failure annotation

---

replace_address_test.py

We expect it to fail to start up, and thus we need to
set wait_other_notice to false

Fix node4 start in resumable_replace_address

---

topology_test.py

Node1 is being decommissioned while we restart node2. thus we
cannot guarantee that node1 will be alive to detect node2 is up.
So we must start node2 with wait_other_notice=False each time

Fix node start in crash_during_decommission

---

upgrade_supercolumns_test.py

@mambocab to review.
We don't test on 2.0 anymore, so we should step always assume we're on 2.1. Easier than doing complicated version checking code.

Change SCUpgrade tests to assume we are always on 2.1

---

repair_tests/incremental_repair_test.py

This PR removes the known_failure annotation from sstable_repairedset_test in incremental_repair_test.py.
[History for sstable_repairedset_test](http://cassci.datastax.com/job/cassandra-2.2_dtest/552/testReport/repair_tests.incremental_repair_test/TestIncRepair/sstable_repairedset_test/history/) shows this has been passing for 3 runs now.
CASSANDRA-9598 solved the issue by making cassandra.yaml available on the classpath, so that sstablerepairedset no longer fails on loading config.

Remove known failure from sstable_repairedset_test after CASSANDRA-11317

---

index_summary_upgrade_test.py
jmx_test.py
jmxmetrics_test.py
materialized_views_test.py
repair_tests/repair_test.py

@knifewine can you have a quick look? this is just more information in the `notes` fields of some `known_failure`s.

add notes for known failures

---

sslkeytool.py
sslnodetonode_test.py

This set of tests can be run to test if server ssl options will have the expected effect on node-to-node communication. It provides a module for interacting with the keytool and will start the cluster with various ssl settings. 
Depends on [CASSANDRA-9220](https://issues.apache.org/jira/browse/CASSANDRA-9220) for hostname verification and log output with detailed handshake errors.
The test needs to have keytool and openssl in the current path.

Test for CASSANDRA-9220

---

replication_test.py

This will hopefully address [CASSANDRA-11417](https://issues.apache.org/jira/browse/CASSANDRA-11417) by blocking until all nodes agree on a schema before moving on to make `nodetool` calls over recently-created tables.

CASSANDRA-11417

---

conf/cassandra-2.1_test-select.cfg
conf/cassandra-2.2_test-select.cfg
conf/trunk_test-select.cfg
consistency_test.py

@mambocab and @exlt to review.
Testing here:
http://cassci.datastax.com/view/Dev/view/ptnapoleon/job/ptnapoleon-cassandra-2.1-dtest/12/console
All job configs will need changed to use the fast-select.cfg instead of test-select.cfg

Skip all 6+ node tests on CI

---

cqlsh_tests/cqlsh_copy_tests.py

A new test to cover a cqlsh COPY issue that was discovered on a machine with a single core. Please do not merge until CASSANDRA-11053 is resolved.

Additional test for CASSANDRA-11053

---

sstable_generation_loading_test.py

Test for [CASSANDRA-11275](https://issues.apache.org/jira/browse/CASSANDRA-11275).
```sstableloader``` is failing in 3.0+ when MV is present.
This PR adds test in that situation.

Add test for CASSANDRA-11275

---

dtest.py

I'm not sure whether or not to be concerned about false positives here -- will there be cases where we want this debug information? But, at the very least, this should remove a whole lot of useless error messages from test output.

filter out annoying "connection failed" messages

---

INSTALL.md

All tested versions support 8. not all versions support 7.
This is a clearly needed change
@mshuler  to review

Mention jdk 8 in install docs, not 7

---

user_types_test.py

See https://issues.apache.org/jira/browse/CASSANDRA-11498 for explanation of bug. In particular, there's a schema disagreement at some point in the flake we saw, so this blocks on schema agreement with the driver before trying to use created tables.
Also includes a pep8 fix.

attempt to address CASSANDRA-11498

---

consistency_test.py

My comment on the default snitch is slightly incorrect, see discussion on CASSANDRA-11488.

CASSANDRA-11225: fixed comment on default snitch

---

user_functions_test.py

Boolean condition was accidentally negated
Fixes bug in #829

UDTs prior to 7423 should always be frozen

---

repair_tests/incremental_repair_test.py

We should let dtest handle when to run this with and without vnodes. It was originally explicitly set to True always, as that is a more rigorous test case than without vnodes. There is no chance of us ever stopping testing on vnodes by default, so we shouldn't override this in the test.
@knifewine to review

Fix 11563. Don't explicitly set vnodes in test

---

cqlsh_tests/cqlsh_copy_tests.py

I've added the check on the number of cores to `test_bulk_round_trip_with_single_core` as discussed on CASSANDRA-11437. 
This pull request must be merged together with the C* patch.

Added check on number of cores detected (CASSANDRA-11437)

---

cqlsh_tests/cqlsh_copy_tests.py

By using it as an arg, we were placing it were the retry policy
should be. Causing 11565 and 11494, amongst others.

Properly set CL kwarg in cqlsh copy tests

---

commitlog_test.py

A couple major internal API changes:
- removes unused size-getting method
- changes the commitlog-dir-getting code to return a list, since commitlogs are going to be in `{data}/commitlogs` and `{data}/cdc` now
as well as some some small cleanup changes

Commitlog test debugging and path getting refactor

---

commitlog_test.py
requirements.txt

DON'T MERGE UNTIL WE'VE UPDATED DEPENDENCIES IN OUR INSTALL SCRIPTS.
I have a few concerns about this one.
- @ptnapoleon Could you please run this test on Windows to make sure `parse` behaves the way we expect?
- I'm worried about the change in SSTable-grabbing code -- I don't think there was a reason to write custom to grab SSTables. Can someone confirm?
I'm actually quite happy with the way the log-checking code turned out. Of course, please have a good hard look at it. Asking for reviews from both @ptnapoleon and @knifewine please.

Fix commitlog replay test

---

bootstrap_test.py
cqlsh_tests/cqlsh_copy_tests.py

Some additional tests for CASSANDRA-11631 (missing values without prepared statements). Please do not merge until ticket is committed.

Tests for CASSANDRA-11631

---

cqlsh_tests/cqlsh_copy_tests.py

This replaces #961, using our metadata wrapper instead of a one-off function -- thanks to @stef1927. @stef1927 and @ptnapoleon or @knifewine, can you review please?
Test run here:
https://cassci.datastax.com/view/Parameterized/job/parameterized_dtest_multiplexer/87/
Filed [PYTHON-554](https://datastax-oss.atlassian.net/projects/PYTHON/issues/PYTHON-554) to hopefully obviate this whole issue.

Tentative fix for CASSANDRA-11676

---

tools.py
upgrade_supercolumns_test.py

this is for special case tests that are difficult to repair, but generally harmless when they fail, provided they can be verified to pass the majority of the time.

allow ambiguous tests

---

upgrade_tests/cql_tests.py
upgrade_tests/paging_test.py
upgrade_tests/regression_test.py
upgrade_tests/upgrade_base.py
upgrade_tests/upgrade_manifest.py
upgrade_tests/upgrade_through_versions_test.py

(mostly) unites test class generation between
the upgrade_through_version tests and the other upgrade
tests of mixed version clusters.
introduces clearer metaphors and makes test coverage
more explicit with the concept of indev, current, and next
for each version.
generative approach to tests using a manifest or starting
versions to all possible upgraded-to versions

new upgrade version logic

---

upgrade_tests/upgrade_manifest.py

this is to make local testing easier for devs in their envs.
this was the simplest way I could think to help make local testing both flexible and not too awful.

instructions and template-ish code for custom upgrade path testing

---

upgrade_tests/upgrade_base.py
upgrade_tests/upgrade_manifest.py
upgrade_tests/upgrade_through_versions_test.py

allows us to re-enable 2.0->2.1 upgrade testing

upgrades: add java version awareness

---

auth_test.py
dtest.py
user_functions_test.py

The first commit here (`don't use env vars for getting C* version`) is intended to fix #976, but does not on my machine. Regardless, I think it's a good thing to do. To demonstrate the problem in #976, run `auth_test.py:TestAuthRoles` with the `CASSANDRA_DIR` env var unset, and the `CASSANDRA_VERSION` var set.
I'm not sure why this doesn't fix the issue. Any thoughts? @ptnapoleon @knifewine

Fix auth test import

---

auth_test.py
bin/collect_known_failures.py
dtest.py
user_functions_test.py

Ok, un-reverts and fixes #978. See comments and commit messages. Should fix 976 without breaking `bin/collect_known_failures.py`

Fix auth test import post revert

---

auth_test.py
user_types_test.py

CASSANDRA-11890 covers recent auth failures in tests on 2.2, 3.0, and 3.x. They appeared recently because the cassandra-test branch of the Python driver was updated for the 3.4.0 driver release.
These failures come from two commits in [datastax/python-driver](https://github.com/datastax/python-driver/commits/cassandra-test).
The failures in user_types_test came from this [commit](https://github.com/datastax/python-driver/commit/88b013daac765cec04626cc3d5fdad804fd0b19b), which adds error checking for positional retry_policy parameters. A consistency level was instead being passed; we now pass this as a labeled argument.
The failures in auth_test came from this [commit](https://github.com/datastax/python-driver/commit/da994dcd3ad76f3eacae367b87f345f2ccc7a1c4), which explicitly states when …

Fix CASSANDRA-11890

---

scrub_test.py

This is for [CASSANDRA-11693](https://issues.apache.org/jira/browse/CASSANDRA-11693).
Since range-aware JBOD is introduced, there is a chance that zero byte SSTable is created (not actually on the disk, just internally) and generation number goes out of sync with what tests expect.
I propose to simply disable JBOD configuration for scrub tests, since it is not the target of the tests anyway.

Force single data dir for scrub tests

---

commitlog_test.py

Had a few style and readability nits to pick with [a recent PR](https://github.com/riptano/cassandra-dtest/pull/998) that I didn't see until after it was merged.
Locally, my changes pass on `trunk` and `cassandra-3.0`, and fail as expected (with a bunch of `org.apache.cassandra.exceptions.WriteTimeoutException: Operation timed out - received only 0 responses.` messages) on `3.0.5`, which is consistent with the bug describtion in [CASSANDRA-11891](https://issues.apache.org/jira/browse/CASSANDRA-11891).

Readability nits

---

upgrade_tests/upgrade_manifest.py

Not to be merged until 3.7/3.0.7 are fully released!
Probably will need one more commit to update indev_3_x as well, since that's currently pointing to the 3.7 branch (which after release isn't likely to see more commits).

bump released vers to 3.7/3.0.7

---

.travis.yml
linter_check.sh

I strongly believe the current pep8 arguments are incorrect. For example, see these nits from a recent travis build:
```
json_test.py/assertions.py:1:1: E902 IOError: [Errno 20] Not a directory: 'json_test.py/assertions.py'
json_test.py/meta_tests/assertion_test.py:1:1: E902 IOError: [Errno 20] Not a directory:'json_test.py/meta_tests/assertion_test.py'
```
Looking at the output of `pep8 --help`, I don't think we can exclusively ignore errors on only one file. So either we stop linting E501, or we stop linting json_test.py. I don't think there's a union of those two goals, so I chose the former. That choice is up for debate, as well as my assumption that there is no way to do what we really want.

Stop checking line length

---

paging_test.py

Multiplexed test can be found [here](https://cassci.datastax.com/view/Parameterized/job/parameterized_dtest_multiplexer/129/)

Use `wait_for_any_log` to wait/grep for logs to avoid test failures caused by buffering.

---

repair_tests/repair_test.py

@ptnapoleon, please review.
Fix being tested here: http://cassci.datastax.com/view/Parameterized/job/parameterized_dtest_multiplexer/132

use self.cluster

---

pushed_notifications_test.py

Since 2.1 is critical fixes only, the patch to ensure correct behaviour for 11038 was only added from 2.2 onwards, so it's probably wise to only run it's test on those versions.
(see also: CASSANDRA-12056)

Only run test from CASSANDRA-11038 on 2.2+

---

cql_tracing_test.py

@thobbs, please review. Looking at CASSANDRA-11598, it seems we version gated the wrong searches.

restricted regex to 2.2+

---

cqlsh_tests/cqlsh_copy_tests.py

Here is a tentative fix for  CASSANDRA-12024, don't merge until it has been tested with a repeated batch of tests.

Fix for CASSANDRA-12024: pick a real token range to signal copy child processes to fail

---

sstable_generation_loading_test.py
upgrade_tests/storage_engine_upgrade_test.py

Also fixed create_schema to create compact tables when that is set.
~~Submitted CI run: http://cassci.datastax.com/view/Dev/view/paulomotta/job/pauloricardomg-trunkcopy-dtest/7/~~
EDIT: previous CI run failed, resubmitted here: http://cassci.datastax.com/view/Dev/view/paulomotta/job/pauloricardomg-trunkcopy2-dtest/1/

Move sstableloader upgrade tests to upgrade_tests/storage_engine_upgrade_test

---

compaction_test.py
cqlsh_tests/cqlsh_copy_tests.py
cqlsh_tests/cqlsh_tests.py
jmxutils.py

We'll probably need to fix the ccm/dtest versioning scheme to be more resilient and use `distutils.version.LooseVersion` exclusively, but this is a more immediate fix to fix trunk dtests more promptly.
Submitted dtest run: http://cassci.datastax.com/view/Dev/view/paulomotta/job/pauloricardomg-trunkcopy2-dtest/4/

Fix broken trunk dtests due to version change to 3.10

---

dtest.py
repair_tests/repair_test.py
upgrade_tests/repair_test.py

Main changes are:
* Upgrade from 2.2.5 instead of 2.1.9 to avoid windows incompatibility and other minor bugs
* Set dclocal_read_repair_chance when read_repair is specified on dtest.create_cf
* Move repair upgrade test to upgrade suite and only run when UPGRADE_TEST_RUN=true
Multiplexer 100x run: https://cassci.datastax.com/view/Parameterized/job/parameterized_dtest_multiplexer/157/ (the only failure is due to CASSANDRA-11393)
Dtest trunk run: http://cassci.datastax.com/view/Dev/view/paulomotta/job/pauloricardomg-trunkcopy-dtest/19/

Fix repair_tests.repair_test.TestRepair.repair_after_upgrade_test (CASSANDRA-12057)

---

auth_test.py
compaction_test.py
cql_tracing_test.py
cqlsh_tests/cqlsh_copy_tests.py
cqlsh_tests/cqlsh_tests.py

In [CASSANDRA-12032](https://issues.apache.org/jira/browse/CASSANDRA-12032), we bumped the netty version in Cassandra to 4.0.37. This contained a bug that caused a variety of dtest failures, including CASSANDRA-12072, CASSANDRA-12067, CASSANDRA-12058, CASSANDRA-12059, and CASSANDRA-12061. 
With commit 78f077de079d0b3760a06a7f944be070772b0c83 in Cassandra, the netty version was reverted to 4.0.36. None of these failures have repeated after the revert.

Remove annotations from tests that failed due to recent netty bug

---

paging_test.py

Shouldn't we insert at CL.ALL if by default we read at CL.ONE? I managed to get a failure locally by forcing an exclusive connection to one node, which I was using for debugging some paging problems in CASSANDRA-11521.
I also fixed a typo.

Write at CL.ALL for paging tests

---

write_failures_test.py

@ptnapoleon @thobbs This is the same failure as https://issues.apache.org/jira/browse/CASSANDRA-12213 right?

tag flaky test

---

rebuild_test.py

Noticed this while looking into
https://issues.apache.org/jira/browse/CASSANDRA-11687
This code wasn't using the same logic between `rebuild` and the code at the top level in the test -- the to-level code would increment `self.rebuild_errors` on any `NodetoolError`, rather than just the one we expect.
I've also re-raised the error when we find an unexpected `NodetoolErrors` -- these should fail the test, yes?

make `nodetool rebuild` calls use same logic

---

dtest.py

`get_test_path` is discovered by `nosetests` as a test in all test modules where it's imported, because it has `test` in the name. This PR manually prevents that:
```sh
~/cstar_src/cassandra-dtest master
(dtest) ❯ CASSANDRA_VERSION=git:trunk nosetests --collect-only -vv --pasteable 2>&1 snapshot_test.py | grep get_test_path
snapshot_test.py:get_test_path ... ok
~/cstar_src/cassandra-dtest master
(dtest) ❯ g co dont-run-get_test_path
Switched to branch 'dont-run-get_test_path'
~/cstar_src/cassandra-dtest dont-run-get_test_path
(dtest) ❯ CASSANDRA_VERSION=git:trunk nosetests --collect-only -vv --pasteable 2>&1 snapshot_test.py | grep get_test_path
~/cstar_src/cassandra-dtest dont-run-get_test_path
(dtest) ❯
```

make get_test_path a non-test

---

scrub_test.py

[@ptnapoleon suggests blocking before assertions in this test](https://issues.apache.org/jira/browse/CASSANDRA-11446?focusedCommentId=15296657&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15296657). So, this PR does that.

add compaction waits for CASSANDRA-11446

---

cqlsh_tests/cqlsh_copy_tests.py
cqlsh_tests/cqlsh_tests.py
json_test.py

These are the companion changes for [CASSANDRA-11850](https://issues.apache.org/jira/browse/CASSANDRA-11850), which upgrades the python driver version embedded with cqlsh. 
This PR must be merge at the same time as the c* patch.

Fixes for CASSANDRA-11850

---

offline_tools_test.py

This should fix the test by removing a duplicate **-rate ...** parameter, which was passed to **stress**.

CASSANDRA-12287: Fix sstablelevelreset_test

---

cqlsh_tests/cqlsh_tests.py

Run cqlsh_tests.py:test_unicode_invalid_request_error for 2.2+ only

---

rebuild_test.py

This is a fix for the immediate problem in [CASSANDRA-11687](https://issues.apache.org/jira/browse/CASSANDRA-11687). This will not close the ticket, as the tests fails.
I'm not sure this is a long-term solution, so I've filed [CASSANDRA-12296](https://issues.apache.org/jira/browse/CASSANDRA-12296).

add ALTER KEYSPACE to make rebuild commands work

---

rebuild_test.py

Current test implementation didn't trigger rebuild concurrently even though we are using thread in my local laptop. I think the same thing is happening in CI since it is hitting assertion error that indicates it.
So I changed the code to run nodetool in background first, and then immediately trigger second one in foreground, and the latter should fail at that point.
Rebuild completion from the former is guarded by wathing log.

Fix simple_rebuild_test

---

cql_tracing_test.py

These are the changes that should be committed after CASSANDRA-11465 is also committed, to improve reliability with tracing events.

CASSANDRA-11465: increase timeout for tracing synchronization

---

offline_tools_test.py

`offline_tools_test` fails on Mac because it does not expect "normal" warnings (`JNA link failure` and `Class JavaLaunchHelper is implemented in both`) in the assertion.
PR adds these to the exclusions.
```
FAIL: sstablelevelreset_test (offline_tools_test.TestOfflineTools)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/Users/snazy/devel/cassandra/dtest/offline_tools_test.py", line 49, in sstablelevelreset_test
self._check_stderr_error(error)
File "/Users/snazy/devel/cassandra/dtest/offline_tools_test.py", line 411, in _check_stderr_error
'Found line \n\n"{line}"\n\n in error\n\n{error}'.format(line=line, error=error))
AssertionError: Found line 
"objc[51491]: Class JavaLaunchHelper is implemented in both …
```

exclude OSX specific error/warning from assertion

---

rebuild_test.py

First of all, my fix in #1146 was not doing the job. Even though nodetool is invoked in background first, the second call can be invoked first. So I reverted the changes made.
Now, I noticed that we were trying to spawn Thread to run rebuild in parallel, but actually it wasn't. The first rebuild is called before the thread is created, resulting sequential rebuild call instead of parallel.
@mambocab @pauloricardomg can you run multiplexer on this one?

CASSANDRA-11687

---

upgrade_tests/upgrade_base.py

https://issues.apache.org/jira/browse/CASSANDRA-11126?focusedCommentId=15404041&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15404041
If you try to run tests in one of the base test classes, the error message is just incidental and doesn't help much if you don't understand the way the tests are generated:
```
RUN_STATIC_UPGRADE_MATRIX=true CASSANDRA_VERSION=git:trunk JAVA8_HOME=/usr/lib/jvm/java-8-openjdk JAVA7_HOME=/usr/lib/jvm/java-7-openjdk python2.7 ./run_dtests.py --vnodes false  --nose-options='-v' upgrade_tests/cql_tests.py:TestCQL.select_distinct_with_deletions_test
[...]
======================================================================
ERROR: select_distinct_with_deletions_test (upgrade_tests.cql_tests.TestCQL) …
```

add more helpful message to upgrade base class

---

INSTALL.md

This is how we install on CI. The Google code repo no longer exists.

Update INSTALL.md for most recent method of installing CQL

---

materialized_views_test.py

I saw some failures on a multiplexer run:
http://cassci.datastax.com/view/Parameterized/job/parameterized_dtest_multiplexer/169/testReport/junit/node_0_iter_246.materialized_views_test/TestMaterializedViews/complex_repair_test/
that look like the session trying to connect to (correctly) downed nodes. Running `materialized_views_test.py:TestMaterializedViews.complex_repair_test` succeeds on my machine.

close session before shutting down nodes

---

jmx_auth_test.py
jmxutils.py

PR for issue at [CASSANDRA-11730](https://issues.apache.org/jira/browse/CASSANDRA-11730). This edits the Windows config files appropriately to set up JMX auth.

Fix enabling of jmx auth on windows

---

tools.py

This will make double-annotation with known_failure work as expected with the notes parameter - if you tag it twice, but omit notes in the outer decorator, the notes will be an empty string.
@knifewine can you review please?

default to empty notes field

---

upgrade_tests/paging_test.py

Add a small loop sleep, and improve debug message when paging times out.
I spotted these small differences comparing the regular paging tests to the upgrade paging tests, and thought they could be useful in the upgrade suite.
At some point we should extract the paging utility classes to a single place, so that both paging suites can pull it in without code duplication, so this is a small band-aid for now.

page wait() small improvements

---

upgrade_tests/paging_test.py

Due to CASSANDRA-10880 there's a special case that needs to be handled with protocol version.
This mixed cluster combination of 2.2/3.0 needs to work over proto v3, rather than v4 (despite that fact that both support v4).

special case for 2.2/3.0 mixed version cluster paging

---

repair_tests/repair_test.py

@ptnapoleon or @mambocab or @knifewine, for your consideration.
The `--node` argument is redundant here, as it is specified inside of ccmlib/node.py here:
https://github.com/pcmanus/ccm/blob/master/ccmlib/node.py#L1226-L1229
Running a quick multiplex here: http://cassci.datastax.com/view/Parameterized/job/parameterized_dtest_multiplexer/218/

remove redundant argument

---

bootstrap_test.py

Moved all stress commands within the context management
of the profile tmp file. Previously we deleted file,
then attempted to read from it again
@smccarthy788 to review

Fix stress profile in local_quorum_bootstrap

---

cql_tracing_test.py

`cql_tracing_test.py` currently doesn't run because `known_failure` was added without an import for it.

Added missing known_failure import

---

upgrade_supercolumns_test.py
upgrade_tests/upgrade_base.py

@knifewine Could I get a quick review? This should successfully ignore the error in [CASSANDRA-12340](https://issues.apache.org/jira/browse/CASSANDRA-12340), yeah?
I forgot to remove the `known_failure` annotation, so I'll need to do that before merge, if we merge this.

Ignore log error cassandra 12340

---

jmxutils.py

This pull request is intended to fix [CASSANDRA-11730](https://issues.apache.org/jira/browse/CASSANDRA-11730).
I originally PRed a fix to this issue as PR #1175 but the config file contents concurrently changed in [CASSANDRA-12109](https://issues.apache.org/jira/browse/CASSANDRA-12109), so the replace was no longer working correctly. This now passes correctly on trunk.
@mambocab to review probably, since he reviewed the original.

Update jmx_auth_test on Windows for config file changes

---

requirements.txt

This is not very useful now, because our CI doesn't yet use this `requirements.txt`. However, once it does, this will be helpful: it makes `pip freeze` report the hash of the installed commit for the driver and CCM:
```sh
~/cstar_src/cassandra-dtest master*  11s
(dtest-test-sha-reporting) ❯ pip install -r requirements.txt 
Obtaining cassandra-driver from git+https://github.com/datastax/python-driver.git@cassandra-test#egg=cassandra-driver (from -r requirements.txt (line 1))
Cloning https://github.com/datastax/python-driver.git (to cassandra-test) to /home/mambocab/.pyenv/versions/2.7.12/envs/dtest-test-sha-reporting/src/cassandra-driver
Obtaining ccm from git+https://github.com/pcmanus/ccm.git@master#egg=ccm (from -r requirements.txt (line 2))
Updating …
```

install driver & ccm as editable eggs

---

upgrade_tests/cql_tests.py

10783 was committed in 3.8, so we should NOT expect 3.8
to have the old error
@knifewine to review

Filter new alias error message with < 3.8

---

topology_test.py

Submitted [multiplexer run](https://cassci.datastax.com/view/Parameterized/job/parameterized_dtest_multiplexer/235/).

Fix race on crash_during_decommission_test (CASSANDRA-11611)

---

cqlsh_tests/cqlsh_copy_tests.py

As discussed on the ticket, we need more debug information to understand why the test failed.

Added more debug information for CASSANDRA-12430

---

bootstrap_test.py
stream_failure.btm
tools.py

Although It's faily stable recently, [the most recent failure](http://cassci.datastax.com/job/cassandra-3.9_novnode_dtest/30/testReport/bootstrap_test/TestBootstrap/resumable_bootstrap_test/) indicates there still be a chance that the test fails because bootstrap streaming is not interrupted as expected.
This patch uses byteman instead of Thread and watch_for_log for killing node to fail bootstrap stream.
This is more reliable and since we can eliminate node start/stop and decrease the size of SSTable, test runs much faster (2x to 3x).
Byteman support is added to 2.2 also so this should be fine.

Stabilize resumable_bootstrap_test by using byteman

---

tools.py

This class was removed in https://github.com/riptano/cassandra-dtest/pull/1213, but I missed on review that `InterruptBoostrap` is used elsewhere.

re-introduce InterruptBootstrap

---

dtest.py

This was a tweak suggested by @aholmberg that restores an old behavior of the Python driver. Previously, the driver waited for all pools on cluster connect. Now, the default behavior is to return after successfully connecting to one. Note that this change would break tests for users who have not updated their driver.
@aholmberg, what are the consequences if we don't enable this? Tests should continue to function correctly, right?

Wait for all pools on cluster connect

---

repair_tests/deprecated_repair_test.py
repair_tests/repair_test.py

This adds a dtest for pull repairs, which are introduced in [CASSANDRA-9876](https://issues.apache.org/jira/browse/CASSANDRA-9876).

Add pull repair test for CASSANDRA-9876

---

cql_tests.py
meta_tests/utils_test/metadata_wrapper_test.py
utils/metadata_wrapper.py

Adds tests for `metadata_wrapper` in advance of some changes I want to make for [CASSANDRA-12456](https://issues.apache.org/jira/browse/CASSANDRA-12456).

Metadata wrapper tests

---

upgrade_internal_auth_test.py

It's been suggested that the control connections for in-test Cluster objects may be the cause of flaky failure detailed in CASSANDRA-12523. Closing the actual cluster objects, rather just the sessions should obviate that.

Ensure all connections are closed during upgrade test

---

bootstrap_test.py

@ptnapoleon, for your review.
We first questioned the validity of the error message in line 405 during cstar-97. I am unable to find it in the cassandra source code. Now that `stress` should return the correct return code, this test will automatically fail if stress fails, but as an extra precaution, I've checked stderr is clean, and left in the original error message check.

check stderr has no errors

---

requirements.txt

Works around some weird Cython behavior in old `pip`s. Works for me locally. Feel free to merge on review, it's just a lil thing that I'm confident about.

change requirement installation order

---

requirements.txt

When we migrated to using `requirements.txt`, missing this dependency made this test fail:
http://cassci.datastax.com/job/trunk_dtest/1359/testReport/junit/cqlsh_tests.cqlsh_tests/TestCqlsh/test_pep8_compliance/

add pep8 to requirements.txt

---

cql_tracing_test.py

Breakage is from https://github.com/riptano/cassandra-dtest/pull/1281/files
Fixes https://issues.apache.org/jira/browse/CASSANDRA-12579
@knifewine to review, please

Version gate changes from 11706

---

batch_test.py

Start the node in logged_batch_doesnt_throw_uae_test in order to make sure that repair happens during the write to avoid reading partial data, as write is done with CL ANY.
Cassandra ticket: https://issues.apache.org/jira/browse/CASSANDRA-12383 (waiting for CI results)

Start the node in logged_batch_doesnt_throw_uae_test

---

cql_tests.py
paging_test.py
user_types_test.py

dtests for #11031 (still in review)
Puts back riptano/cassandra-dtest#969 once ticket is merged

Add test for Cassandra-11031 allow filtering on partition key

---

repair_tests/repair_test.py

```
02:36 PM:~/cstar/cassandra-dtest[fix-12640*]$ nose -sv --collect-only -a 'resource-intensive' repair_tests/repair_test.py
initial_empty_repair_tables_test (repair_tests.repair_test.TestRepairDataSystemTable) ... ok
repair_parent_table_test (repair_tests.repair_test.TestRepairDataSystemTable) ... ok
repair_table_test (repair_tests.repair_test.TestRepairDataSystemTable) ... ok
----------------------------------------------------------------------
Ran 3 tests in 0.000s
OK
```
@smccarthy788 to review

Mark 5 node repair tests as resource intensive

---

replace_address_test.py

Fixes this error
```
======================================================================
ERROR: resume_failed_replace_test (replace_address_test.TestReplaceAddress)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/mshuler/git/cassandra-dtest/tools/decorators.py", line 46, in wrapped
f(obj)
File "/home/mshuler/git/cassandra-dtest/replace_address_test.py", line 444, in resume_failed_replace_test
self._test_restart_failed_replace(mode='resume')
File "/home/mshuler/git/cassandra-dtest/replace_address_test.py", line 463, in _test_restart_failed_replace
self.ignore_log_patterns.append(r'Error while waiting on bootstrap to complete')
AttributeError: 'tuple' object has no attribute 'append'
-------------------- >> begin …
```

Fix log pattern append in replace_address_test

---

snitch_test.py

This typo was fixed in https://github.com/apache/cassandra/commit/2dc2bb808634be9aaf5ee1d65eb968f8c5514305, but the test was never updated accordingly.

Parameterize error message in snitch_test after typo fix in C*

---

pushed_notifications_test.py

More flexible expectations for 2.1 nodes in pushed_notifications_test

---

repair_tests/deprecated_repair_test.py

This supercedes #1299. Passes locally on [Tyler's branch](https://github.com/thobbs/cassandra/tree/CASSANDRA-12532-trunk) and HEAD on `cassandra-3.0` `cassandra-2.2` `cassandra-2.1`.
@thobbs, could you review please?

Cassandra 12532 log statement

---

upgrade_tests/cql_tests.py

@knifewine or @smccarthy788 to review. I ran these all locally across all relevant versions. The only failing test was failing 100% consistently, so no real need for CI.

Use correct version check function in upgrade cql_tests

---

cql_tests.py

CCM uses 'datacenter1'. The dtest uses 'dc1'. CASSANDRA-12681 validates the datacenter name. 
Whether or not CASSANDRA-12681 gets merged, we should use the real datacenter name.

Update CQL tests to use proper DC name for CASSANDRA-12681

---

upgrade_tests/cql_tests.py

Removing the `known_failure` annotations for `multi_collection_test` and `multi_list_set_test` as the problem behind those tests seems to have been fixed.

Removes outdated known_failure annotations

---

auth_test.py
meta_tests/utils_test/metadata_wrapper_test.py
tools/metadata_wrapper.py

Adds and tests a `max_schema_agreement_wait` to the metadata wrappers, uses one of those wrappers in the auth test that failed in [CASSANDRA-12456](https://issues.apache.org/jira/browse/CASSANDRA-12456), then bumps the wait in that test.

Bump timeout for cassandra 12456

---

bin/collect_known_failures.py
tools/decorators.py

Update `collect_known_failure.py` to reflect this.
@mambocab, please review.
Tests with two annotations will be represented by `collect_known_failure.py` as:
```bash
{"failure_annotations": [{"failure_source": "test", "notes": "", "known_flaky": true, "jira_url": 
"https://issues.apache.org/jira/browse/CASSANDRA-12444"}, {"failure_source": "cassandra", "notes": "", "known_flaky": true, "jira_url": "https://issues.apache.org/jira/browse/CASSANDRA-12457"}], "name": "TestUpgrade_current_3_x_To_indev_3_x.rolling_upgrade_test", "module": "upgrade_tests.upgrade_through_versions_test"} ... ok
```
Something we should think about is any place where we access the `known_failure` attribute thinking there will be the `failure_source` value. I'm not aware of anything like this in dtest, but maybe it …

known_failure decorator tracks annotations as a list of dicts.

---

auth_test.py
tools/assertions.py

To be merged if and only iff CASSANDRA-12700 is committed in its current form.

Changes for CASSANDRA-12700: test for corrupt auth table

---

cqlsh_tests/cqlsh_copy_tests.py

In view of some recent failures in cqlsh copy tests that are very hard to reproduce, I propose to show the output of the cqlsh copy commands for all tests, so that in future we may be able to understand why a copy command has failed. 
I've already run the patch [here](https://cassci.datastax.com/view/Dev/view/stef1927/job/stef1927-dtest-multiplex/73/).

Make show_output=True the default for all cqlsh copy tests

---

rebuild_test.py

These are new dtests to go along with the changes in [CASSANDRA-9875](https://issues.apache.org/jira/browse/CASSANDRA-9875).

Source specific and error validation rebuild tests for CASSANDRA-9875

---

upgrade_internal_auth_test.py

[CASSANDRA-12813](https://issues.apache.org/jira/browse/CASSANDRA-12813)
Follow up after the #1381 
Unfortunately, the previous version contained a bug that made it look like C* patch was correct, so the test was failing when we needed it to and succeeding in other case. I've simplified and rewritten the tests. 
After the bug I mentioned was fixed, the other problem appeared: test was flaky because system_auth was not always available on the clean node. I've fixed it in this version by increasing a CL of `system_auth` and making sure the node sees it.
I haven't squashed commits if anyone wanted to see history.
CI results:
[2.2](https://cassci.datastax.com/job/ifesdjeen-2.2-dtest/) 
[3.0](https://cassci.datastax.com/job/ifesdjeen-3.0-dtest/) …

Add dtest for CASSANDRA-12813

---

bootstrap_test.py

The changes to subprocess' stdout/stderr when starting a ccm node seem to have broken simultaneous_bootstrap_test. The changes I've made fix the test, but there may be better ways to acheive that.

Update bootstrap test following pcmanus/ccm#557

---

auth_test.py

auth_test:TestAuth.system_auth_ks_is_alterable_test can be flaky due to
the client session attempting to reconnect while the cluster is being
restarted. Because it uses the 'cassandra' user, reads to the auth
tables are made a QUORUM & so may fail if nodes are marked down.

Remove potential reconnection error from auth_test

---

offline_tools_test.py
upgrade_internal_auth_test.py

The annotation in `upgrade_internal_auth_test` fixes CASSANDRA-12986, as upgrading from 2.1 -> 4.0 is not supported.
`offline_tools_test` has also been failing recently for similar reasons, but I couldn't find a JIRA for that.

Add max version for tests which shouldn't run for 4.0+

---

bootstrap_test.py
cdc_test.py
commitlog_test.py
compaction_test.py
concurrent_schema_changes_test.py
cql_tests.py
dtest.py
materialized_views_test.py
metadata_tests.py
offline_tools_test.py
pushed_notifications_test.py
putget_test.py
rebuild_test.py
repair_tests/incremental_repair_test.py
replace_address_test.py
requirements.txt
sstable_generation_loading_test.py
sstablesplit_test.py
sstableutil_test.py
super_column_cache_test.py
super_counter_test.py
thrift_hsha_test.py
thrift_tests.py
write_failures_test.py

This is the changes required on 4.0/trunk now that CASSANDRA-11115 has been committed and basically consists at skipping anything thrift related on 4.0. This depends on a https://github.com/pcmanus/ccm/pull/566, but once that's been committed, we should remove/revert the commit named "Point to modified ccm repo".

Thrift removal tests

---

cql_tests.py

I saw a test fail to connect at this line, although I can no longer reproduce it I think it's safer to use `patient_cql_connection`.

Use patient connection to avoid flakiness

---

upgrade_tests/storage_engine_upgrade_test.py

These are for testing 2.1 -> post-8099, and thus there's no need
to run on 4.0. We don't support upgrades to 4.x from 2.1
@beobal or @pauloricardomg  to review

Don't run storage upgrade tests on 4.0+

---

materialized_views_test.py

This restores the original behavior of `base_replica_repair_test` pre-CASSANDRA-12905, by only setting jvm parameters when `fail_mv_lock=True`.

Fix for CASSANDRA-13056

---

auth_test.py
dtest.py
paging_test.py
requirements.txt
secondary_indexes_test.py

Update requirements.txt to use version 2.4.8 of ccm, remove wait_for_any_log function definition, and replace all usages of wait_for_any_log with ccm version.

Update dtest to use new ccm 'wait_for_any_log' function

---

snitch_test.py

This test adds test coverage for DES in multi-datacenter situations.
It does this by populating scores for the local datacenter and ensuring that read metrics are not incremented on the degraded host when doing local quorum reads.
A [multiplexer run](http://cassci.datastax.com/job/parameterized_dtest_multiplexer/374/) shows this passing 90 times when the patches for CASSANDRA-13074 are applied. This should not be merged until CASSANDRA-13074 has been merged.

Add test that DES works in multi-datacenter situations (CASSANDRA-13074)

---

bootstrap_test.py
topology_test.py

These tests were recently changed to alter the system_distributed keyspace. This keyspace doesn't exist on 2.1, so that operation will always fail.

Don't try to alter system_distributed keyspace on 2.1

---

INSTALL.md

Because I always have to start looking at the code how to run those tests... :eyes:

Add run_dtest.py usage example for disabled vnodes

---

disk_balance_test.py

It does not make sense to have the allocate_tokens_for_keyspace, because the keyspace is not created at cluster start time yet.
And it will break the test after CASSANDRA-13080.

remove the allocate_tokens_for_keyspace in disk_balance_test

---

read_failures_test.py

The `read_failures_test.TestReadFailures.test_tombstone_failure_v3` test is now [failing for months](http://cassci.datastax.com/job/cassandra-2.1_dtest/lastCompletedBuild/testReport/read_failures_test/TestReadFailures/test_tombstone_failure_v3/) for 2.1. The reason for this seems to be that the expected `ReadTimeout` is actually wrapped in `OperationTimedOut` due to the retry semantics at work. One option would be either to disable retries by using FallthroughPolicy, or, as in the PR, to unwrap the error.

Fix test_tombstone_failure_v3 error handling for 2.1

---

upgrade_tests/cql_tests.py

CASSANDRA-12694 did slightly change the behavior in that case (for the
better) and updated unit tests accordingly (see the end of
https://github.com/ifesdjeen/cassandra/commit/3b7a2f8479eaafa00d55466fe37e43318b8dadcf,
which is "exactly" the same case) but this upgrade test was missed and
currently fails
(http://cassci.datastax.com/job/cassandra-3.0_dtest_upgrade/lastBuild/testReport/junit/upgrade_tests.cql_tests/TestCQLNodes2RF1_Upgrade_current_3_0_x_To_indev_3_0_x/static_columns_cas_test/).

Update upgrade test post-CASSANDRA-12694

---

secondary_indexes_test.py
upgrade_tests/cql_tests.py

So this is just a first attempt at CSTAR-665. If this is the proper way to rename these tests, I will continue forward renaming the rest of them.

Rename {{bug_\d+}} tests

---

compaction_test.py

Solves https://issues.apache.org/jira/browse/CASSANDRA-13170
The reason for [the test](https://github.com/riptano/cassandra-dtest/blob/master/compaction_test.py#L280) to fail is that 5mb threshold is compared against the first matched `avgthroughput` without unit conversion. In the [node_debug.log](https://issues.apache.org/jira/secure/attachment/12850004/node1_debug.log) attached in the ticket, the threshold was compared against `6.175KiB/s`

Convert avg compaction throughput to mbs before compaing to threshold

---

hintedhandoff_test.py
requirements.txt

This test is broken on trunk after [CASSANDRA-12510](https://issues.apache.org/jira/browse/CASSANDRA-12510), so we need to use the `--force` flag to allow decommission to happen (dropping below RF is not relevant since we just want to make sure hints are being delivered on this test).

Use decommission --force on hintedhandoff_decom_test

---

replace_address_test.py

@ptnapoleon to review please. This is for cs690. I could only find one place where `assertRaises` was used in `replace_address_test`. I am assuming the other mention of its use in the JIRA ticket has since been removed or changed.

Use "multi-catch" `assertRaises` call in `replace_address_test` and elsewhere

---

requirements.txt

@mshuler to review
Testing CI here: http://cassci.datastax.com/view/Dev/view/ptnapoleon/job/ptnapoleon-test-upgrade-dtest/1/console
(shouldnt be a serious change, is outside of the path of regular dtest usage)

Use ccm 2.6.0

---

jmx_test.py

The netstats_test in jmx_test.py recently started failing in CI on all branches. This is because Java 1.8u111 changed the details of a ConnectException thrown from native code. I scanned for other tests failing in similar ways and didn't notice any.
I checked the patched test on 2.1+ both pre- and post-1.8u111.

Fix netstats_test

---

offline_tools_test.py

sstabledump test assumes only one SSTable to be written, but in JBOD config multiple SSTables.
This patch strictly set to use only 1 data directory to avoid error.

Restrict data dir for sstabledump test

---

repair_tests/deprecated_repair_test.py

[CASSANDRA-11530](https://issues.apache.org/jira/browse/CASSANDRA-11530) removes deprecated methods, so once it is committed, we need to patch `deprecated_repair_test` to have max version.

set max_version since deprecated repair methods are removed in 4.0

---

repair_tests/repair_test.py

Simple fix for [no_anticompaction_of_already_repaired_test](http://cassci.datastax.com/view/cassandra-3.11/job/cassandra-3.11_novnode_dtest/38/testReport/repair_tests.repair_test/TestRepair/no_anticompaction_of_already_repaired_test/history/), which is failing only on 3.11 due to JBOD (test is disabled on trunk).

Restrict data dir for no_anticompaction_of_already_repaired_test

---

repair_tests/incremental_repair_test.py

With CASSANDRA-13257 committed, we can easily validate that all repaired data is in sync, so I've added some tests that verify everything looks ok after cluster reconfigurations.

adding cluster reconfiguration tests for 9143

---

sstableutil_test.py

My best guess at the moment is because directly after we call `node.compact()` we instantly compare files. `_check_files` looks at the directory first and then invokes `SSTableUtil`, and then compares the output of them both. The (still existing) old generation SSTables is what the differences in the list are. This commit only introduces a small sleep to give compaction time to actually cleanup the files before we check the directory. 
Previously this test failed some 12 times in the last 30 runs, I've re-run it 45 times and still have yet to get an error, so I think this would fix it or at worse, make it less flaky.

Add a sleep after compaction to give it time before checking SSTable directory for files (CASSANDRA-13182)

---

sslnodetonode_test.py

we have tests to prove that the TLS hostname verification fails or is ignored, but no positive test to prove that it actually works.

add test to confirm that hostname validation is working

---

hintedhandoff_test.py

This test currently fails on versions < 4.0, since it was introduced for CASSANDRA-11720, which only went into 4.0+

Hinted handoff setmaxwindow test should only run on versions >= 4.0

---

requirements.txt

2.6.3 brings in several improvements over 2.6.0 that may increase reliability in some environments.

Bump CCM version to 2.6.3

---

repair_tests/preview_repair_test.py

These tests were added for [CASSANDRA-13257](https://issues.apache.org/jira/browse/CASSANDRA-13257), which is 4.0+ only. We should restrict them to only run on supported versions.

Repair preview tests should only run on 4.0+

---

topology_test.py

This test was introduced for [CASSANDRA-9639](https://issues.apache.org/jira/browse/CASSANDRA-9639), which only went into 3.0.11+. As I understand it, we do not expect the behavior described by this test to occur on 2.1 and 2.2 branches.
Ping @pauloricardomg to verify what I'm saying re: 2.1, 2.2, since I'm not completely certain.

Restrict size estimates multi-dc test to run on 3.0.11+

---

topology_test.py

This has been failing since [CASSANDRA-12510](https://issues.apache.org/jira/browse/CASSANDRA-12510) was committed. It's safe to force here, so we force on versions 4.0+.
AFAICT, there's no reason this shouldn't run on vnodes. I removed the no_vnodes annotation and tested on 3.0, 3.11, and trunk, which are the only branches where this will run.

Force decommission on topology test where required on 4.0+, run with vnodes

---

batch_test.py

@stef1927 to review. These tests do _not_ pass on 3.11. I am actually not sure why? There are errors reading sstables after the upgrade, but this upgrade path is supported and tested. Stefania, hopefully you know why these were restricted to only 3.0.x originally, which may also explain the failures.

Expand 9673 tests to also run on 3.x

---

jmx_test.py
nodetool_test.py

Tests for the 'nodetool getbatchlogreplaythrottle' and 'nodetool setbatchlogreplaythrottle' commands added at [CASSANDRA-13614](https://issues.apache.org/jira/browse/CASSANDRA-13614)

Add tests for 'nodetool getbatchlogreplaythrottle' and 'nodetool setbatchlogreplaythrottle'

---

jmx_test.py
tools/jmxutils.py

I've optionally made the JMX querying accept a `verbose` flag because the nosetest would print out all stacktraces otherwise...and finally end with an 'OK'. 
Any feedback/comments welcome (Or if you'd rather a patch etc.)

Add a test for CASSANDRA-13346
