riptano/cassandra-dtest

auth_roles_test.py, auth_test.py, pytools.py
@beobal Are these ready to merge? Should I close #76 as out of date?
=> CASSANDRA-7653

paxos_tests.py
=> Fixes #151. Testing for CASSANDRA-8640

nodetool_test.py
=> Add test for CASSANDRA-8716

sstablesplit_test.py
Add sstablesplit test for CASSANDRA-8623
=> Add sstablesplit test for CASSANDRA-8623

auth_roles_test.py, auth_test.py
Build on the changes in https://github.com/riptano/cassandra-dtest/pull/173
=> Additional test for CASSANDRA-8849

prepared_statements_test.py, pushed_notifications_test.py
Additional tests for cassandra-7875 and cassandra 7816, one fix for test of cassandra-8516
=> Additional tests

auth_roles_test.py
Require WITH & AND for multiple role options - CASSANDRA-8850
=> Clean up CREATE|ALTER ROLE syntax

incremental_repair_test.py
=> Add test for CASSANDRA-8366

bootstrap_test.py, replace_address_test.py, tools.py
[CASSANDRA-8838](https://issues.apache.org/jira/browse/CASSANDRA-8838) introduced new feature around bootstrappping/replace node.
Tests are added to verify its functionality.
=> tests for CASSANDRA-8838

scrub_test.py
These are the tests for [CASSANDRA-5174](https://issues.apache.org/jira/browse/CASSANDRA-5174).
As I am a python novice, please don't shy away from style comments in the code review.
Thanks!
=> Tests for CASSANDRA-5174

pushed_notifications_test.py
I fixed a bug that caused an unnecessary wait till timeout was up in restart_node_test(), CASSANDRA-7816.
I also added the JIRA label to the two tests, to avoid confusion.
=> CASSANDRA-7816 - restart_node_test() - bug fix

super_counter_test.py
Done as part of the work for CASSANDRA-8996 to get dtests passing on
trunk.
=> Fix super_counter_test.py on trunk

bootstrap_test.py, replace_address_test.py
Change in [CASSANDRA-8942](https://issues.apache.org/jira/browse/CASSANDRA-8942) allows bootstrapping node to stay up when bootstrap failed, so we need to change tests added in CASSANDRA-8834(#199).
=> Modify test for CASSANDRA-8942

consistency_test.py
@pcmanus This test passes on both 2.1-head and trunk. Is there something wrong with the test logic, that isn't exposing the error?
=> Add test for CASSANDRA-8933

conf/cassandra-2.0_test-select.cfg, conf/cassandra-2.1_test-select.cfg, conf/trunk_test-select.cfg, validation.py
I already excluded the new file from jenkins. Does just basic data loss validation. A good prototype to discuss what we want this harness to look like long term. 
As is, there is going to be far far too much log parsing for errors. If the harness is going to be in Python, then changes need to be made in stress so the harness can get simple error codes returned.
=> CASSANDRA-9007

cql_tests.py
=> Port cql_tests.rename_test from CLI to thrift client

cql_tests.py
=> Port cql_test.TestCQL.cql3_insert_thrift_test from CLI to Thrift API

super_column_cache_test.py
=> Port super column cache test from CLI to Thrift API

upgrade_supercolumns_test.py
=> Port upgrade_supercolumns_test from CLI to Thrift API

repair_test.py
`repair_test.py` should test both sequential and parallel repair.
3.0(trunk) changes default to parallel, and in fact, I found a bug only happens in parallel repair.
Also, 3.0 defaults to incremental repair but we now have `inceremental_repair_test.py`, `repair_test.py` should stick to test only 'full' repairs.
=> repair_test should test both sequential and parallel repair

scrub_test.py
The existing code only worked correctly when a single sstable existed.
For example, if the existing generations were [1, 2], it would increment
them to [2, 3].  The correct behavior is to go to [3, 4].
This fixes the sometimes failing `scrub_test.TestScrub.test_standalone_scrub`
=> Fix the increment of sstable generation numbers

upgrade_supercolumns_test.py
The test is typically failing against 2.0 because the thrift connection
is being opened before the RPC server has started.  I also saw failures
due to querying the new tables before there was schema agreement, so I
added a check for that.
=> Properly wait for RPC server to start, schema agreement

dtest.py
Getting errors in CI due to having a handle open when we attempt to delete. Trivial patch to resolve that.
=> Delete last test dir after closing file handle.

upgrade_through_versions_test.py
just adds a test to check that select count(*) is returning the right count
=> Countupdatetest

cqlsh_tests.py
These aren't comprehensive tests, but they add basic coverage. I used the titles of the stubbed [cqlsh parsing tests in C* trunk](https://github.com/apache/cassandra/blob/trunk/pylib/cqlshlib/test/test_cql_parsing.py) as a starting point.
I may have found a bug in pre-trunk releases with [CREATE INDEX](https://github.com/riptano/cassandra-dtest/blob/b712395bc318ab41b26762ba395e3866ac36f4be/cqlsh_tests.py#L749) and [DROP INDEX](https://github.com/riptano/cassandra-dtest/blob/b712395bc318ab41b26762ba395e3866ac36f4be/cqlsh_tests.py#L776) handling. I think they may just be bugs in the cqlsh parser. I've marked the tests for these statements `@since('3.0')` until I can isolate the bug.
Pinging @thobbs in case he wants to have a look.
=> Adds smoke tests for cqlsh

auth_test.py
This test doesn't work with current trunk, and its coverage is
superceded by the new tests in auth_roles_test from CASSANDRA-7557.
=> Remove broken func_auth_test

bootstrap_test.py
Stress was not being used correctly for validation of the data, and it's easy to validate the data normally through CQL.
This fixes the failing ``manual_bootstrap_test()``.
=> Validate data through CQL query, not stress

sstablelist_test.py, tools.py
We've introduced a new standalone tool (sstablelister) for CASSANDRA-7066 and these are some basic tests for it.
=> Tests for CASSANDRA-7066 (standalone sstablelister)

bootstrap_test.py
Add test for local quorum queries while a node is bootstrapping
=> Add test for local quorum queries while a node is bootstrapping

token_generator.py
=> Add token-generator dtest

paging_test.py
300 was triggering inside system tables
Fixes #265 
@knifewine to review
=> Increase TOE threshold from 300 to 500

paging_test.py
@knifewine and @aboudreault to review
see CASSANDRA-9299
=> Update test for 9299

scrub_test.py
This breaks up the sstable generation incrementing process to work on
each table (or index) individually instead of all at once.  When all
sstables were worked on at once, if a single table/index had a
generation that the others did not, the incrementing process would
over-increment those other tables.
=> Fix periodic scrub test failures

compaction_test.py
`dtcs_deletion_test` still fails on 2.0. I think this is due to [a `ccm` bug](https://github.com/pcmanus/ccm/issues/284). When I change [this line](https://github.com/pcmanus/ccm/blob/master/ccmlib/node.py#L843) so the glob is just the table name, `dtcs_deletion_test` passes. 
Other than that, all tests pass on 2.0, 2.1, and trunk.
Closes #263.
=> fix compaction_tests on 2.0

auth_roles_test.py, user_functions_test.py
adopt dtests for CASSANDRA-9404 + CASSANDRA-8374
=> Add enable_user_defined_functions:true + fixes for UDF/null

tools.py
re: the discussion in #282: I think regexes are a good fit here. The implementation is pretty simple, the functionality subsumes an `*args`-based approach, and the behavior safely falls back to the way it was before, where it just did case-insensitive string matching, if you just don't use regex escape chars.
closes #282.
=> makes @require work with regex argument

bootstrap_test.py
The test has been failing because the ``intial_token`` was not being
properly set, and with 32 random tokens there was some variation in the
data distribution.
The root of the problem is that when ``DISABLE_VNODES=false``, the
cluster-level config sets ``{'initial_token': None}``.  In ccm, the cluster
(and node-level) config options are applied _after_ ``self.initial_token``,
and ``self.initial_token`` is not actually in the node-level config.  The
result was that no initial_token was being set.  It seems like this
should be improved in ccm, but in the meantime, this is a simple fix for
the tests.
=> Fix initial_token for simple_bootstrap_test

tools.py
`unittest.skip` doesn't have that kwarg!
=> fixes kwarg passed to unittest.skip()

deletion_test.py, index_summary_upgrade_test.py, jmxutils.py
This is a workaround for https://github.com/rhuss/jolokia/issues/198
=> Adjust JVM options to fix Jolokia agent problems

cqlsh_tests/cqlsh_tests.py
These are the tests for [CASSANDRA-9399] (https://issues.apache.org/jira/browse/CASSANDRA-9399), which was committed yesterday.
=> Tests for CASSANDRA-9399

repair_test.py
CASSANDRA-9842 was fixed, but the check for the parent repair history table is still failing, so we skip just that test and let the other tests run.
This also simplifies the tests by removing a parameterized test and the resulting indirection.
=> simplifies repair table tests and changes require

read_repair_test.py
dtest for "Reading from table which contains collection type using token function and with CL > ONE causes overwhelming writes to replicas" (CASSANDRA-8989)
=> dtest for 8989 & 9502

largecolumn_test.py
Patch by @aweisberg. Looking for review from @mambocab.
Ariel, this test fails currently. Does it pass with your proposed patch for CASSANDRA-8670?
=> Add test for CASSANDRA-8670

offline_tools_test.py, sstablelist_test.py
I had to change offline tools to cope with the new way to discover temporary files or else it will fail after CASSANDRA-7066 is committed. It will work even if 7066 is not yet committed.
=> CASSANDRA-7066, changes for tmp files in offline tools 

repair_test.py
For [CASSANDRA-9521](https://issues.apache.org/jira/browse/CASSANDRA-9521) and part of [CASSANDRA-9109](https://issues.apache.org/jira/browse/CASSANDRA-9109).
=> Add multiple dc repair tests

thrift_hsha_test.py
Quick little improvement -- adds some Doxygen metadata to the thrift HSHA tests.
=> adds metadata to thrift_hsha_test tests

scrub_test.py
I have added two basic scrub tests, one for nodetool and one for standalone scrubbing. We already had some tests but they only run for >= 2.2 because scrubbing of secondary indexes is only available in 2.2. There is a test called test_nodetool_scrub() which runs since 2.1 but it doesn't seem to check much.
I have also added a test for [CASSANDRA-9591] (https://issues.apache.org/jira/browse/CASSANDRA-9591).
=> Adding basic scrub tests for versions 2.0 and 2.1 and one test for CASSANDRA-9591

consistency_test.py
There are the tests for [CASSANDRA-9102] (https://issues.apache.org/jira/browse/CASSANDRA-9102) : Consistency levels such as non-local quorum need better tests.
=> New consistency tests introduced by CASSANDRA-9102

README.md
This is some stuff that trips people up but isn't written down anywhere. Is CONTRIBUTING the right place for it? Maybe the README is better; I feel like most people who look at this also contribute tests, and they may be more likely to read the README. Though, this does only pertain to contributing. I'm 100% ambivalent.
=> add uncodified knowledge to CONTRIBUTING

consistency_test.py
Fix for consistency_test.py, CASSANDRA-9102
=> Use exclusive connections in TestAvailability

upgrade_internal_auth_test.py
=> 7653 with upgrade test

consistency_test.py, hintedhandoff_test.py, tools.py
These are some basic hinted handoff tests, for CASSANDRA-9035.
=> Tests for CASSANDRA-9035

cqlsh_tests/cqlsh_tests.py
Some tests I wrote quite some time ago for CASSANDRA-7814, but never merged.
=> Tests for CASSANDRA-7814

cql_tests.py
=> Remove unused imports after PR for C*-9160

jmxmetrics_test.py
Test to see whether JMX changes as you'd expect it to after running C*.
=> Test to check JMX metrics

CONTRIBUTING.md
Add notice that we now lint all new contributions.
=> Stop telling lies about PEP-8.

cqlsh_tests/cqlsh_tests.py
This tests for the bug described in CASSANDRA-9064. It will probably be superseded at some point by CVH, but for the moment it'll be helpful.
Review this in separate commits -- the 2 most recent commits are whitespace fixes and import sorting. I've run the tests locally and they still pass, so I don't think I screwed anything up in fixing whitespace.
=> DESCRIBE TABLE -> CREATE TABLE round trip

write_failures_test.py
These are the tests for [CASSANDRA-8592](https://issues.apache.org/jira/browse/CASSANDRA-8592), but you need to wait for [PYTHON-238](https://datastax-oss.atlassian.net/browse/PYTHON-238) to be available before you can merge them.
=> Tests for cassandra 8592

compaction_test.py
A test for [CASSANDRA-9643] (https://issues.apache.org/jira/browse/CASSANDRA-9643)
=> Test for CASSANDRA-9643

CONTRIBUTING.md
This is follow up for [a comment I left on a PR today](https://github.com/riptano/cassandra-dtest/pull/371#discussion_r34169469). Related to #84.
=> adds information on py3 division to CONTRIBUTING

cql_tests.py
Some tests to check that we can abort queries when they are already in progress, CASSANDRA-7392.
=> Tests for CASSANDRA-7392

upgrade_internal_auth_test.py
No reason there should be problems here; I filed the PR for accountability via Travis.
=> Skip failing upgrade test

configuration_test.py, cqlsh_tests/cqlsh_tests.py, user_types_test.py
Removes the existing FIXME. Review, but don't merge. I'm checking with Aleksey to make sure I'm fixing this the way he wanted before I do the rest of the tests. It seems wrong since it's more verbose, and I'm still specifying the keyspace/table names.
=> Use python driver metadata api

snapshot_test.py
... until we can fix them with a solution to #393.
=> Skip snapshot tests

paxos_tests.py
addresses #389. Can you review, @ptnapoleon?
=> documents purpose of replica_availability_test

sstablesplit_test.py
The sstable_split test was a bit of a mess, so I cleaned it up and added some comments. @pcmanus sorry to ask you to re-review, but could you please look this over?
=> make sstablesplit_test changes more readable

bootstrap_test.py, tools.py
A new test for CASSANDRA-9765.
=> Test for CASSANDRA-9765

consistency_test.py
I've added a loop to try and catch the NPE of CASSANDRA-9460 more frequently.
=> Modified existing test to make it more likely to reproduce CASSANDRA-9460

cqlsh_tests/cqlsh_copy_tests.py, cqlsh_tests/cqlsh_tools.py
=> test fixes

cqlsh_tests/cqlsh_copy_tests.py, cqlsh_tests/cqlsh_tests.py, cqlsh_tests/cqlsh_tools.py
@mambocab to review.
Also fixes Travis complaints
=> Clean up Jake's PR

auth_roles_test.py, offline_tools_test.py, replace_address_test.py, replication_test.py, schema_test.py, secondary_indexes_test.py, sstable_generation_loading_test.py, sstablelist_test.py, sstablesplit_test.py, super_counter_test.py, thrift_hsha_test.py, thrift_tests.py, token_generator.py, topology_test.py, upgrade_through_versions_test.py, user_types_test.py, validation_test.py, wide_rows_test.py
=> Fix PEP-8 Violations

linter_check.sh
A convenient script to ensure our changes will pass on travis.
=> Add linter_check.sh

auth_roles_test.py, user_functions_test.py
https://issues.apache.org/jira/browse/CASSANDRA-9889
=> patch for CASSANDRA-9889

auth_roles_test.py, user_functions_test.py
Reverts riptano/cassandra-dtest#417
=> Revert "patch for CASSANDRA-9889"

user_functions_test.py
Just noticed a couple things to clean up while I was reviewing the PRs I missed.
=> Post vacation cleanup

consistent_bootstrap_test.py
=> Style fixes

auth_roles_test.py, user_functions_test.py
Reverts riptano/cassandra-dtest#418
=> Revert "Revert "patch for CASSANDRA-9889""

bootstrap_test.py, replace_address_test.py
A simple test for CASSANDRA-9871.
=> Test for CASSANDRA-9871

incremental_repair_test.py
more details on https://issues.apache.org/jira/browse/CASSANDRA-9983
=> made multiple_subsequent_repair_test less agressive

cqlsh_tests/cqlsh_tests.py
Test for https://issues.apache.org/jira/browse/CASSANDRA-10000 (not committed yet).
=> Test retrieving dates in the far future and far past with cqlsh

schema_metadata_test.py, upgrade_through_versions_test.py
…ariants to schema test -  CASSANDRA-6717
=> adding additional schema migration tests

INSTALL.md, snapshot_test.py, tools.py
Depends on [CASSANDRA-9897](https://issues.apache.org/jira/browse/CASSANDRA-9897)
=> Fix bad file separator on Windows

cqlsh_tests/cqlsh_copy_tests.py
We need to use NamedTemporaryFile(delete=False) on Windows to prevent
access violations. Also cleaned up CqlshCopyTester.tearDown logic on
Windows and for calling super.tearDown in general.
=> Further fix cqlsh_copy_tests on Windows

rebuild_test.py
This removes the test's dependence on the outcome of a race. Occasionally, the call to `nodetool rebuild` in the main thread would start before the one in the secondary thread, making the call in the secondary thread fail instead of the one in the main thread. The failure is correct -- a `nodetool rebuild` call should fail if another is running. However, the test only expected failure in the main thread. It led to failures like this:
http://cassci.datastax.com/view/trunk/job/trunk_dtest/470/testReport/junit/rebuild_test/TestRebuild/simple_rebuild_test/
where the command in the thread clearly (correctly) failed, but the test didn't pass. It led to 4 failures over the course of the past few days:
http://cassci.datastax.com/view/trunk/job/trunk_dtest/lastCompletedBuild/testReport/rebuild_test …
=> fixes occasional failures in simple_rebuild_test

batch_test.py, materialized_views_test.py
Validation tests for gc_grace_seconds on logged batches and materialized views
=> Tests for CASSANDRA-9917

batch_test.py, materialized_views_test.py
Reverts riptano/cassandra-dtest#464
I jumped the gun again.
=> Revert "Tests for CASSANDRA-9917"

offline_tools_test.py
requires this: https://github.com/pcmanus/ccm/pull/350
=> add sstableexpiredblockers test

schema_metadata_test.py
this was branched off another pull request -- these additional tests fail due work still going on in for c*3.0
=> additional schema tests - cassandra-6717

upgrade_tests/cql_tests.py, upgrade_tests/paging_test.py, upgrade_tests/upgrade_base.py
Moved PR #471 here so that we can edit the branch more easily. Will set up a cassci job for these tests.
=> Backwards compat

hintedhandoff_test.py
=> make linesep comparison os agnostic in hintedhandoff_test.py'

consistency_test.py, consistent_bootstrap_test.py, cqlsh_tests/cqlsh_tests.py, deprecated_repair_test.py, hintedhandoff_test.py, incremental_repair_test.py, putget_test.py, rebuild_test.py, repair_test.py, tools.py, topology_test.py
Fixes #488.
@mambocab and @josh-mckenzie  to review
=> Refactor insert_c1c2 to use execute_concurrent

cqlsh_tests/cqlsh_tests.py
A test to check that we can describe tables whose name is a non-reserved CQL keyword. It requires the patch from CASSANDRA-9232.
=> Test for CASSANDRA-9232

cqlsh_tests/cqlsh_tests.py, cqlsh_tests/glass.cql
=> Add source_glass test, refactor glass tests

batch_test.py
Also some PEP8 and import changes
@mambocab to look over
I checked, all the tests still pass.
=> Use better formatting and asserts in batch_test.py

dtest.py
Breakout logic to find highest protocol version
@knifewine you closed #486, but I still think this refactoring needed done, and will be useful. Can you review? Thanks
=> Refactor _create_session

materialized_views_test.py
Tests need to be validated before on https://issues.apache.org/jira/browse/CASSANDRA-10171
=> Fixed materialized view tests in the context of CASSANDRA-10171

bootstrap_test.py
Set log level to TRACE for debugging CASSANDRA-10205.
=> C*-10205 debug: set log level before populating

commitlog_test.py
This PR makes the commitlog segment size tests more deterministic, as discussed on [CASSANDRA-10098](https://issues.apache.org/jira/browse/CASSANDRA-10098)
Since the main objective of these tests is to verify that the `commitlog_segment_size_in_mb` property is respected, I removed the checks for number of commit log files and total commit log size, since these may greatly vary on different test runs, environments, cassandra versions and compression settings, so there's a lot of variation. There are other tests that test commit log integrity, so I don't think it's crucial to test these attributes on these tests.
Since compressed commit log segment sizes may also vary depending on different factors, I modified the test to check that the compressed commit log segment size is within …
=> Make commit log segment size tests more deterministic (CASSANDRA-10098)

nodetool_test.py
=> Test for CASSANDRA-8741

cqlsh_tests/cqlsh_tests.py
Tests for [CASSANDRA-9689](https://issues.apache.org/jira/browse/CASSANDRA-9689)
=> Added TestCqlsh.test_refresh_schema_on_timeout_error (CASSANDRA-9689)

dtest.py, native_transport_ssl_test.py
Do not merge before ticket has been commited.
=> Test for CASSANDRA-9590

upgrade_tests/upgrade_base.py
in mixed version cluster.
@josh-mckenzie to review
=> Ignore 2.1 errors on non-upgraded node

dtest.py
=> Never use the thrift port.

batch_test.py, tools.py
Tests for batched logs and mixed version clusters (CASSANDRA-9673).
=> Test for CASSANDRA-9673

commit_log_test.py
This cleans up #375 for merging. @bdeggleston can you review my changes please? In particular, I'd like confirmation that my new assertion logic is correct. Thanks again for these tests!
@ptnapoleon can you review as well?
=> CASSANDRA-9749 cleanup

cqlsh_tests/cqlsh_tests.py
A very simple test that would have caught CASSANDRA-10272.
=> Test for CASSANDRA-10272

cqlsh_tests/cqlsh_tests.py
@mambocab to review.
PS, if you think this is readable, you are wrong.
=> Add test for C-10066

upgrade_tests/upgrade_base.py
The upgrade code should handle the protocol_version being None.
=> checks for default protocol_version value

cql_tests.py
The log message format has changed, I fixed a bug with join_ring and there are some new queries.
=> Some changes to the tests for CASSANDRA-7392

materialized_views_test.py
=> Indexes are disallowed on materialized views

cqlsh_tests/cqlsh_tests.py, pushed_notifications_test.py
I created two tests for CASSANDRA-9961, to describe materialized views in cqlsh.
=> Tests for CASSANDRA-9961

materialized_views_test.py
https://issues.apache.org/jira/browse/CASSANDRA-9664
to review, do not merge until the patch is committed.
=> Add complex_mv_statements_test

cqlsh_tests/cqlsh_copy_tests.py
=> fixed encoding so utf8 string works, hacked around issues with bytearray

pushed_notifications_test.py
=> unrequire CASSANDRA-10052 tests

compaction_test.py
Fix for CASSANDRA-10463.
This change depends on ccm change here(https://github.com/pcmanus/ccm/pull/386).
=> Watch debug.log for compaction logs

INSTALL.md
I don't know a good way to phrase this without a long explanation of what's going on here. Requesting feedback/edits from @ptnapoleon and feedback from @spodkowinski if you're so inclined.
=> driver version doc

sstableutil_test.py
sstableutil_test.py is still failing on Jenkins, I need to add an extra debug call to see why.
=> CASSANDRA-10461: add extra logging

jmx_test.py
=> Add test for CASSANDRA-10504

paging_test.py
DTest changes for CASSANDRA-10381
=> Add tests for paging with only static columns containing data

upgrade_tests/paging_test.py
Filing a PR for this so Travis picks it up.
=> fix linter errors in upgrade_tests/paging_test.py

tools.py
This should address the problem @blerer mentioned here:
https://github.com/riptano/cassandra-dtest/pull/602#issuecomment-149192018
I've run this in a `git`-less environement on my machine and it seems to work there. @blerer can you confirm? Sorry for merging #602 before this was ready.
=> fix nonsensical behavior in gitless env

thrift_tests.py
This current fails on cassandra-3.0 branch.
=> Add test for thrift accessing a compact storage created table.

thrift_tests.py
=> Extend testing of create/alter ks metadata over thrift

secondary_indexes_test.py
=> Better checking of system.IndexInfo when rebuiling indexes

topology_test.py
Also added a test for related issue CASSANDRA-9034.
=> Tests for CASSANDRA-9912

consistency_test.py
=> Add test for EACH_QUORUM reads

cqlsh_tests/cqlsh_copy_tests.py
A simple test for COPY TO WITH TIMEFORMAT
=> Regression test for CASSANDRA-10633

schema_metadata_test.py
Ticket URL: https://issues.apache.org/jira/browse/CASSANDRA-10650
=> Update dtest for C* ticket

batch_test.py
=> Skip unsupported 2.1 batch upgrade tests on Win

bootstrap_test.py, hintedhandoff_test.py, materialized_views_test.py, secondary_indexes_test.py, thrift_tests.py
=> Make some pep8 fixes

repair_test.py
=> Cleanup repair test

cqlsh_tests/cqlsh_copy_tests.py
A simple test for CASSANDRA-9494, it verifies COPY FROM with the TTL option.
=> Test for CASSANDRA-9494

cqlsh_tests/cqlsh_copy_tests.py
CASSANDRA-9043: Add test case for COPY from COUNTER csv
=> CASSANDRA-9043: Add test case for COPY from COUNTER csv

secondary_indexes_test.py
CASSANDRA-8505 is changing the behaviour when an index is building. If an index is not fully built, it will throw an error when it is queried. The patch makes the test wait until the index is built.
=> Make sure that the index is built before using it (CASSANDRA-8505)

cqlsh_tests/cqlsh_copy_tests.py
Three more tests for CASSANDRA-9302, with failure injection.
=> 9302: tests with failure injection

replication_test.py
=> Testing rack swapping

replication_test.py
Reverts riptano/cassandra-dtest#605. Mistakenly merged instead of a similar PR.
=> Revert "Testing rack swapping"

cqlsh_tests/cqlsh_tests.py, replication_test.py, thrift_tests.py, topology_test.py
I was taking a look at ccm's code with a checking tool I wrote (similar to pyflakes) that helped me prepare some PEP8, pylint and indentation fixes.
I did read the contributing guidelines and I hope to have followed them accordingly.
=> PEP8 Fixes

replication_test.py
Reverts riptano/cassandra-dtest#688
=> Revert "Fixes to replication_test.py for CASSANDRA-10243"

compaction_test.py
@mambocab to review. I broke this in the first place.
=> Check for correct log message on 2.1

repair_test.py
=> replicate to all nodes to make tests pass without vnodes

replication_test.py
I still have to check with a dev that this change is intentional, but it definitely doesn't seem accidental.
=> Adjust expected trace output

pending_range_test.py
@mambocab and @blambov, I am following the repro steps laid out on https://issues.apache.org/jira/browse/CASSANDRA-10887 , but I can't seem to repro with this test. Do you see any issues?
=> Add test for CASSANDRA-10887

cqlsh_tests/cqlsh_copy_tests.py
Two tests for CASSANDRA-10854, I did not use `@require` since the ticket is already in status `ready to commit` so you may want to wait until the ticket is committed before merging or I can merge myself once I have your +1 and the ticket is committed.
=> Tests for CASSANDRA-10854

jmxutils.py
=> Disable PerfDisableSharedMem in jvm.options instead of cassandra-env

cqlsh_tests/cqlsh_copy_tests.py
This should fix CASSANDRA-10858.
=> 10858: test_copy_to_with_more_failures_than_max_attempts is failing

jmxutils.py
This reverts commit 5bfc5937c931998918a62a896a7bbc575c4d439c.
Do not merge until 10494 is merged.
=> Revert "Totally undo changes for 10494. Revert once that is committed."

thrift_hsha_test.py
These changes are to help with CASSANDRA-10863 and CASSANDRA-10879
=> Use jmx instead of lsof

nodetool_test.py
=> Add tests for nodetool get/settimeout commands

auth_test.py
@mambocab Review please, and thanks.
=> Hard refresh schema metadata before checking it

cqlsh_tests/cqlsh_tests.py
Depends on commit for CASSANDRA-10686 with new `--request-timeout` option.
=> Fix for CASSANDRA-10686

conf/cassandra-1.2_test-select.cfg, conf/cassandra-2.0_test-select.cfg, conf/cassandra-2.1_fast-select.cfg, conf/cassandra-2.1_test-select.cfg, conf/cassandra-2.2_fast-select.cfg, conf/cassandra-2.2_test-select.cfg, conf/trunk_test-select.cfg
@mshuler to check that I'm sane
=> updage cfg's to remove redundant upgrade excludes

cqlsh_tests/cqlsh_copy_tests.py, cqlsh_tests/cqlsh_tests.py
CASSANDRA-10997 was committed. These are no longer failures.
Either @knifewine or @mambocab to review
=> Remove known_failures for 10997

schema_metadata_test.py, upgrade_tests/cql_tests.py
@ptnapoleon, can you review? I don't think I missed any instances of this ticket.
=> CASSANDRA-10730 was closed, remove known_failure

.travis.yml, auth_test.py, bootstrap_test.py, compaction_test.py, concurrent_schema_changes_test.py, jmxmetrics_test.py, linter_check.sh, snapshot_test.py
A few PEP8 fixes necessary for the PEP checks to only ignore E501 errors.
=> Fix pep8 2015 01 18

secondary_indexes_test.py
Use an exclusive cql connection to ensure that the coordinator is deterministic
=> Ensure we fix the coordinator for query (CASSANDRA-10905)

incremental_repair_test.py
@ptnapoleon and/or @krummas are we good to unskip this test and resolve https://issues.apache.org/jira/browse/CASSANDRA-9752 ?
=> unskip multiple_subsequent_repair_test after #9752

compaction_test.py
=> Be lenient to almost right computed throughput

incremental_repair_test.py
Reverts riptano/cassandra-dtest#761
Still hanging CI
=> Revert "unskip multiple_subsequent_repair_test after #9752"

replication_test.py
=> Harden replication tests

upgrade_tests/cql_tests.py
This should hopefully fix CASSANDRA-10836
=> Always use LWT read and writes for conditional tests

cqlsh_tests/cqlsh_tests.py
This test simply checks that we can execute LWT operations without an error in cqlsh.
=> Add cqlsh LWT test for CASSANDRA-11003

pushed_notifications_test.py
See discussion in CASSANDRA-10870
@mambocab or @stef1927 to review. We'll give this a week or so after merging to see if the flapping tests start passing on CI, before we resolve 10870.
=> Harden restart_node_test

largecolumn_test.py
Pretty sure this should fix https://issues.apache.org/jira/browse/CASSANDRA-11058
=> Make test of number work with negative numbers

dtest.py, replication_test.py
=> Block on traces in replication_test.py

upgrade_tests/upgrade_base.py
@ptnapoleon and @knifewine to review.
Please review carefully to make sure the changes are correct. Correctness here means that the changed code executes as though `QUERY_UPGRADED=true`, `QUERY_OLD=true`, and `UPGRADE_MODE=normal`.
=> Remove upgrade tests env vars

index_summary_upgrade_test.py
Local testing works as expected now - notes on https://datastax.jira.com/browse/CSTAR-276
=> Fix offheap configurations in index_summary_upgrade_test

schema_test.py
Test to reproduce CASSANDRA-11050, to commit when the issue itself is committed.
=> Test for CASSANDRA-11050

cqlsh_tests/cqlsh_copy_tests.py
`test_bulk_round_trip_blogposts_with_max_connections` failed because of a timeout during a truncate operation, more details in CASSANDRA-11157. 
I've also removed a known failure for a ticket that was resolved.
=> Harden copy bulk tests by increasing truncate timeout

upgrade_tests/regression_test.py
Can I get a review from @knifewine on this one? I don't know if the intent for this test is to test all the upgrade paths we care about (in which case this approach is the one we want), or if it tests for a regression on one particular upgrade path (in which case this isn't what we want to do).
=> generate upgrade classes for regression_test

assertions.py, auth_test.py
@mambocab and @knifewine to review.
=> Expand docstring comments for the auth tests.

upgrade_tests/cql_tests.py, upgrade_tests/paging_test.py, upgrade_tests/upgrade_through_versions_test.py
Also adds some Doxygen metadata in a place where it was obviously necessary.
=> mark known_failures from upgrade_tests

consistent_bootstrap_test.py, pending_range_test.py, upgrade_tests/cql_tests.py, upgrade_tests/paging_test.py
Removes `@known_failure` annotations for closed tickets.
=> Clean up known failures

cql_tests.py
Looking for feedback on TODOs in docstrings and (in one or 2 places) comments. I'm going to avoid expanding the scope of this PR if I can -- dealing with the TODOs will happen in a followup PR. @ptnapoleon, got time for this?
=> Cql tests cleanup

dtest.py, plugins/dtestconfig.py, requirements.txt, run_dtests.py
Probably not ready for merge yet, just looking to start a conversation. @ptnapoleon?
=> Novnode flag

repair_tests/incremental_repair_test.py
Also add better debug output
@knifewine to review.
=> Expect non-matching repair values in repairedset_test

repair_tests/incremental_repair_test.py
=> multiple full repairs with lcs

cql_tracing_test.py
=> add a forgotten since decorator

paging_test.py, secondary_indexes_test.py, user_types_test.py
Fix the test for the CASSANDRA-6377 patch and add extra tests
=> Cassandra 6377

thrift_tests.py, ttl_test.py
Add 2 new tests to cover CASSANDRA 11207 and change the expectation of an existing one.
=> Cassandra 11207

repair_tests/incremental_repair_test.py
Small thing to improve that I found while filing a bug. @ptnapoleon and/or @knifewine to review.
=> don't manually calculate set() and Counter()

upgrade_tests/upgrade_through_versions_test.py
looks like these are passing now, thanks to @ptnapoleon
=> remove known_failure from 11197

repair_tests/repair_test.py
Made one bug fix, one style fix, and added three tests
=> Add additional repair coverage

secondary_indexes_test.py
=> Make test more robust to lag recording trace events

cqlsh_tests/cqlsh_copy_tests.py
This introduces a new test for CASSANDRA-11053, which was committed yesterday and added a new COPY FROM option for disabling prepared statements. 
I also noticed [one failure] (http://cassci.datastax.com/view/Dev/view/stef1927/job/stef1927-11053-2.1-dtest/16/testReport/cqlsh_tests.cqlsh_copy_tests/CqlshCopyTest/test_bulk_round_trip_blogposts/) in the bulk copy tests due to a wrong element count, so I've increased the consistency level to ALL.
=> A new test for CASSANDRA-11053

cqlsh_tests/cqlsh_copy_tests.py
CASSANDRA-11274 will change the signature of `formatting.format_value()` and this pull request addresses this, see comments in the patch.
This patch is backward compatible so we can merge at any time but once CASSANDRA-11274 is committed, some cqlsh copy tests will fail unless this pull request is merged.
=> Changes to formatting.format_value() for CASSANDRA-11274

repair_tests/repair_test.py
=> Fix repairs

secondary_indexes_test.py
@mshuler Still testing this locally, but does this look like it'll address CSTAR-347?
=> isort and skip hanging test

bootstrap_test.py, replace_address_test.py
- Fix test for CASSANDRA-11286
- Remove @known_failure annotation, since its highly likely that it's caused by CASSANDRA-11286
=> Fix resumable bootstrap_test

materialized_views_test.py
=> Issue write a CL > ONE so that we don't have to worry about EC

topology_test.py
Node is not expected to start up. Set wait_other_notice to False
=> Fix node start in decommissioned_node_cant_rejoin_test

compaction_test.py
Saw room for a little improvement, so I made it. @ptnapoleon and/or @knifewine to review.
=> refactor get_random_word

pushed_notifications_test.py
On systems that have dual-stack IPv4/IPv6, the name 'localhost' may
prefer IPv6 and resolve to ::1 instead of the expected 127.0.0.1.
=> Use 127.0.0.1 instead of 'localhost' for dual-stacked systems

repair_tests/repair_test.py
small change for more readable assert
=> better assert error message

materialized_views_test.py
Seeing consistency issues with write at ONE then immediate
read at QUORUM
@knifewine or @mambocab to review
=> Set default CL to QUORUM in complex_mv_select_statements_test

cqlsh_tests/cqlsh_copy_tests.py
A new test for CASSANDRA-11333, do not merge before the ticket is committed.
=> Test for CASSANDRA-11333

upgrade_tests/cql_tests.py, upgrade_tests/paging_test.py, upgrade_tests/upgrade_base.py
=> pause during do_upgrade

bootstrap_test.py
Make sure we don't get too many files during cleanup
=> Monitor datadirectory during cleanup

upgrade_tests/cql_tests.py
forgot to pull these in my pr with the fix.
=> remove known for CASSANDRA-11395

conf/cassandra-2.1_test-select.cfg, conf/cassandra-2.2_test-select.cfg, conf/cassandra-3.0_test-select.cfg, conf/trunk_test-select.cfg
Already skipped in code, more appropriate to do so there
@mshuler to review
=> Remove multi sub repair from conf exclusions

CONTRIBUTING.md
This is something I find useful and wanted to share.
=> Add note on flake8 commit hook

compaction_test.py
[CASSANDRA-9692](https://issues.apache.org/jira/browse/CASSANDRA-9692) normalizes logging output and pretty-prints rates/sizes in many places.
This breaks two tests in compaction_test.py, which match on the units with regexes. These have been extended to support both old and new-style rates, splitting behavior on version 3.6 (current trunk).
Please review but don't merge until CASSANDRA-9692 is commited; this will minimize the length of time for which the tests fail (since trunk is currently 3.6 and does not have these logging changes).
=> Support changed log units after CASSANDRA-9692 in compaction tests

repair_tests/repair_test.py
=> make sure we can run sub range repairs in parallel

consistency_test.py
CASSANDRA-11225: hardened consistency_test.TestAccuracy.test_simple_strategy_counters
by performing a read at CL.ALL before each iteration and using property file snitch
to ensure coordinator reads locally if it is a replica. Enhanced error reporting.
=> CASSANDRA-11225: hardened consistency_test test_simple_strategy_counters

cqlsh_tests/cqlsh_copy_tests.py
Added a new test for CASSANDRA-11320 and hardened an existing test since it failed once with the 11320 patch in place.
=> A new test for CASSANDRA-11320

cql_tracing_test.py
Just adds some debug printing for https://issues.apache.org/jira/browse/CASSANDRA-11465.
=> get more debug info in tracing_unknown_impl_test

cqlsh_tests/cqlsh_tests.py
An existing test needs changing due to CASSANDRA-11529. 
Commit only when the C* ticket is also committed.
=> Fixed test for CASSANDRA-11529

auth_test.py
compare with the correct part of users list
=> fix drop user case sensitive test

paging_test.py
This PR adds dtests for PER PARTITION LIMIT queries introduced in [#7017](https://issues.apache.org/jira/browse/CASSANDRA-7017)
=> Add paging dtests for PER PARTITION LIMIT for CASSANDRA-11535

user_types_test.py
The ``listify()`` function had some strange behavior around single item
lists that resulted in an error.  I made it consistent and
non-surprising here, and updated other tests to match.
=> Fix CASSANDRA-11560 (user_types_test failure)

paging_test.py
Add paging tests for filtering with clustering, static and regular columns for [#11310](https://issues.apache.org/jira/browse/CASSANDRA-11310)
=> Add paging tests for filtering with clustering columns for 11310

secondary_indexes_test.py
=> Fix 11564. Only run 2i vnode test with vnodes

pushed_notifications_test.py
Solves problem where query is aborted but error hasn't been flushed
to log yet
=> Fix 11476. Watch node logs instead of grepping.

bootstrap_test.py
Some light cleanup. I was going to make the stress larger, but I no longer think the size of the bootstrap is why the test fails.
=> Make improvements to resumable_bootstrap_test

commitlog_test.py
Some cleanup in advance of changes I'm going to make for testing CDC. @ptnapoleon and/or @knifewine to review, please.
=> Commitlog test cleanup

sstableutil_test.py, tools.py
See discussion on CASSANDRA-11497.
=> CASSANDRA-11497: Fixed SSTableUtilTest.abortedcompaction_test

cqlsh_tests/cqlsh_copy_tests.py
Some tests for CASSANDRA-11474, which disables COPY FROM batching if MAXBATCHSIZE is set to 1, but only for C* versions from 2.2 to 3.5, see discussion on the ticket for details. Since `test_reading_counter_without_batching` is only testing a different code path but no new functionality, I've disabled it for 3.6 onwards. 
As usual, we need to commit the C* ticket before merging this PR.
=> Tests for CASSANDRA-11474

cqlsh_tests/cqlsh_copy_tests.py
I've extended the null indicator tests to catch COPY FROM problems with type conversions.
The enhanced tests will fail until CASSANDRA-11549 is committed.
=> CASSANDRA-11549: extended null indicator tests 

dtest.py
don't merge just yet, still have some testing to do.
=> protect against active log scanning race conditions

cql_tests.py
(currently [#11621](https://issues.apache.org/jira/browse/CASSANDRA-11621) awaits review)
=> Test for tables with thousands of columns for CASSANDRA-11621

cqlsh_tests/cqlsh_copy_tests.py
This is a test to reproduce the issue described in CASSANDRA-11633.
=> Test for CASSANDRA-11633

topology_test.py
@ptnapoleon to review (in case I goofed decorator ordering)
=> known_failure CASSANDRA-11665

topology_test.py
=> Fix 11665. Wait longer for node to shut down in cant_rejoin_test

commitlog_test.py, snapshot_test.py
Changes in advance of C* 8844 testing. @ptnapoleon or @knifewine to review.
=> Commitlog test improvements

materialized_views_test.py
=> Fix 11674. Use CL.QUORUM in mv clustering_column_test

pushed_notifications_test.py
=> Intelligently wait for first notification in moved_single_node

paging_test.py
Add paging tests for partition range queries where the clustering columns are all specified.
=> CASSANDRA-11669

paging_test.py
This PR is linked to CASSANDRA-11603
=> Fix page size issue and add additional checks

sstableutil_test.py
In `SSTableUtilTest.abortedcompaction_test()`, we should not check final files after aborting compaction since we do not know how far it got. 
See the [C* ticket](https://issues.apache.org/jira/browse/CASSANDRA-11692) for more details.
=> CASSANDRA-11692: do not check final files after aborted compaction

bootstrap_test.py
=> Ignore tmplink files

upgrade_tests/upgrade_manifest.py
=> Fix whitespace in upgrade_manifest

topology_test.py
http://cassci.datastax.com/view/Parameterized/job/parameterized_dtest_multiplexer/103/
https://issues.apache.org/jira/browse/CASSANDRA-11837
Literally anyone to review, I promise it's fine.
=> Don't wait notice on an already stopped node

dtest.py
@knifewine and @mambocab to review
=> Always disable maxDiff

auth_test.py, dtest.py, user_functions_test.py
Reverts riptano/cassandra-dtest#978
=> Revert "Fix auth test import"

upgrade_tests/cql_tests.py
=> upgrade tests with frozen type should run only 2.1+

upgrade_tests/cql_tests.py
=> flagged features not avaiable in < 2.1. Added jira ticket docstring ref

upgrade_tests/cql_tests.py
=> restrict test version to 2.1+

upgrade_tests/cql_tests.py
=> restricting features not in 2.0. Added jira ref

upgrade_tests/cql_tests.py
@ptnapoleon for your consideration.
=> restricting tests on features not available on 2.0

thrift_tests.py
=> adjusted wait time for index creation

upgrade_tests/upgrade_manifest.py
@mambocab I forgot to mention this env var in my earlier pr (one more small thing I don't want people to trip over)
=> make note of env var for local upgrade testing

upgrade_tests/cql_tests.py
=> restricted to 2.1+ due to bug in 2.0

upgrade_tests/upgrade_manifest.py
@ptnapoleon or @mambocab to review
=> 3.6 branch is still alive until 3.6 release

cql_tracing_test.py
=> Skip flakey part of tracing test on 2.1

compaction_test.py
Reverts riptano/cassandra-dtest#1000
seems the compactions take too long on cassci and the tests time out, I'll work on it
=> Revert "Never purge tombstones longer test"

upgrade_tests/storage_engine_upgrade_test.py
@mambocab, please review.
Tested on cassci:
http://cassci.datastax.com/view/Parameterized/job/parameterized_dtest_multiplexer/124/
=> Changed % string formatting to .format() string formatting

repair_tests/incremental_repair_test.py
=> disable hints

commitlog_test.py, configuration_test.py, consistency_test.py, consistent_bootstrap_test.py, json_tools_test.py, repair_tests/repair_test.py
@mambocab, please review.
Cassci test: http://cassci.datastax.com/view/Dev/view/smccarthy788/job/smccarthy788-cassandra-3.0-dtest/lastCompletedBuild/
=> changed all calls to set_configuration_options to reflect ccm change

commitlog_test.py, configuration_test.py, consistency_test.py, consistent_bootstrap_test.py, json_tools_test.py, repair_tests/repair_test.py
Reverts riptano/cassandra-dtest#1002
=> Revert "changed all calls to set_configuration_options to reflect ccm change"

user_functions_test.py
=> Added annotation

consistency_test.py
=> annotated known failure

json_tools_test.py
Just added known failure to the json file
=> known failure added

offline_tools_test.py
This takes the run time from ~15m to ~80s.
This needs to be merged at the same time as a related ccm changed.  I'll post the PR link in a sec.
=> Speed up sstableofflinerelevel_test

commitlog_test.py, concurrent_schema_changes_test.py, cqlsh_tests/cqlsh_copy_tests.py, disk_balance_test.py, jmx_test.py, jmxmetrics_test.py, offline_tools_test.py, repair_tests/incremental_repair_test.py, repair_tests/repair_test.py, replace_address_test.py, secondary_indexes_test.py, snitch_test.py, sstable_generation_loading_test.py, sstablesplit_test.py, sstableutil_test.py, stress_tool_test.py, topology_test.py
=> added 'no-warmup' arg to stress calls

compaction_test.py
A new test for CASSANDRA-11765.
=> Added a user defined compaction test, CASSANDRA-11765

dtest.py
@ptnapoleon: Please review.
Connected with https://github.com/pcmanus/ccm/pull/513
=> save gc & compaction logs on tear down

dtest.py
@ptnapoleon: 
Passed cassci build.
http://cassci.datastax.com/view/Dev/view/smccarthy788/job/smccarthy788-cassandra-3.0-dtest/12/
=> Check log length is not zero

replication_test.py
=> annotated jira-11927

upgrade_tests/cql_tests.py, upgrade_tests/upgrade_base.py
Test non-compound RangeTombstone ser during upgrades
Done for CASSANDRA-11930
=> CASSANDRA-11930

cqlsh_tests/cqlsh_copy_tests.py
This should roughly cut the total test run time in half (currently 1hr)
=> Speed up cqlsh copy tests

dtest.py, repair_tests/repair_test.py, sstable_generation_loading_test.py, upgrade_tests/storage_engine_upgrade_test.py
=> CASSANDRA-10990 dtests

cqlsh_tests/cqlsh_copy_tests.py
Reverts riptano/cassandra-dtest#1025
=> Revert "Speed up cqlsh copy tests"

repair_tests/incremental_repair_test.py
=> annotation for cassandra-12006

cql_tracing_test.py
=> added known failure annotation for cassandra-12007

repair_tests/repair_test.py
=> annotation for cassandra-12022

cqlsh_tests/cqlsh_copy_tests.py
=> annotation for cassandra-12024

pushed_notifications_test.py
Some fixes as discussed in CASANDRA-11731 and additional log messages. 
The restart node tests have been modified to take into account the fix that will be delivered by CASSANDRA-11038. Until this patch is delivered, these tests will fail if you merge this pull request.
=> Fixes for CASSANDRA-11731

paging_test.py
=> annotation for cassandra-12025

cdc_test.py, meta_tests/utils_test/funcutils_test.py, requirements.txt, utils/fileutils.py, utils/funcutils.py
Incrementally pushing up tests for 8844. @ptnapoleon and/or @knifewine to review, please. @josh-mckenzie, could you please take a look as well? These pass locally running on your `8844_review` branch.
Please (please) don't merge until I've squashed this into something sensible. Don't even look at the commits. Please, I beg of you.
=> 8844 tests pr0

auth_test.py, cqlsh_tests/cqlsh_copy_tests.py, cqlsh_tests/cqlsh_tests.py, repair_tests/repair_test.py
annotations, @ptnapoleon please review.
=> annotations

cql_tests.py
Related Cassandra ticket is [9842](https://issues.apache.org/jira/browse/CASSANDRA-9842)
=> Add dtests for LWT with static columns and batches

dtest.py
This cuts about 1s off of Cassandra's startup time, which should save us ~15m on the dtests.
This requires https://github.com/pcmanus/ccm/pull/519 in order to work
correctly.
=> Improve startup time by prelocating libjemalloc

dtest.py
Reverts riptano/cassandra-dtest#1058
=> Revert "Improve startup time by prelocating libjemalloc"

upgrade_tests/upgrade_base.py, upgrade_tests/upgrade_through_versions_test.py
depends on https://github.com/pcmanus/ccm/pull/518
=> log ignores for CASSANDRA-12026

rebuild_test.py
JIRA for this PR is [CASSANDRA-10526](https://issues.apache.org/jira/browse/CASSANDRA-10526).
=> Add test for CASSANDRA-10406

repair_tests/incremental_repair_test.py
=> disable autocompaction during repairedset test

bootstrap_test.py
=> Add bootstrap test with -Dcassandra.write_survey and nodetool join

read_repair_test.py
my note isn't a standard one, but was couldn't think of anything better than what the error was.  I expect you'll tell me to change it?
=> added another known failure

dtest.py
depends on ccm changes here https://github.com/pcmanus/ccm/pull/515
this makes sure that in cleanup the log watching thread will be joined and allowed to stop.
=> add proper thread cleanup for active log watching

upgrade_tests/upgrade_manifest.py
=> upgrade tests ver bump to 2.1.15, 2.2.7, 3.0.8

paging_test.py
@mambocab or @smccarthy788  to review.
=> Expand debug output to help solve 12068

read_repair_test.py
Also, use correct number of brackets. This is a fix from a mistake
in the big Assertion Refactoring
Literally anyone to review
@knifewine or @mambocab or @smccarthy788
=> Only check first two columns of result

paging_test.py
The patch is related to [CASSANDRA-12025](https://issues.apache.org/jira/browse/CASSANDRA-12025).
=> Use long message to provide more information about failed query.

commitlog_test.py, counter_tests.py, cql_tracing_test.py, cqlsh_tests/cqlsh_tests.py, materialized_views_test.py, repair_tests/repair_test.py, thrift_tests.py
=> add known_failure annotations for new jira tickets

cqlsh_tests/cqlsh_tests.py
[CASSANDRA-12076](https://issues.apache.org/jira/browse/CASSANDRA-12076) changed the format of error messages on failed login attempts. A PR at the time updated auth_test.py but not the cqlsh tests.
I've verified these pass after the fix on 3.9 and 3.10, so the version gating works as intended.
=> Fix cqlsh login tests to expect error format from CASSANDRA-12076

materialized_views_test.py
=> add known_failure annotations

materialized_views_test.py
=> add known_failure annotation

upgrade_tests/cql_tests.py, upgrade_tests/upgrade_through_versions_test.py
=> annotations for upgrade_test_all 59 failures

materialized_views_test.py
Wait for schema agreement after creating table and view
=> CASSANDRA-11698: Flaky clustering_column_test

rebuild_test.py
@mambocab to review. related to CASSANDRA-11687
=> error message showing actual value found if assertEqual fails

replication_test.py
This will make it a little easier to debug failures in this test.
=> add debug statement to murmur loop

dtest.py, secondary_indexes_test.py
=> Prevent schema concurrency issues in 2i test

user_functions_test.py
=> Use a session w/o a WL policy for schema changes

dtest.py, repair_tests/repair_test.py
2 simple changes to hopefully address [CASSANDRA-12162](https://issues.apache.org/jira/browse/CASSANDRA-12162).
=> Retry more in repair test

jmx_test.py, jmxutils.py
=> Add tests for connecting to JMX with SSL

bootstrap_test.py
Basically rf=1 tests were flaky for non-vnodes because depending where the new node was bootstrapped, the consistent bootstrap could succeed or not (depending if the node would take or not the range of the down node). The fix is to use deterministic tokens for the non-vnode case.
Also took the chance to improve comments, test naming and simplify test to use 2 nodes instead of 3.
Non-vnode dtest run submitted here: http://cassci.datastax.com/view/Dev/view/paulomotta/job/pauloricardomg-trunk-novnode-dtest/
=> Update consistent bootstrap tests to support non-vnodes case

rebuild_test.py
This test didn't fail when the `rebuild` call in the thread raised an exception; this PR fixes that.
Clarity question: I've written a function that generically takes a function here. Since it's only used the once, would it be clearer to write:
```python
def rebuild_and_register_exc_info_on_exception():
"""
Closes over self to catch any exceptions raised by func and
register them at self.thread_exc_info
Based on http://stackoverflow.com/a/1854263
"""
try:
rebuild()  # closed over
except Exception:
import sys
self.thread_exc_info = sys.exc_info()
cmd1 = Thread(target=rebuild_and_register_exc_info_on_exception)
```
=> correctly fail on errors from rebuild thread

cdc_test.py
Depends on #1008. Another gross history; please don't merge until that's addressed. Alternately, we could squash both PRs together into one big thing. Up to reviewers -- @ptnapoleon and/or @knifewine, and @josh-mckenzie, please.
@josh-mckenzie I'm still not seeing the behavior I expect after flush -- I still don't find any commitlogs in `cdc_raw`. I assume I'm doing something wrong here; what am I missing?
=> 8844 tests pr1

consistency_test.py
Once PR https://github.com/datastax/python-driver/pull/617 is merged, this change will eliminate the UnknownColumnFamilyException warnings from the logs. You can merge this PR as soon as you would like, but it won't have any effect until the driver change is also available.
I've also fixed some typos and pep warnings.
=> CASSANDRA-11950: wait for schema agreement

user_functions_test.py
=> Fix 12265, block on schema agreement between ALL DDL changes

upgrade_tests/cql_tests.py
This runs locally, so I think the code is good. In progress on CassCI here:
http://cassci.datastax.com/view/Parameterized/job/parameterized_dtest_multiplexer/180/console
=> Cassandra 12250 check for indexes

offline_tools_test.py
This is the additional known failure added as Josh mentioned
=> known failure added to existing failure

secondary_indexes_test.py
@mambocab, I know you won't like this, so I'm asking you to review
=> Block until index is finished before inserting data

token_generator_test.py
Rename to token_generator_test.py so nose picks it up
Do some better string formatting
Add jira ticket and since annotaitons
Use os.path.join
@mambocab and @c-kodman to review
=> Clean up token_generator.py

replace_address_test.py
ran test a few times, no failure.  I realize this could be flaky, but is there something else I messed up?
=> add known failure annotation

offline_tools_test.py
Couldn't really try it out because I don't have **windows**. @ptnapoleon can you take a look?
=> CASSANDRA-11235: Ignore JNA/JavaLaunchHelper warning

materialized_views_test.py
=> add known failure annotations

materialized_views_test.py
=> change known failure annotation to 12140 to deal with duplicates

materialized_views_test.py
Make sure to drain the batchlog after each commit
=> 12097: failure in view_tombstone_test

upgrade_tests/cql_tests.py
=> Specify different error message for order by clause in alias test

user_functions_test.py
@mambocab or @knifewine or @smccarthy788. This WILL fix the test, but I'm only 80% sure doesn't change the test in a bad way. Someone sanity check this is reasonable?
=> Use schema_wait_session to create UDFs

repair_tests/repair_test.py
Complementary dtest for [CASSANDRA-11349](https://issues.apache.org/jira/browse/CASSANDRA-11349)
=> Add repair_test.py test for CASSANDRA-11349

sstable_generation_loading_test.py
This should enable debugging for [CASSANDRA-12137](https://issues.apache.org/jira/browse/CASSANDRA-12137). Depends on https://github.com/pcmanus/ccm/pull/510/files for proper error handling, so don't merge yet.
=> Sstable popen

consistency_test.py, materialized_views_test.py, replication_test.py, upgrade_tests/upgrade_through_versions_test.py
@ptnapoleon, @mambocab, please review.
=> add large attribute to test methods

sstable_generation_loading_test.py
Reverts riptano/cassandra-dtest#1080
Broke the build.
=> Revert "Sstable popen"

upgrade_tests/upgrade_base.py
this is just to get upgrade tests running for the evening, then we should figure out if there's a better fix.
=> handle missing attr

cql_tracing_test.py
=> Restrict entire tracing test to 2.2+

compaction_test.py
=> Don't perform int division on sstable count

compaction_test.py
=> only divide by data dir count in 3.2+

compaction_test.py, configuration_test.py, jmx_test.py, scrub_test.py, token_generator_test.py
This code should *NOT be merged.  I just want the non commented lines to be looked at, or to use this as a way of stashing for now?
=> adding parse but don't merge this yet

repair_tests/repair_test.py
So this fixes the test, as in, makes it pass without removing coverage of C*. However, the stress behavior is still a thing. Do we want to file a bug for that? @mambocab / @jkni?
=> Use cqlsh instead of stress to verify data count

replace_address_test.py
See CASSANDRA-12415. followup to #1204
=> add resource-intensive attr to 4-node tests

global_row_key_cache_test.py
=> update known_failure annotations

.travis.yml, bootstrap_test.py, linter_check.sh
Fixes another import (:facepalm:) and fixes the linter scripts to catch these errors in the future.
=> Fix interrupt bootstrap import

sstable_generation_loading_test.py
Running the whole file here:
http://cassci.datastax.com/view/Parameterized/job/parameterized_dtest_multiplexer/238/
Serves the same purpose as #1080, but hopefully actually works.
=> print stdout and err from sstableloader

batch_test.py
Testing here: http://cassci.datastax.com/view/Parameterized/job/parameterized_dtest_multiplexer/249/
=> Specify protocol version in mixed version batch tests

upgrade_tests/cql_tests.py
=> Don't execute schema change in mixed-version cluster

upgrade_tests/upgrade_through_versions_test.py
=> don't run counter subprocesses over upgrades

pending_range_test.py
=> Mark pending range as resource intensive

dtest.py, secondary_indexes_test.py, tools.py
Not sure if I got every instance where index_is_built could be used.
=> Write a blocker function to ensure that an index is built

byteman/decommission_failure_inject.btm, topology_test.py
Add test for testing concurrent decommission is not allowed and decommission is resumable. 
Byteman script injection is used here.
=> Add tests for decommission

rebuild_test.py
=> Only alter system_auth on 2.2+

dtest.py, secondary_indexes_test.py
=> Fix infinite loop in 2i tests

cql_tests.py
Some new tests for the slow query log, introduced by [CASSANDRA-12403](https://issues.apache.org/jira/browse/CASSANDRA-12403).
=> Tests for CASSANDRA-12403

offline_tools_test.py, upgrade_crc_check_chance_test.py, upgrade_internal_auth_test.py
@ptnapoleon, take a look at this for me, please.
=> Annotations 8.22

cql_tests.py
=> restrict C-12403 test to 3.10+

secondary_indexes_test.py
@mambocab and @knifewine to review. I'll kick off some CI and link here
=> Raise DtestTimeoutError on failed 2i build

upgrade_tests/cql_tests.py, upgrade_tests/upgrade_base.py
I need to run a lot of CI to be sure this doesnt break everything
=> node.get_versions in upgrade should return a LooseVersion

compaction_test.py
@ptnapoleon, please review.
This should only be merged after https://github.com/pcmanus/ccm/pull/540
=> use get_sstable_data_files method in ccm

run_dtests.py
=> Dtest runner tweaks

cql_tracing_test.py
For https://issues.apache.org/jira/browse/CASSANDRA-11706
=> Fix tracing tests after improving the logging message

topology_test.py
=> Ignore all streaming errors on crash test

repair_tests/repair_test.py
this needs to wait for CASSANDRA-12279 to be merged
=> Add test for CASSANDRA-12279

dtest.py, upgrade_tests/paging_test.py
@ptnapoleon & @mambocab, please review.
I've not been able to run this locally, so I'm running a multiplex here:
http://cassci.datastax.com/view/Parameterized/job/parameterized_dtest_multiplexer/271/
=> patch for CASSANDRA-12524

cqlsh_tests/cqlsh_copy_tests.py
This fix increases the COPY TO page timeout for `test_bulk_round_trip_non_prepared_statements` in order to fix the operation timed out errors, see [CASSANDRA-12479](https://issues.apache.org/jira/browse/CASSANDRA-12479). It also shows the COPY command's output for all bulk round trip tests as I suspect other tests may be failing with timeouts, see for example [CASSANDRA-12559](https://issues.apache.org/jira/browse/CASSANDRA-12559). Finally, I've removed the known failures of some solved tickets.
If CASSANDRA-12559 is also failing for the same reason, we may want to increase the COPY TO page timeouts for all bulk round trip tests.
=> Fix for CASSANDRA-12479

consistency_test.py
This should hopefully fix all flakiness in this test, and possibly in other consistency tests as well, more details in [CASSANDRA-12092](https://issues.apache.org/jira/browse/CASSANDRA-12092).
=> CASSANDRA-12092: fixTestAccuracy.test_simple_strategy_counters

CONTRIBUTING.md
@ptnapoleon, all the byteman files I can find are already in the byteman directory, so I just updated CONTRIBUTING.md to state where future .btm files should reside.
=> explain where byteman files should reside

materialized_views_test.py
=> Mark 5 node MV tests as resource intensive

upgrade_tests/bootstrap_upgrade_test.py
Should fix the import problem causing [this test](http://cassci.datastax.com/job/trunk_dtest_upgrade/43/testReport/nose.failure/Failure/runTest/) to fail.
=> change imports for new module structure

thrift_tests.py, upgrade_tests/storage_engine_upgrade_test.py
These are 2 new thrift tests that @thobbs and I wrote for CASSANDRA-12423 to test range tombstones with end of component (eoc) set to zero. Once the ticket is committed, the tests will pass on all versions, at the moment they only work on 2.x but fail in 3.0+. There is also a new storage engine upgrade test to ensure that we can upgrade an sstable with such tombstones.
Please don't merge until the ticket is committed.
=> New tests for CASSANDRA-12423

upgrade_tests/paging_test.py
@ptnapoleon & @mambocab please review. This should only be merged after: https://github.com/pcmanus/ccm/pull/541
=> implement timed log grep from cluster.py

repair_tests/repair_test.py, thrift_tests.py, upgrade_tests/storage_engine_upgrade_test.py
Fixes 12637 12634 12578
@jkni or @mambocab to review
=> Version gate tests that dont run on 3.9

upgrade_tests/paging_test.py
@ptnapoleon, @mambocab: please review.
Running a multiplex here: https://cassci.datastax.com/view/Parameterized/job/parameterized_dtest_multiplexer/309/
=> add default pattern to node grepping

bootstrap_test.py
@ptnapoleon, please review. To be merged after https://github.com/pcmanus/ccm/pull/542
=> replace watch_for_logs with wait_for_thrift_interface

upgrade_tests/cql_tests.py, upgrade_tests/paging_test.py, upgrade_tests/upgrade_base.py
=> add log ignore for RejectedExecution during upgrade

replace_address_test.py
=> Version gate more non-3.9 tests

requirements.txt
=> Install CCM latest, not master

materialized_views_test.py
=> Skip all MV tests that use over 3 nodes

auth_test.py, commitlog_test.py, compaction_test.py, cql_tracing_test.py, cqlsh_tests/cqlsh_copy_tests.py, cqlsh_tests/cqlsh_tests.py, jmx_auth_test.py, json_test.py, mixed_version_test.py, paging_test.py, pushed_notifications_test.py, repair_tests/deprecated_repair_test.py, requirements.txt, tools/decorators.py, tools/jmxutils.py, upgrade_supercolumns_test.py, upgrade_tests/upgrade_base.py, upgrade_tests/upgrade_manifest.py, user_functions_test.py, write_failures_test.py
@mambocab to review. Depends on https://github.com/pcmanus/ccm/pull/548
CI at http://cassci.datastax.com/view/Dev/view/ptnapoleon/job/ptnapoleon-trunk-dtest/20/testReport/
http://cassci.datastax.com/view/Dev/view/ptnapoleon/job/ptnapoleon-trunk-upgrade-upgrade/2/
=> Loose versions

upgrade_tests/upgrade_manifest.py
to be merged when 3.0.9 is released.
=> bump upgrade manifest to 3.0.9

cqlsh_tests/cqlsh_copy_tests.py
Another COPY TO test that requires a higher page timeout, see [CASSANDRA-12430](https://issues.apache.org/jira/browse/CASSANDRA-12430).
Maybe we should review all cqlsh COPY TO tests and ensure they have a higher page timeout. It seems that the default, 10 seconds per 1000 rows, is not enough on Jenkins and causes rare failures. As an alternative, we could also consider doubling the default value in production code, I don't think this would cause issues.
=> Increase the page timeout for CASSANDRA-12430

bootstrap_test.py, byteman/inject_failure_streaming_to_node2.btm, rebuild_test.py, replace_address_test.py, secondary_indexes_test.py, tools/assertions.py
=> CASSANDRA-12039

materialized_views_test.py
=> Add simple test to build MV with wide partition

repair_tests/incremental_repair_test.py
@ptnapoleon, @mambocab: Please review.
Multiplexing here: https://cassci.datastax.com/view/Parameterized/job/parameterized_dtest_multiplexer/314/
=> remove use of output files

dtest.py, requirements.txt, upgrade_tests/README.md, upgrade_tests/upgrade_manifest.py
changes necessary to match pcmanus/ccm#554 (local: slug changes to support multiple local versions).
=> deps for pcmanus/ccm#554

cqlsh_tests/cqlsh_copy_tests.py
A test that invokes cqlsh COPY with authentication enabled in 3 different ways: from the command line, using the SOURCE command or the --file option.
=> Basic security tests for cqlsh copy, CASSANDRA-12642

upgrade_tests/upgrade_base.py
@mambocab to review. See C-12697
=> Stop ignoring cdc error on upgrade

cql_tests.py
@ifesdjeen or @blerer to review
=> Use nodes kwarg correctly in cql prepare

materialized_views_test.py
=> When inserting data for MV, settle the nodes before continuing

upgrade_tests/upgrade_manifest.py
to be merged after 2.2.8 is released.
=> update upgrade manifest to 2.2.8

cql_tests.py
CASSANDRA-12060 is only for 3.0.10 and 3.10 and up. 3.0.9 and 3.9 would still fail. This patch fixes it.
=> Fix versions in which CASSANDRA-12060 is applied

upgrade_tests/upgrade_manifest.py
=> upgrade version bump to 3.9

upgrade_tests/upgrade_manifest.py
=> Change in-dev 3.x to the correct branch

schema_test.py
A new test for reproducing the problem described in [CASSANDRA-12582](https://issues.apache.org/jira/browse/CASSANDRA-12582).
It passes locally for 2.1 and 2.2 without any code changes, but for 3.0 and higher it will fail until the ticket is committed.
=> A new test for CASSANDRA-12582

cqlsh_tests/cqlsh_copy_tests.py
This is a new test for [CASSANDRA-12740](https://issues.apache.org/jira/browse/CASSANDRA-12740), which was just committed.
=> New test for CASSANDRA-12740

cdc_test.py, snapshot_test.py, tools/hacks.py
Supercedes #1340, implementing @jkni's suggested approach with a shared utility function. @jkni can you review?
=> Write to fresh CLs

auth_test.py
=> Ensure permissions on UDAs are cleaned up on drop

cqlsh_tests/cqlsh_copy_tests.py
I've noticed a failure for `test_round_trip_with_rate_file` but there isn't enough information to understand the problem. I've also added the ability to print debug output to `run_cqlsh()`
=> Add debug information for CqlshCopyTest.test_round_trip_with_rate_file

compaction_test.py
Add dtest for CASSANDRA-11550, tracked in CASSANDRA-12738.
Reviewed by Marcus Eriksson.
=> add the dtest for compaction fanout_size

upgrade_tests/cql_tests.py
@thobbs or @guyboltonking to review
=> Change upgrade tests to expect different ordering after C-12420

repair_tests/incremental_repair_test.py
=> Only run sstablemetadata against nodes with sstables

replication_test.py, upgrade_tests/upgrade_supercolumns_test.py
=> add new known failues. remove stale annotations.

materialized_views_test.py
=> Fix C-12874, read/write at CL QUORUM

meta_tests/assertion_test.py, tools/assertions.py
@mambocab to review. Needed to debug C-12895 (amongst others), also this is totally broken.
=> Fix string formatting code

cqlsh_tests/cqlsh_copy_tests.py
A new test for CASSANDRA-12863.
=> New test for CASSANDRA-12863

compaction_test.py
Fixes c-12119
Anyone to review
=> Fix regex for large compaction warning test

bootstrap_test.py
@mambocab to review, this is a hotfix. We can think of a better way to do this later.
```
nose -sv --collect-only bootstrap_test.py
bootstrap_on_write_survey_test (bootstrap_test.TestBootstrap) ... ok
bootstrap_with_reset_bootstrap_state_test (bootstrap_test.TestBootstrap) ... ok
consistent_range_movement_false_with_replica_down_should_succeed_test (bootstrap_test.TestBootstrap) ... ok
consistent_range_movement_false_with_rf1_should_succeed_test (bootstrap_test.TestBootstrap) ... ok
consistent_range_movement_true_with_replica_down_should_fail_test (bootstrap_test.TestBootstrap) ... ok
consistent_range_movement_true_with_rf1_should_fail_test (bootstrap_test.TestBootstrap) ... ok
decommissioned_wiped_node_can_gossip_to_single_seed_test (bootstrap_test.TestBootstrap) ... ok …
```
=> Mark TestBootstrap as a test class

repair_tests/repair_test.py
=> Add 12904 annotation

read_failures_test.py
=> Fix read_failures_test on 2.2 branch

disk_balance_test.py
=> write more data in disk balance test

cqlsh_tests/cqlsh_copy_tests.py
@ptnapoleon, for your review.
CI : http://cassci.datastax.com/view/Parameterized/job/parameterized_dtest_multiplexer/370/
=> retry run_cqlsh on client request timeout errors

auth_test.py
Occasionally, `auth_test:TestAuth.permissions_caching_test` can fail unexpectedly. Investigation suggests that this may be due to the cache expiring before the test has a chance to run the query that verifies the cached permissions. This patch adds a retry in the case that the cache is found to have expired earlier than expected.
=> Make permissions_caching_test more resilient against delays

upgrade_tests/upgrade_manifest.py
Testing here:
http://cassci.datastax.com/view/Dev/view/ptnapoleon/job/ptnapoleon-trunk-upgradeing-upgrade/4/console
=> Test upgrades to 4.0 versions, properly

cqlsh_tests/cqlsh_copy_tests.py
This is a new test for a cqlsh copy-from bug, see [CASSANDRA-12959](https://issues.apache.org/jira/browse/CASSANDRA-12959) for more details.
=> A new test for CASSANDRA-12959

cqlsh_tests/cqlsh_copy_tests.py
A new test for CASSANDRA-12909.
=> New test for CASSANDRA-12909

cql_tests.py
[CASSANDRA-13050](https://issues.apache.org/jira/browse/CASSANDRA-13050) fixed a bug when monitoring queries, as a consequence the delay time that is applied for testing needs to be reduced, since it will now be applied for every CQL row. The total request timeout needs to be increased for the slow query tests, to ensure the query is only reported as slow and not aborted. 
I've also fixed a few more problems:
* `monitoring_check_interval_ms` is actually `monitoring_report_interval_ms`, unsure when it was renamed but the tests were clearly not updated, it's value was decreased since monitoring more frequently ensures the logs are updated more quickly
* some request timeouts were missing
* using logs at INFO level causes flakiness because the no spam logger only logs every 5 minutes, hence …
=> Fix slow and aborted query tests for CASSANDRA-13050

upgrade_tests/upgrade_manifest.py
Tested here: http://cassci.datastax.com/view/Dev/view/ptnapoleon/job/ptnapoleon-trunk-upgradeing-upgrade/11/testReport/
@mshuler to review
=> Clone from github mirror instead of apache

bootstrap_test.py, pushed_notifications_test.py, topology_test.py
pending https://issues.apache.org/jira/browse/CASSANDRA-12510
=> Test decommission failure when N <= replication factor

tools/decorators.py, upgrade_tests/cql_tests.py, upgrade_tests/upgrade_base.py
@pcmanus or @smccarthy788 to review
=> Let since decorator max version apply to upgrade tests as well

snitch_test.py
This test was added for CASSANDRA-13074 and multiplexed to make sure it would pass.
Unfortunately, this multiplex run took place before CASSANDRA-13050 was committed, which changed the behavior of the read_iteration_delay property such that it didn't take effect for reads that returned empty results.
We need to populate data to be returned by the selects. A multiplex run [here](http://cassci.datastax.com/view/Parameterized/job/parameterized_dtest_multiplexer/380/) shows the test passing on trunk 100 times after this PR. I also tested it on 3.X and 3.11 locally.
=> CASSANDRA-13112 Populate rows in test_multidatacenter_local_quorum so that read_iteration_delay property takes effect

tools/assertions.py
See https://issues.apache.org/jira/browse/CASSANDRA-12437
=> Ignore stress JMX errors, fixes CASSANDRA-12437

read_failures_test.py
A recent change to the read_failures_test for protocol v3 appeared to fix the test on 2.1 but broke it on 2.2, 3.0, 3.11, and trunk. The 2.1 fix rested on a very delicate balance and needed a rework. This also fixes 2.2+.
On 2.1, when hitting tombstone overwhelming exceptions, we have no way to signal this back to the coordinator. This means that on the v3 protocol under 2.1 we won't get the read timeout back until the cluster configured read timeout. Since the cluster configured read timeout and the client configured read timeout were both 10 seconds, whether the error caught by 2.1 was an OperationTimedOut with one wrapped ReadTimeout or a bare OperationTimedOut depended on vnode count, test machine, and the speed of the wind. We can up the client timeout to 15 seconds and switch to the …
=> Fix read_failures_test to handle ReadTimeout, retries, and driver-local timeouts correctly

dtest.py
@smccarthy788 to review.
Testing here:
http://cassci.datastax.com/view/Dev/view/ptnapoleon/job/ptnapoleon-trunk-upgradeing-upgrade/
http://cassci.datastax.com/view/Dev/view/ptnapoleon/job/ptnapoleon-trunk-upgradeing-dtest/
=> Always clone from github, instead of apache

cqlsh_tests/cqlsh_copy_tests.py
This is a new test for [CASSANDRA-12794](https://issues.apache.org/jira/browse/CASSANDRA-12794).
=> New test for CASSANDRA-12794

offline_tools_test.py
=> Test sstabledump with partition deletion + insert

upgrade_tests/cql_tests.py
Follow-up to https://github.com/riptano/cassandra-dtest/pull/1431: @ptnapoleon was obviously right, the initial change was not working for old version and we need to condition this, which is what this PR does.
I'll note that I've never really been able to run upgrade tests locally so while it's a simple patch, it's basically untested.
=> Proper fix for upgrade test post-CASSANDRA-12694

upgrade_tests/upgrade_base.py
Joel, which test should I run 1000x times to confirm this fixes the issue?
=> Set consistency level on connection to both nodes in do_upgrade

cqlsh_tests/cqlsh_copy_tests.py, cqlsh_tests/cqlsh_tools.py
This is a new test for [CASSANDRA-13185](https://issues.apache.org/jira/browse/CASSANDRA-13185).
=> New test for CASSANDRA-13185

cqlsh_tests/cqlsh_copy_tests.py
A new test for [CASSANDRA-13071](https://issues.apache.org/jira/browse/CASSANDRA-13071) and the missing `@jira_ticket` for CASSANDRA-13185.
=> New test for CASSANDRA-13071

auth_test.py
=> Add dtest for CASSANDRA-13053

repair_tests/repair_test.py
Complementary dtest for [CASSANDRA-13153](https://issues.apache.org/jira/browse/CASSANDRA-13153)
=> Add repair test for CASSANDRA-13153

upgrade_tests/cql_tests.py
A simple upgrade test using materialized views to reproduce the bug from CASSANDRA-13382
=> Add test to reproduce CASSANDRA-13382

cqlsh_tests/cqlsh_copy_tests.py
A new test case that tests [CASSANDRA-13364](https://issues.apache.org/jira/browse/CASSANDRA-13364).
=> Added test case for CASSANDRA-13364

snapshot_test.py
Jira: https://issues.apache.org/jira/browse/CASSANDRA-13483
=> CASSANDRA-13483: fixed test failure in snapshot_test.TestSnapshot.test_snapshot_and_restore_dropping_a_column

hintedhandoff_test.py
dtest added for https://issues.apache.org/jira/browse/CASSANDRA-11720
=> New test for CASSANDRA-11720; Changing `max_hint_window_in_ms` at runtime

cqlsh_tests/cqlsh_tests.py
=> Include quoted index names in describe test

upgrade_tests/regression_test.py
A test for [CASSANDRA-13559](https://issues.apache.org/jira/browse/CASSANDRA-13559), see ticket for more details.
=> Test for CASSANDRA-13559

byteman/index_build_failure.btm, secondary_indexes_test.py, sstable_generation_loading_test.py
Add tests about secondary index (re)build failure and concurrency handling
=> CASSANDRA-10130
